* Cavern Dwellers
** Ankheg Group, Large
*Bite (d8+1 damage) 10 HP 3 Armor*
*Close, Reach*
*Special Qualities:* Burrowing
A hide like plate armor and great crushing mandibles are problematic. A stomach
full of acid that can burn a hole through a stone wall makes them all the worse.
They’d be bad enough if they were proper insect-sized, but these things have the
gall to be as long as any given horse. It’s just not natural! Good thing they
tend to stick to one place? Easy for you to say—you don’t have an ankheg living
under your corn field. /Instinct/: To undermine
    - Undermine the ground
    - Burst from the earth
    - Spray forth acid, eating away at metal and flesh
** Cave Rat Horde, Small
*Gnaw (d6 damage 1 piercing) 7 HP 1 Armor*
*Close, Messy*
Who hasn’t seen a rat before? It’s like that, but nasty and big and not afraid
of you anymore. Maybe this one was a cousin to that one you caught in a trap or
the one you killed with a knife in that filthy tavern in Darrow. Maybe he’s
looking for a little ratty revenge. /Instinct/: To devour
    - Swarm
    - Rip something (or someone) apart
** Choker Solitary, Stealthy, Intelligent
*Choke (d10 damage) 15 HP 2 Armor*
*Close, Reach*
*Special Qualities:* Flexible
Some say these things descended from the family of a cruel wizard who forced
them to live out their lives underground. They say his experiments led him to
fear the sun and ages passed while he descended into unlife, dragging his folk
along with him. These things resemble men, in a way. Head, four limbs and all
that. Only their skin is wet and rubbery and their arms long and fingers
grasping. They hate all life that bears the stink of the sun’s touch, as one
might expect. Jealousy, long-instilled, is hard to shake. /Instinct/: To deny
light
    - Hold someone, wringing the breath from them
    - Fling a held creature
** Cloaker Solitary, Stealthy
*Constrict (d10 damage ignores armor) 12 HP 1 Armor*
*Close*
*Special Qualities:* Looks like a cloak
Don’t put on that cloak, Gareth. Don’t. You don’t know where it’s been. I tell
you, it’s no good. See! It moved! I’m not mad, Gareth, it moved! Don’t do it!
No! GARETH! /Instinct/: To engulf
    - Engulf the unsuspecting
** Dwarven Warrior Horde, Organized
*Axe (d6 damage) 7 HP 2 Armor*
*Close*
For ages, men believed all dwarves were male and all were of this ilk: stoic and
proud warriors. Axe-wielding and plate-wearing. Stout bearded battle-hungry
dwarves who would push them, time and time again, back up out of their mines and
tunnels with ferocity. It just goes to show how little men know about the elder
races. These folk are merely a vanguard, and they bravely do their duty to
protect the riches of the Dwarven realm. Earn their trust and you’ve an ally for
life. Earn their ire and you’re not likely to regret it very long. /Instinct/:
To defend
    - Drive them back
    - Call up reinforcements
** Earth Elemental Solitary, Huge
*Smash (d10+5 damage) 27 HP 4 Armor*
*Reach, Forceful*
*Special Qualities:* Made of stone
Our shaman says that all the things of the world have a spirit. Stones, trees, a
stream. Now that I’ve seen the earth roil under my feet and fists of stone beat
my friends half to death I’d like to believe that crazy old man. The one I saw
was huge—big as a house! It came boiling up from a rockslide out of nowhere and
had a voice like an avalanche. I pay my respects, now. Rightly so. /Instinct/:
To show the strength of earth
    - Turn the ground into a weapon
    - Meld into stone
** Fire Beetle Horde, Small
*Flames (d6 damage ignores armor) 3 HP 3 Armor*
*Near*
*Special Qualities:* Full of flames
/Scarabaeus pyractomena/! What a delightful creature—see how its carapace
glitters in the light of our torches? Not too close now, they’re temperamental,
you see. The fire in their belly isn’t just metaphorical, no. Watch as I goad
the beast. Aha! A spout of flame! Unexpected, isn’t it? One of these creatures
alone, if it comes up from below, can be a hellish nuisance to a farmstead or
village. A whole swarm? There’s a reason they call it a conflagration of fire
beetles. /Instinct/: To enflame
    - Undermine the ground
    - Burst from the earth
    - Spray forth flames
** Gargoyle Horde, Stealthy, Hoarder
*Claw (d6 damage) 3 HP 2 Armor*
*Close*
*Special Qualities:* Wings
It’s a sad thing, really. Guardians bred by magi of the past with no more
castles to guard. Their ancestors’ sacred task bred into their blood leads them
to find a place—ruins mostly, but sometimes a cave or hill or mountain cliff—and
guard it as though their masters yet lived below. They’re notoriously good at
finding valuables buried below the earth, though. Find one of these winged
reptiles and you’ll find yourself a treasure nearby. Just be careful, they’re
hard to spot and tend to move in packs. /Instinct/: To guard
    - Attack with the element of surprise
    - Take to the air
    - Blend into stonework
** Gelatinous Cube Solitary, Large, Stealthy, Amorphous
*Engulf (d10+1 damage ignores armor) 20 HP 1 Armor*
*Hand*
*Special Qualities:* Transparent
How many adventurers’ last thoughts were “strange, this tunnel seems cleaner
than most?” Too many, and all because of this transparent menace. A great acidic
blob that expands to fill a small chamber or corridor and then slides, ever so
slowly along, eating everything in its path. It cannot eat stone or metal and
will often have them floating in its jelly mass. Blech. /Instinct/: To clean
    - Fill an apparently empty space
    - Dissolve
** Goblin Horde, Small, Intelligent, Organized
*Spear (d6 damage) 3 HP 1 Armor*
*Close, Reach*
Nobody seems to know where these things came from. Elves say they’re the
dwarves’ fault—dredged up from a hidden place beneath the earth. Dwarves say
they’re bad elvish children, taken away at birth and raised in the dark. The
truth of the matter is that goblins have always been here and they’ll be here
once all the civilized races have fallen and gone away. Goblins never die out.
There’s just too damn many of them. /Instinct/: To multiply
    - Charge!
    - Call more goblins
    - Retreat and return with (many) more
** Goblin Orkaster Solitary, Small, Magical, Intelligent, Organized
*Acid orb (d10+1 damage ignores armor) 12 HP 0 Armor*
*Near, Far*
Oh lord, who taught them magic? /Instinct/: To tap power beyond their stature
    - Unleash a poorly understood spell
    - Pour forth magical chaos
    - Use other goblins for shields
** Goliath Group, Huge, Organized, Intelligent
*Mace (d8+7 damage) 14 HP 1 Armor*
*Reach, Forceful*
They dwell beneath the earth because they do not belong above it any longer. An
undying race of mighty titans fled the plains and mountains in ages past—driven
out by men and their heroes. Left to bide their time in the dark, hate and anger
warmed by the pools of lava deep below. It’s said that an earthquake is a
goliath’s birthing cry. Someday they’ll take back what’s theirs. /Instinct/: To
retake
    - Shake the earth
    - Retreat, only to come back stronger
** Otyugh Solitary, Large
*Tentacles (d10+3 damage) 20 HP 1 Armor*
*Close, Reach, Forceful*
*Special Qualities:* Filth Fever
The mating call of the otyugh is a horrible, blaring cry that sounds like a
cross between an elephant dying and an over-eager vulture. The otyugh spends
much of its time partly submerged in filthy water and prefers eating garbage
over any other food. As a result, it often grows fat and strong on the offal of
orcs, goblins and other cave-dwelling sub-humans. Get too close, however, and
you’ll have one of its barbed tentacles dragging you into that soggy,
razor-toothed maw. If you get away with your life, best get to a doctor, or your
victory may be short lived. /Instinct/: To befoul
    - Infect someone with filth fever
    - Fling someone or something
** Maggot-Squid Horde, Small
*Chew (d6 damage) 3 HP 1 Armor*
*Close*
*Special Qualities:* Amphibious, Paralyzing Tentacles
The gods that made this thing were playing some sick joke on the civilized folk
of the world. The maggot-squid wields a face full of horrible squirming
tentacles that, if they touch you, feel like being struck by lightning. They’ll
paralyze you and chew you up slowly while you’re helpless. Best to not let it
get to that. /Instinct/: To eat
    - Paralyze with a touch
** Purple Worm Solitary, Huge
*Bite (d10+5 damage) 20 HP 2 Armor*
*Reach, Forceful*
*Special Qualities:* Burrowing
Iä! Iä! The Purple Worm! Blessed is its holy slime! We walk, unworthy, in its
miles of massive tunnels. We are but shadows under its violet and all-consuming
glory. Mere acolytes, we who hope someday to return to the great embrace of its
tooth-ringed maw. Let it consume us! Let it eat our homes and villages so that
we might be taken! Iä! Iä! The Purple Worm! /Instinct/: To consume
    - Swallow whole
    - Tunnel through stone and earth
** Roper Solitary, Large, Stealthy, Intelligent
*Bite (d10+1 damage) 16 HP 1 Armor*
*Close, Reach*
*Special Qualities:* Rock-like Flesh
Evolutionary happenstance has created a clever underground predator. Disguised
as a rocky formation—most often a stalactite or stalagmite—the roper waits for
its prey to wander by. When it does, whether it’s a rat, a goblin or a foolhardy
adventurer, a mass of thin, whipping tentacles erupts from the thing’s hide. A
hundred lashes in the blink of an eye and the stunned prey is being dragged into
the roper’s mouth. Surprisingly effective for a thing that looks like a rock.
/Instinct/: To ambush
    - Ensnare the unsuspecting
    - Disarm a foe
    - Chew on someone
** Rot Grub Horde, Tiny
*Burrow (d6-2 damage) 3 HP 0 Armor*
*Hand*
*Special Qualities:* Burrow into flesh
They live in your skin. Or your organ meat. Or your eyeballs. They grow there
and then, in a bloody and horrific display, burrow their way out. Disgusting.
/Instinct/: To infect
    - Burrow under flesh
    - Lay eggs
    - Burst forth from an infected creature
** Spiderlord Solitary, Large, Devious, Intelligent
*Mandibles (d8+4 damage) 16 HP 3 Armor*
*Close, Reach*
*Special Qualities:* Burrowing
Even spiders have their gods, whispered to in webs with little praying arms.
/Instinct/: To weave webs (literal and metaphorical)
    - Enmesh in webbing
    - Put a plot into motion
** Troglodyte Group, Organized
*Club (d8 damage) 10 HP 1 Armor*
*Close*
Long-forgotten, our last remaining ancestors dwell in caves in the wild parts of
the world. Driven away by our cities and villages, our iron swords and our fire,
these ape-men eat their meat raw with sharp-nailed hands and jagged teeth. They
strike out at frontier villages wielding clubs and in overwhelming numbers to
seize cattle, tools, and poor prisoners to drag into the hills. Known for their
viciousness and their stink, they’re an old and dying race we’d all sooner
forget existed. /Instinct/: To prey on civilization
    - Raid and retreat
    - Use scavenged weapons or magic
