
* The Fighter
It’s a thankless job—living day to day by your armor and the skill of your arm.
To dive heedlessly into danger. They won’t be playing golden horns for the time
you took that knife to the ribs for them in the bar in Bucksberg. No flock of
angels to sing of the time you dragged them, still screaming, from the edge of
the Pits of Madness, no.

Forget them.

You do this for the guts and the glory. The scream of battle and the hot, hot
blood of it. You are a beast of iron. Your friends may carry blades of forged
steel but, fighter, you are steel. While your traveling companions might moan
about their wounds over a campfire in the wilderness, you bear your scars with
pride.

You are the wall—let every danger smash itself to nothing on you. In the end,
you’ll be the last one standing.
** Names
/Dwarf/: Ozruk, Surtur, Brunhilda, Annika, Janos, Greta, Dim, Rundrig, Jarl,
Xotoq  
/Elf/: Elohiir, Sharaseth, Hasrith, Shevaral, Cadeus, Eldar, Kithracet, Thelian    
/Halfling/: Finnegan, Olive, Randolph, Bartleby, Aubrey, Baldwin, Becca 
/Human/: Hawke, Rudiger, Gregor, Brianne, Walton, Castor, Shanna, Ajax, Hob
** Look
Choose one for each:
Hard Eyes, Dead Eyes, or Eager Eyes
Wild Hair, Shorn Hair, or Battered Helm
Calloused Skin, Tanned Skin, or Scarred Skin
Built Body, Lithe Body, or Ravaged Body
** Stats
Your maximum HP is 10+Constitution.
Your base damage is d10.
** Starting Moves
Choose a race and gain the corresponding move:
*** Dwarf
When you *share a drink with someone*, you may parley with them using CON
instead of CHA.
*** Elf
Choose one weapon—you can always treat weapons of that type as if they had the
precise tag.
*** Halfling
When you defy danger and *use your small size to your advantage*, take +1.
*** Human
Once per battle you may reroll a single damage roll (yours or someone else’s).
You start with these moves:
*** Bend Bars, Lift Gates
When you *use pure strength to destroy an inanimate obstacle*, roll+Str. ✴On a
10+, choose 3. ✴On a 7-9 choose 2.
    - It doesn’t take a very long time
    - Nothing of value is damaged
    - It doesn’t make an inordinate amount of noise
    - You can fix the thing again without a lot of effort
*** Armored
You ignore the clumsy tag on armor you wear.
*** Signature Weapon
This is your weapon. There are many like it, but this one is yours. Your weapon
is your best friend. It is your life. You master it as you master your life.
Your weapon, without you, is useless. Without your weapon, you are useless. You
must wield your weapon true.

Choose a base description, all are 2 weight:
    - Sword
    - Axe
    - Hammer
    - Spear
    - Flail
    - Fists
Choose the range that best fits your weapon:
    - Hand
    - Close
    - Reach
Choose two enhancements:
    - Hooks and spikes. +1 damage, but +1 weight.
    - Sharp. +2 piercing.
    - Perfectly weighted. Add precise.
    - Serrated edges. +1 damage.
    - Glows in the presence of one type of creature, your choice.
    - Huge. Add messy and forceful.
    - Versatile. Choose an additional range.
    - Well-crafted. -1 weight.
Choose a look:
    - Ancient
    - Unblemished
    - Ornate
    - Blood-stained
    - Sinister
** Alignment
Choose an alignment:
*** Good
Defend those weaker than you.
*** Neutral
Defeat a worthy opponent.
*** Evil
Kill a defenseless or surrendered enemy.
** Gear
Your load is 12+Str. You carry your signature weapon and dungeon rations (5
uses, 1 weight). Choose your defenses:
    - Chainmail (1 armor, 1 weight) and adventuring gear (1 weight)
    - Scale armor (2 armor, 3 weight)
Choose two:
    - 2 Healing potions (0 weight)
    - Shield (+1 armor, 2 weight)
    - Antitoxin (0 weight), dungeon rations (1 weight), and poultices and herbs
      (1 weight)
    - 22 coins
** Bonds
Fill in the name of one of your companions in at least one:

_______________ owes me their life, whether they admit it or not.

I have sworn to protect _______________.

I worry about the ability of _______________ to survive in the dungeon.

_______________ is soft, but I will make them hard like me.
** Advanced Moves
When you gain a level from 2-5, choose from these moves.
*** Merciless
When you deal damage, deal +1d4 damage.
*** Heirloom
When you *consult the spirits that reside within your signature weapon*, they
will give you an insight relating to the current situation, and might ask you
some questions in return, roll+CHA. ✴On a 10+, the GM will give you good detail.
✴On a 7-9, the GM will give you an impression.
*** Armor Mastery
When you *make your armor take the brunt of damage dealt to you*, the damage is
negated but you must reduce the armor value of your armor or shield (your
choice) by 1. The value is reduced each time you make this choice. If the
reduction leaves the item with 0 armor it is destroyed.
*** Improved Weapon
Choose one extra enhancement for your signature weapon.
*** Seeing Red
When you discern realities during combat, you take +1.
*** Interrogator
When you *parley using threats of impending violence as leverage*, you may use
STR instead of CHA.
*** Scent of Blood
When you hack and slash an enemy, your next attack against that same foe deals
+1d4 damage.
*** Multiclass Dabbler
Get one move from another class. Treat your level as one lower for choosing the
move.
*** Iron Hide
You gain +1 armor.
*** Blacksmith
When you have access to a forge you can graft the magical powers of a weapon
onto your signature weapon. This process destroys the magical weapon. Your
signature weapon gains the magical powers of the destroyed weapon.
When you gain a level from 6-10, choose from these moves or the level 2-5 moves.
*** Bloodthirsty
Replaces: Merciless
When you deal damage, deal +1d8 damage.
*** Armored Perfection
Replaces: Armor Mastery
When you *choose to let your armor take the brunt of damage dealt to you*, the
damage is negated and you take +1 forward against the attacker, but you must
reduce the armor value of your armor or shield (your choice) by 1. The value is
reduced each time you make this choice. If the reduction leaves the item with 0
armor it is destroyed.
*** Evil Eye
Requires: Seeing Red
When you *enter combat*, roll+CHA. ✴On a 10+, hold 2. ✴On a 7-9, hold 1. Spend
your hold to make eye contact with an NPC present, who freezes or flinches and
can’t act until you break it off. ✴On a 6-, your enemies immediately identify
you as their biggest threat.
*** Taste of Blood
Replaces: Scent of Blood
When you hack and slash an enemy, your next attack against that same foe deals
+1d8 damage.
*** Multiclass Initiate
Requires: Multiclass Dabbler
Get one move from another class. Treat your level as one lower for choosing the
move.
*** Steel Hide
Replaces: Iron Hide
You gain +2 armor.
*** Through Death’s Eyes
When you *go into battle*, roll+WIS. ✴On a 10+, name someone who will live *and*
someone who will die. ✴On a 7-9, name someone who will live *or* someone who
will die. Name NPCs, not player characters. The GM will make your vision come
true, if it’s even remotely possible. ✴On a 6- you see your own death and
consequently take -1 ongoing throughout the battle.
*** Eye for Weaponry
When you look over an enemy’s weaponry, ask the GM how much damage they do.
*** Superior Warrior
When you hack and slash on a 12+ you deal your damage, avoid their attack, and
impress, dismay, or frighten your enemy.