
* First Session
The first session of a game of Dungeon World begins with character creation.
Character creation is also world creation, the details on the character sheets
and the questions that you ask establish what Dungeon World is like—who lives in
it and what’s going on.

This section is for the GM so it’s addressed to you—the GM. For the players, the
first session is just like every other. They just have to play their characters
like real people and explore Dungeon World. You have to do a little more in the
first session. You establish the world and the threats the players will face.
** Prep
Before the first session, you’ll need to print some stuff. Print off:
    - A few copies of the basic moves
    - One copy of each class sheet, double-sided
    - One copy each of the cleric and wizard spell sheets, double-sided
    - The GM sheet
You’ll also need to read this whole book, especially the sections on GMing (GM
moves) and the basic moves. It’s a good idea to be acquainted with the class
moves too, so you can be prepared for them. Be especially sure to read the rules
for fronts, but don’t create any yet.

Think about fantastic worlds, strange magic, and foul beasts. Remember the games
you played and the stories you told. Watch some movies, read some comics; get
heroic fantasy into your brain.

What you bring to the first session, ideas-wise, is up to you. At the very least
bring your head full of ideas. That’s the bare minimum.

If you like you can plan a little more. Maybe think of an evil plot and who’s
behind it, or some monsters you’d like to use.

If you’ve got some spare time on your hands you can even draw some maps (but
remember, from your principles: leave blanks) and imagine specific locations.

The one thing you absolutely can’t bring to the table is a planned storyline or
plot. You don’t know the heroes or the world before you sit down to play so
planning anything concrete is just going to frustrate you. It also conflicts
with your agenda: play to find out what happens.
*** Getting Started
When everyone shows up for the first session briefly introduce Dungeon World to
anyone who hasn’t played before. Cover the mechanical basis of moves. Introduce
the character classes, help players pick their classes, and walk them through
character creation.

Your role during character creation is threefold: help everyone, ask questions,
and take notes. When a player makes a choice—particularly for their bonds—ask
them about it. Get more detail. Think about what these details mean.

You should also set expectations: the players are to play their characters as
people—skilled adventurers delving into dangerous places, but real people. Your
role is to play the rest of the world as a dynamic, changing place.

Some questions commonly come up during character creation. You should be ready
to answer them:

/Are the characters friends?/ No, not necessarily, but they do work together as
a team for common goals. Their reasons for pursuing those goals may be
different, but they manage to work together.

/Are there other wizards?/ Not really. There are other workers of arcane magic,
and the common folk may call them wizards, but they’re not like you. They don’t
have the same abilities, though they may be similar. Later on there may be
another player character with the same class but no GM character will ever
really be a wizard (or any other class).

/What’s coin?/ Coin’s the currency of the realm. It’s good pretty much
everywhere. It’ll buy you mundane stuff, like steel swords and wooden staves.
The special stuff, like magic weapons, isn’t for sale. Not for coin, anyway…

/Is the GM trying to kill us?/ No. The GM’s job is to portray the world and the
things in it and the world is a very dangerous place. You might die. That
doesn’t mean the GM is out to get you.

During this entire process, especially character creation, ask questions. Look
for interesting facts established by the characters’ bonds, moves, classes, and
descriptions and ask about those things. Be curious! When someone mentions the
demons that slaughtered their village find out more about them. After all, you
don’t have anything (except maybe a dungeon) and everything they give you is
fuel for future adventures.

Also pay attention to the players’ questions. When mechanical questions come up
answer them. When questions of setting or fiction come up your best bet is to
turn those questions around. When a player says, “Who is the King of Torsea,”
say, “I don’t know. Who is it? What is he like?” Collaborate with your players.
Asking a question means it’s something that interests them so work with them to
make the answers interesting. Don’t be afraid to say, “I don’t know” and ask
them the same questions. Work together to find a fantastic and interesting
answer.

If you’ve come to the table with some ideas about stuff you’d like to see in the
world, share them with the players. Their characters are their responsibility
and the world is yours—you’ve got a lot of say in what lives in it. If you want
the game to be about a hunt for the lost sorcerer-race of aeons past, say so! If
the players aren’t interested or they’re sick to death of sorcerers, they’ll let
you know and you can work together to find some other way. You don’t need
pre-approval for everything but making sure everyone is excited about the broad
strokes of the world is a great start.

Once everyone has their characters created you can take a deep breath. Look back
over the questions you’ve asked and answered so far. You should have some notes
that will point you towards what the game might look like. Look at what the
players have brought to the table. Look to the ideas that’ve been stewing away
in your head. It’s time for the adventure to begin!
*** The First Adventure
The first adventure is really about discovering the direction that future
sessions will take. Throughout the first adventure keep your eye out for
unresolved threats; note dangerous things that are mentioned but not dealt with.
These will be fuel for sessions to come.

Start the session with a group of player characters (maybe all of them) in a
tense situation. Use anything that demands action: outside the entrance to a
dungeon, ambushed in a fetid swamp, peeking through the crack in a door at the
orc guards, or being sentenced before King Levus. Ask questions right away—“who
is leading the ambush against you?” or “what did you do to make King Levus so
mad?” If the situation stems directly from the characters and your questions,
all the better.

Here’s where the game starts. The players will start saying and doing things,
which means they’ll start making moves. For the first session you should watch
especially carefully for when moves apply, until the players get the hang of it.
Often, in the early sessions, the players will be most comfortable just
narrating their actions—this is fine. When a move triggers let them know. Say,
“It sounds like you’re trying to…” and then walk them through the move. Players
looking for direction will look to their character sheet. When a player just
says “I hack and slash him” be quick to ask, “so what are you actually doing?”
Ask “How?” or “With what?”

For the first session, you have a few specific goals:
    - Establish details, describe
    - Use what they give you
    - Ask questions
    - Leave blanks
    - Look for interesting facts
    - Help the players understand the moves
    - Give each character a chance to shine
    - Introduce NPCs
**** Establish details, describe
All the ideas and visions in your head don’t really exist in the fiction of the
game until you share them, describe them, and detail them. The first session is
the time to establish the basics of what things look like, who’s in charge, what
they wear, what the world is like, what the immediate location is like. Describe
everything but keep it brief enough to expand on later. Use a detail or two to
make a description really stand out as real.
**** Use what they give you
The best part of the first session is you don’t have to come with anything
concrete. You might have a dungeon sketched out but the players provide the real
meat—use it. They’ll emerge from the darkness of that first dungeon and when
they do and their eyes adjust to the light, you’ll have built up an exciting
world to explore with their help. Look at their bonds, their moves, how they
answer your questions and use what you find to fill in the world around the
characters.
**** Ask questions
You’re using what they give you, right? What if you need more? That’s when you
draw it out by asking questions. Poke and prod about specific things. Ask for
reactions: “What does Lux think about that?” “Is Avon doing something about it?”

If you ever find yourself at a loss, pause for a second and ask a question. Ask
one character a question about another. When a character does something, ask how
a different character feels or reacts. Questions will power your game and make
it feel real and exciting. Use the answers you find to fill in what might happen
next.
**** Leave blanks
This is one of your principles, but it’s especially true during the first
session. Every blank is another cool thing waiting to happen; leave yourself a
stock of them.
**** Look for interesting facts
There are some ideas that, when you hear them, just jump out at you. When you
hear one of those ideas, just write it down. When a player mentions the Duke of
Sorrows being the demon he bargained with, note it. That little fact is the seed
for a whole world.
**** Help the players understand the moves
You’ve already read the game, the players may not have, so it’s up to you to
help them if they need it. The fact is, they likely won’t need it much. All they
have to do is describe what their character does, the rules take care of the
rest.

The one place they may need some help is remembering the triggers for the moves.
Keep an ear out for actions that trigger moves, like attacking in melee or
consulting their knowledge. After a few moves the players will likely remember
them on their own.
**** Give each character a chance to shine
As a fan of the heroes (remember your agenda?) you want to see them do what they
do best. Give them a chance at this, not by tailoring every room to their
skills, but by portraying a fantastic world (agenda again) where there are many
solutions to every challenge.
**** Introduce NPCs
NPCs bring the world to life. If every monster does nothing more than attack and
every blacksmith sets out their wares for simple payment the world is dead.
Instead give your characters, especially those that the players show an interest
in, life (principles, remember?). Introduce NPCs but don’t protect them. The
recently deceased Lord of Goblins is just as useful for future adventures as the
one who’s still alive.
** After the First Session
Once you’re done with the first session take some time to relax. Let ideas
ferment. Don’t rush into the next session.

Once you’ve had some time to relax and think over the first session it’s time to
prepare for the next session. Preparing for the second session takes a few
minutes, maybe an hour if this is your first time. You’ll create fronts, maybe
make some monsters or custom moves, and generally get an idea of what is going
on in the world.
