* Fronts
Fronts are secret tomes of GM knowledge. Each is a collection of linked
dangers—threats to the characters specifically and to the people, places, and
things the characters care about. It also includes one or more impending dooms,
the horrible things that will happen without the characters’ intervention.
“Fronts” comes, of course, from “fighting on two fronts” which is just where you
want the characters to be—surrounded by threats, danger and adventure.

Fronts are built outside of active play. They’re the solo fun that you get to
have between games—rubbing your hands and cackling evilly to yourself as you
craft the foes with which to challenge your PCs. You may tweak or adjust your
fronts during play (who knows when inspiration will strike?) but the meat of
them comes from preparation between sessions.

Fronts are designed to help you organize your thoughts on what opposes the
players. They’re here to contain your notes, ideas, and plans for these opposing
forces. When you’re in a bind your fronts are where you’re going to turn and
say, “Oh, so /that’s/ what I should do.” Consider them an organizational tool,
as inspiration for present and future mayhem.

When you’re building fronts, think about all the creepy dungeon denizens, the
rampaging hordes and ancient cults that you’d like to see in your game. Think in
broad strokes at first and then, as you build dangers into your fronts, you’ll
be able to narrow those ideas down. When you write your campaign front, think
about session-to-session trends. When you write your adventure fronts, think
about what’s important right here and right now. When you’re done writing a few
fronts you’ll be equipped with all the tools you’ll need to challenge your
players and ready to run Dungeon World.
*** When to Make Fronts
You’ll make your campaign front and first adventure fronts /after/ your first
session. Your campaign front may not be complete when you first make it—that’s
great! Just like blanks on a map, unknown parts of your campaign front are
opportunities for future creativity.

After that first session you’ll also make some adventure fronts. One or two is
usually a good number. If you find yourself with more adventure fronts consider
leaving some possible fronts as just notes for now.
*** Campaign and Adventure Fronts
At their core, all fronts contain the same components. They sort and gather your
dangers into easy-to-use clusters. There are, however, two different /kinds/ of
fronts available to you. On the session-to-session level there are your
adventure fronts. These fronts will see use for a few sessions each. They’re
tied to one problem and will be dealt with or cast aside as the characters
wander the dungeon or uncover the plot at hand. Think of them as episodic
content: “Today, on Dungeon World…”

Tying your adventure fronts together is your campaign front. While the adventure
fronts will contain immediate dangers—the orcs in Hargrosh Pass, say—the
campaign front contains the Dark God Grishkar who drives the orcs to their
pillaging. The campaign front is the unifying element that spans all the
sessions of your Dungeon World game. It will have slower-burning portents but
they’ll be bigger in scope and have a deeper impact on the world. Most
importantly they’ll be scarier if they’re allowed to resolve.

When a danger from an adventure front goes without resolution you’ll have to
make a decision. If the danger is something you like and feel has a place in the
larger world of your game don’t hesitate to move it to the campaign front.
You’re able to make smaller dangers that went unresolved into bigger dangers
some day later on. You can move dangers from the campaign fronts to an adventure
front if they’ve come to bear, too.
** Creating Fronts
Here’s how a front comes together:
    - Choose campaign front or adventure front
    - Create 2-3 dangers
    - Choose an impending doom for each danger
    - Add grim portents (1-3 for an adventure front, 3-5 for the campaign front)
    - Write 1–3 stakes questions
    - List the general cast of the front
** Creating Dangers
Not every element of your game will warrant a danger—traps, some roving
monsters, and other bits of ephemera may just be there to add context but aren’t
important enough to warrant inclusion. That’s okay. Fronts are here to keep you
apprised of the bigger picture. Dangers are divided into a handful of
categories, each with its own name and *impulse*.

Every danger has a crucial motivation that drives it called its impulse. The
impulse exists to help you understand that danger. What pushes it to fulfill its
impending doom? Impulses can help you translate the danger into action.

When creating dangers for your front, think about how each one interacts as a
facet of the front as a whole. Keep in mind the people, places, and things that
might be a part of the threat to the world that the front represents. How does
each danger contribute to the front?
Let’s say we have an idea for a front—an ancient portal has been discovered in
the icy north. We’ll call our front “The Opening of the White Gate.”
The easiest place to start is with people and monsters. Cultists, ogre
chieftains, demonic overlords, and the like are all excellent dangers. These are
the creatures that have risen above mere monster status to become serious
threats on their own. Groups of monsters can be dangers too—goblin tribes or a
rampaging centaur khanate, for example.
For the front we’re creating, we can pick a few different groups or people who
might be interested in the gate. The College of Arcanists, perhaps. There’s a
golem, too, we’ve decided, that protects the forgotten portal. The golem is just
an obstacle, so we won’t make him a danger.
Thinking more broadly, less obvious elements of the world can be dangers.
Blasted landscapes, intelligent magical items, ancient spells woven into the
fabric of time. These things fulfill the same purposes as a mad
necromancer—they’re part of the front, a danger to the world.
For our front, we’ll add the gate itself as a danger.
Lastly, if we think ahead, we can include some overarching dangers. The sorts of
things that are in play outside the realm of the obvious—godly patrons, hidden
conspiracies and cursed prophecies waiting to be fulfilled.
Perhaps the White Gate was carved in the ancient past, hidden by a race of
angels until the Day of Judgement. We’ll add the Argent Seraphim to our front as
a new danger.
There’s always more dangers you could add to a front, but limit yourself to 3 at
most and leave room for discovery. Like a map, blank spaces can always be filled
in later. Leaving room for player contribution and future inspiration means
you’ll have freedom to alter the front and make it fit the game. Not every bad
thing that could happen deserves to be made into a danger. If you’re uncertain,
think about it this way: dangers can always get worse.
A barbarian tribe near the gate, the frozen tundra itself, a band of rival
adventurers; all these things could be dangerous elements of the game but
they’re not important enough just yet to deserve to be dangers.
Creating dangers is a way to slice up your overall front concept into smaller,
easier to manage pieces. Dangers are tools for adding detail to the right parts
of the front and for making the front easier to manage in the long run.

Once you’ve named and added a danger to the front you need to choose a type for
that danger from the list below. Alternately, you can use the list of types to
inspire dangers: with your front in mind, peruse the list and pick one or two
that fit.
For our three dangers (The College of Arcanists, The White Gate and the Argent
Seraphim) we’ve selected Cabal, Dark Portal and Choir of Angels, respectively.
** Types of Dangers
    - Ambitious Organizations
    - Planar Forces
    - Arcane Enemies
    - Hordes
    - Cursed Places
*** Ambitious Organizations
    - Misguided Good (/impulse: to do what is “right” no matter the cost/)
    - Thieves Guild (/impulse: to take by subterfuge/)
    - Cult (/impulse: to infest from within/)
    - Religious Organization (/impulse: to establish and follow doctrine/)
    - Corrupt Government (/impulse: to maintain the status quo/)
    - Cabal (/impulse: to absorb those in power, to grow/)
**** GM Moves for Ambitious Organizations
    - Attack someone by stealthy means (kidnapping, etc.)
    - Attack someone directly (with a gang or single assailant)
    - Absorb or buy out someone important (an ally, perhaps)
    - Influence a powerful institution (change a law, manipulate doctrine)
    - Establish a new rule (within the organization)
    - Claim territory or resources
    - Negotiate a deal
    - Observe a potential foe in great detail
*** Planar Forces
    - God (/impulse: to gather worshippers/)
    - Demon Prince (/impulse: to open the gates of Hell/)
    - Elemental Lord (/impulse: to tear down creation to its component parts/)
    - Force of Chaos (/impulse: to destroy all semblance of order/)
    - Choir of Angels (/impulse: to pass judgement/)
    - Construct of Law (/impulse: to eliminate perceived disorder/)
**** GM Moves for Planar Forces
    - Turn an organization (corrupt or infiltrate with influence)
    - Give dreams of prophecy
    - Lay a Curse on a foe
    - Extract a promise in exchange for a boon
    - Attack indirectly, through intermediaries
    - Rarely, when the stars are right, attack directly
    - Foster rivalries with other, similar powers
    - Expose someone to a Truth, wanted or otherwise
*** Arcane Enemies
    - Lord of the Undead (/impulse: to seek true immortality/)
    - Power-mad Wizard (/impulse: to seek magical power/)
    - Sentient Artifact (/impulse: to find a worthy wielder/)
    - Ancient Curse (/impulse: to ensnare/)
    - Chosen One (/impulse: to fulfill or resent their destiny/)
    - Dragon (/impulse: to hoard gold and jewels, to protect the clutch/)
**** GM Moves for Arcane Enemies
    - Learn forbidden knowledge
    - Cast a spell over time and space
    - Attack a foe with magic, directly or otherwise
    - Spy on someone with a scrying spell
    - Recruit a follower or toady
    - Tempt someone with promises
    - Demand a sacrifice
*** Hordes
    - Wandering Barbarians (/impulse: to grow strong, to drive their enemies
      before them/)
    - Humanoid Vermin (/impulse: to breed, to multiply and consume/)
    - Underground Dwellers (/impulse: to defend the complex from outsiders/)
    - Plague of the Undead (/impulse: to spread/)
**** GM Moves for Hordes
    - Assault a bastion of civilization
    - Embrace internal chaos
    - Change direction suddenly
    - Overwhelm a weaker force
    - Perform a show of dominance
    - Abandon an old home, find a new one
    - Grow in size by breeding or conquest
    - Appoint a champion
    - Declare war and act upon that declaration without hesitation or
      deliberation
*** Cursed Places
    - Abandoned Tower (/impulse: to draw in the weak-willed/)
    - Unholy Ground (/impulse: to spawn evil/)
    - Elemental Vortex (/impulse: to grow, to tear apart reality/)
    - Dark Portal (/impulse: to disgorge demons/)
    - Shadowland (/impulse: to corrupt or consume the living/)
    - Place of Power (/impulse: to be controlled or tamed/)
**** GM Moves for Cursed Places
    - Vomit forth a lesser monster
    - Spread to an adjacent place
    - Lure someone in
    - Grow in intensity or depth
    - Leave a lingering effect on an inhabitant or visitor
    - Hide something from sight
    - Offer power
    - Dampen magic or increase its effects
    - Confuse or obfuscate truth or direction
    - Corrupt a natural law
*** Description and Cast
Write up something short to remind you just what this danger is about, something
to describe it in a nutshell. Don’t worry about where it’s going or what could
happen—grim portents and the impending doom will handle that for you; you’ll get
to those in a bit. If there are multiple people involved in the danger (an orc
warlord and his clansmen, a hateful god and his servants) go ahead and give them
names and a detail or two now. Leave yourself some space as you’ll be adding to
this section as you play.
*** Custom Moves
Sometimes a danger will suggest a move that isn’t covered by any existing ones.
You can write custom moves to fill the gaps or to add the right effects for the
danger. They can be player moves or GM moves, as you see fit. Of course, if
you’re writing a player move, keep your hands off the dice and mind the basic
structure of a move. A 10+ is a complete success, while a 7–9 is a partial
success. On a miss, maybe the custom move does something specific, or maybe
not—maybe you just get to make a move or work towards fulfilling a grim portent.
The formatting of these moves varies from move to move.
For the Opening of the White Gate, I just know some fool PC is going to end up
in the light that spills from the gate, so I’m writing a move to show what might
occur.
When you *stand in the presence of the Light From Beyond*, roll+WIS: ✴On a 10+
you are judged worthy, the Argent Seraphim will grant you a vision or boon. ✴On
a 7-9 you are under suspicion and see a vision of what dark fate might befall
you if you do not correct your ways. ✴On a miss, thou art weighed in the balance
and art found wanting.
*** Grim Portents
Grim portents are dark designs for what could happen if a danger goes unchecked.
Think about what would happen if the danger existed in the world but the PCs
didn’t—if all these awful things you’ve conjured up had their run of the world.
Scary, huh? The grim portents are your way to codify the plans and machinations
of your dangers. A grim portent can be a single interesting event or a chain of
steps. When you’re not sure what to do next, push your danger towards resolving
a grim portent.

More often than not grim portents have a logical order. The orcs tear down the
city only after the peace talks fail, for example. A simple front will progress
from bad to worse to much worse in a clear path forward. Sometimes, grim
portents are unconnected pathways to the impending doom. The early
manifestations of danger might not all be related. It’s up to you to decide how
complex your front will be. Whenever a danger comes to pass, check the other
dangers in the front. In a complex front, you may need to cross off or alter the
grim portents. That’s fine, you’re allowed. Keep scale in mind, too. Grim
portents don’t all have to be world-shaking. They can simply represent a change
in direction for a danger. Some new way for it to cause trouble in the world.

Think of your grim portents as possible moves waiting in the wings. When the
time is right, unleash them on the world.
I’ve chosen a few grim portents for my new front.
    - The College sends an expedition to the Gate
    - The Key is discovered
    - The First Trumpet sounds
    - A Champion is chosen
    - The Second Trumpet sounds
    - The Herald appears
    - The Gate is Opened
When a grim portent comes to pass, check it off—the prophecy has come true! A
grim portent that has come to pass might have ramifications for your other
fronts, too. Have a quick look when your players aren’t demanding your attention
and feel free to make changes. One small grim portent may resound across the
whole campaign in subtle ways.

You can advance a grim portent descriptively or prescriptively. Descriptively
means that you’ve seen the change happen during play, so you mark it off. Maybe
the players sided with the goblin tribes against their lizardman enemies—now the
goblins control the tunnels. Lo and behold, this was the next step in a grim
portent. Prescriptive is when, due to a failed player move or a golden
opportunity, you advance the grim portent as your hard move. That step comes to
pass, show its effects and keep on asking, “What do you do, now?”
*** Impending Doom
At the end of every danger’s path is an impending doom. This is the final toll
of the bell that signals the danger’s triumphant resolution. When a grim portent
comes to pass the impending doom grows stronger, more apparent and present in
the world. These are the very bad things that every danger, in some way, seeks
to bring into effect. Choose one of the types of impending dooms and give it a
concrete form in your front. These often change in play, as the characters
meddle in the affairs of the world. Don’t fret, you can change them later.
    - Tyranny (of the strong over the weak or the few over the many)
    - Pestilence (the spread of sickness and disease, the end of wellness)
    - Destruction (apocalypse, ruin and woe)
    - Usurpation (the chain of order comes apart, someone rightful is displaced)
    - Impoverishment (enslavement, the abandonment of goodness and right)
    - Rampant Chaos (laws of reality, of society, or any order is dissolved)

When all of the grim portents of a danger come to pass, the impending doom sets
in. The danger is then resolved but the setting has changed in some meaningful
way. This will almost certainly change the front at large as well. Making sure
that these effects reverberate throughout the world is a big part of making them
feel real.
*** Stakes
Your stakes questions are 1-3 questions about people, places, or groups that
you’re interested in. People include PCs and NPCs, your choice. Remember that
your agenda includes “Play to find out what happens?” Stakes are a way of
reminding yourself what you want to find out.

Stakes are concrete and clear. Don’t write stakes about vague feelings or
incremental changes. Stakes are about important changes that affect the PCs and
the world. A good stakes question is one that, when it’s resolved, means that
things will never be the same again.

The most important thing about stakes is that you find them interesting. Your
stakes should be things that you genuinely want to know, but that you’re also
willing to leave to be resolved through play. Once you’ve written it as a stake,
it’s out of your hands, you don’t get to just make it up anymore. Now you have
to play to find out.

Playing to find out is one of the biggest rewards of playing Dungeon World.
You’ve written down something tied to events happening in the world that you
want to find out about—now you get to do just that.

Once you have your stakes your front is ready to play.
My stakes questions include, as tailored to my group:
    - Who will be the champion?
    - How will Lux respond to the Light From Beyond?
    - Will the College be able to recruit Avon?
** Resolving a Front
Often a front will be resolved in a simple and straightforward manner. A front
representing a single dungeon may have its dangers killed, turned to good, or
overcome by some act of heroism. In this case the front is dissolved and set
aside. Maybe there are elements of the front—dangers that go unresolved or
leftover members of a danger that’s been cleared—that live on. Maybe they move
to the campaign front as brand new dangers?

The campaign front will need a bit more effort to resolve. It’ll be working
slowly and subtly as the course of the campaign rolls along. You won’t introduce
or resolve it all at once, but in pieces. The characters work towards defeating
the various minions of the big bad that lives in your campaign front. In the
end, though, you’ll know that the campaign front is resolved when the Dark God
is confronted or the undead plague claims the world and the heroes emerge
bloodied but victorious or defeated and despairing. Campaign fronts take longer
to deal with but in the end they’re the most satisfying to resolve.

When a front is resolved take some extra time to sit down and look at the
aftermath. Did any grim portents come to pass? Even if a danger is stopped, if
any grim portents are fulfilled, the world is changed, if only in subtle ways.
Keep this in mind when you write your future fronts. Is there anyone who could
be moved from the now-defeated front to somewhere else? Anyone get promoted or
reduced in stature? The resolution of a front is an important event!

When you resolve an adventure front usually that means the adventure itself has
been resolved. This is a great time to take a break and look at your campaign
front. Let it inspire your next adventure front. Write up a new adventure front
or polish off one you’ve been working on, draw a few maps to go with it and get
ready for the next big thing.
** Multiple Adventure Fronts
As you start your campaign you’re likely to have a lightly detailed campaign
front and one or two detailed adventure fronts. Characters may choose, part-way
through an adventure, to pursue some other course. You might end up with a
handful of partly-resolved adventure fronts. Not only is this okay, it’s a great
way to explore a world that feels alive and organic. Always remember, fronts
continue along apace no matter whether the characters are there to see them or
not. Think offscreen, especially where fronts are concerned.

When running two adventure fronts at the same time they can be intertwined or
independent. The anarchists corrupting the city from the inside are a different
front from the orcs massing outside the walls, but they’d both be in play at
once. On the other hand one dungeon could have multiple fronts at play within
its walls: the powers and effects of the cursed place itself and the warring
humanoid tribes that inhabit it.

A situation warrants multiple adventure fronts when there are multiple impending
dooms, all equally potent but not necessarily related. The impending doom of the
anarchists is chaos in the city, the impending doom of the orcs is its utter
ruination. They are two separate fronts with their own dangers. They’ll deal
with each other, as well, so there’s some room for the players choosing sides or
attempting to turn the dangers of one front against the other.

When dealing with multiple adventure fronts the players are likely to
prioritize. The cult needs attention now, the orcs can wait, or vice versa.
These decisions lead to the slow advancement of the neglected front, eventually
causing more problems for the characters and leading to new adventures. This can
get complex once you’ve got three or four fronts in play. Take care not to get
overwhelmed.
* An Example Front: The Opening of the White Gate
** Dangers
*** The College of Arcanists (Cabal)
*Impulse:* to absorb those in power, to grow
**** Grim Portents
    - The College sends an expedition to the Gate
    - The Key is discovered
    - The Gate’s Power is harnessed
    - The College seizes control
*Impending Doom:* Usurpation
*** The White Gate (Dark Portal)
*Impulse:* to disgorge demons
**** Grim Portents
    - The First Trumpet sounds
    - The Second Trumpet sounds
    - The Gate is opened
*Impending Doom:* Destruction
*** The Argent Seraphim (Choir of Angels)
*Impulse:* to pass judgement
**** Grim Portents
    - A Champion is chosen
    - An organization of power is formed or co-opted
    - The Herald appears
    - Judgement is passed
*Impending Doom:* Tyranny
** Description and Cast
An ancient gate, buried for aeons in the icy north. It opens into a realm of
pure light, guarded by the Argent Seraphim. It was crafted only to be opened at
Judgement Day, so that the Seraphim could come forth and purge the realm of men.
It was recently uncovered by the College of Arcanists, who do not yet understand
its terrible power.
    - Oren Balserus, Arcanist Supreme
    - Hali’el, voice of the Seraphim
    - Drudge, a manservant
** Custom Moves
When you *stand in the presence of the Light From Beyond*, roll+WIS. ✴On a 10+
you are judged worthy, the Argent Seraphim will grant you a vision or boon. ✴On
a 7-9 you are under suspicion and see a vision of what dark fate might befall
you if you do not correct your ways. ✴On a miss, thou art weighed in the balance
and art found wanting.
** Stakes
    - Who will be the Champion?
    - How will Lux respond to the holy light?
    - Will the College be able to recruit Avon?

