
* The Ranger
These city-born folk you travel with. Have they heard the call of the wolf? Felt
the winds howl in the bleak deserts of the East? Have they hunted their prey
with the bow and the knife like you? Hell no. That’s why they need you.

Guide. Hunter. Creature of the wilds. You are these things and more. Your time
in the wilderness may have been solitary until now, but the call of some greater
thing—call it fate if you like—has cast your lot with these folk. Brave, they
may be. Powerful and strong, too. You know the secrets of the spaces between,
though.

Without you, they’d be lost. Blaze a trail through the blood and dark, strider.
** Names
/Elf/: Throndir, Elrosine, Aranwe, Celion, Dambrath, Lanethe 
/Human/: Jonah, Halek, Brandon, Emory, Shrike, Nora, Diana
** Look
Choose one for each:
Wild Eyes, Sharp Eyes, or Animal Eyes
Hooded Head, Wild Hair, or Bald
Cape, Camouflage, or Traveling Clothes
Lithe Body, Wild Body, or Sharp Body
** Stats
Your maximum HP is 8+Constitution.
Your base damage is d8.
** Starting Moves
Choose a race and gain the corresponding move:
*** Elf
When you undertake a perilous journey through wilderness whatever job you take
you succeed as if you rolled a 10+.
*** Human
When you make camp in a dungeon or city, you don’t need to consume a ration.
You start with these moves:
*** Hunt and Track (Wis)
When you *follow a trail of clues left behind by passing creatures*, roll+WIS.
✴On a 7+, you follow the creature’s trail until there’s a significant change in
its direction or mode of travel. ✴On a 10+, you also choose 1:
    - Gain a useful bit of information about your quarry, the GM will tell you
      what
    - Determine what caused the trail to end
*** Called Shot
When you *attack a defenseless or surprised enemy at range*, you can choose to
deal your damage or name your target and roll+DEX.
    - Head ✴10+: As 7–9, plus your damage ✴7-9: They do nothing but stand and
      drool for a few moments.
    - Arms ✴10+: As 7-9, plus your damage ✴7-9: They drop anything they’re
      holding.
    - Legs ✴10+: As 7-9, plus your damage ✴7-9: They’re hobbled and slow moving.
*** Animal Companion
You have a supernatural connection with a loyal animal. You can’t talk to it per
se but it always acts as you wish it to. Name your animal companion and choose a
species:
Wolf, cougar, bear, eagle, dog, hawk, cat, owl, pigeon, rat, mule
Choose a base:
    - Ferocity +2, Cunning +1, 1 Armor, Instinct +1
    - Ferocity +2, Cunning +2, 0 Armor, Instinct +1
    - Ferocity +1, Cunning +2, 1 Armor, Instinct +1
    - Ferocity +3, Cunning +1, 1 Armor, Instinct +2
Choose as many strengths as its ferocity:
Fast, burly, huge, calm, adaptable, quick reflexes, tireless, camouflage,
ferocious, intimidating, keen senses, stealthy
Your animal companion is trained to fight humanoids. Choose as many additional
trainings as its cunning:
Hunt, search, scout, guard, fight monsters, perform, labor, travel
Choose as many weaknesses as its instinct:
Flighty, savage, slow, broken, frightening, forgetful, stubborn, lame
*** Command
When you work with your animal companion on something it’s trained in…
    - …and you attack the same target, add its ferocity to your damage
    - …and you track, add its cunning to your roll
    - …and you take damage, add its armor to your armor
    - …and you discern realities, add its cunning to your roll
    - …and you parley, add its cunning to your roll
    - …and someone interferes with you, add its instinct to their roll
** Alignment
Choose an alignment:
*** Chaotic
Free someone from literal or figurative bonds.
*** Good
Endanger yourself to combat an unnatural threat.
*** Neutral
Help an animal or spirit of the wild.
** Gear
Your load is 11+Str. You start with dungeon rations (5 uses, 1 weight), leather
armor (1 armor, 1 weight), and a bundle of arrows (3 ammo, 1 weight). Choose
your armament:
    - Hunter’s bow (near, far, 1 weight) and short sword (close, 1 weight)
    - Hunter’s bow (near, far, 1 weight) and spear (reach, 1 weight)
Choose one:
    - Adventuring gear (1 weight) and dungeon rations (1 weight)
    - Adventuring gear (1 weight) and bundle of arrows (3 ammo, 1 weight)
** Bonds
Fill in the name of one of your companions in at least one:

I have guided _______________ before and they owe me for it.

_______________ is a friend of nature, so I will be their friend as well.

_______________ has no respect for nature, so I have no respect for them.

_______________ does not understand life in the wild, so I will teach them.
** Advanced Moves
You may take this move only if it is your first advancement.
*** Half-Elven
Somewhere in your lineage lies mixed blood and it begins to show its presence.
You gain the elf starting move if you took the human one at character creation
or vice versa.
When you gain a level from 2-5, choose from these moves.
*** Wild Empathy
You can speak with and understand animals.
*** Familiar Prey
When you spout lore about a monster you use WIS instead of INT.
*** Viper’s Strike
When you strike an enemy with two weapons at once, add an extra 1d4 damage for
your off-hand strike.
*** Camouflage
When you *keep still in natural surroundings*, enemies never spot you until you
make a movement.
*** Man’s Best Friend
When you *allow your animal companion to take a blow that was meant for you*,
the damage is negated and your animal companion’s ferocity becomes 0. If its
ferocity is already 0 you can’t use this ability. When you have a few hours of
rest with your animal companion its ferocity returns to normal.
*** Blot Out the Sun
When you volley you may spend extra ammo before rolling. For each point of ammo
spent you may choose an extra target. Roll once and apply damage to all targets.
*** Well-Trained
Choose another training for your animal companion.
*** God Amidst the Wastes
Dedicate yourself to a deity (name a new one or choose one that’s already been
established). You gain the commune and cast a spell cleric moves. When you
select this move, treat yourself as a cleric of level 1 for using spells. Every
time you gain a level thereafter, increase your effective cleric level by 1.
*** Follow Me
When you undertake a perilous journey you can take two roles. You make a
separate roll for each.
*** A Safe Place
When you *set the watch for the night*, everyone takes +1 to take watch.
When you gain a level from 6-10, choose from these moves or the level 2-5 moves.
*** Wild Speech
Replaces: Wild Empathy
You can speak with and understand any non-magical, non-planar creature.
*** Hunter’s Prey
Replaces: Familiar Prey
When you spout lore about a monster you use WIS instead of INT. On a 12+, in
addition to the normal effects, you get to ask the GM any one question about the
subject.
*** Viper’s Fangs
Replaces: Viper’s Strike
When you strike an enemy with two weapons at once, add an extra 1d8 damage for
your off-hand strike.
*** Smaug’s Belly
When you know your target’s weakest point your arrows have 2 piercing.
*** Strider
Replaces: Follow Me
When you undertake a perilous journey you can take two roles. Roll twice and use
the better result for both roles.
*** A Safer Place
Replaces: A Safe Place
When you set the watch for the night everyone takes +1 to take watch. After a
night in camp when you set the watch everyone takes +1 forward.
*** Observant
When you hunt and track, on a hit you may also ask one question about the
creature you are tracking from the discern realities list for free.
*** Special Trick
Choose a move from another class. So long as you are working with your animal
companion you have access to that move.
*** Unnatural Ally
Your animal companion is a monster, not an animal. Describe it. Give it +2
ferocity and +1 instinct, plus a new training.