* The world
Much of the adventuring life is spent in dusty, forgotten tombs or in places of
terror and life-threatening danger. It’s commonplace to awaken from a short and
fitful rest still deep in the belly of the world and surrounded by foes. When
the time comes to emerge from these places—whether laden with the spoils of
battle or beaten and bloody—an adventurer seeks out safety and solace.

These are the comforts of civilization: a warm bath, a meal of mead and bread,
the company of fellow men and elves and dwarves and halflings. Often thoughts of
returning to these places are all that keep an adventurer from giving up
altogether. All fight for gold and glory but who doesn’t ache for a place to
spend that gold and laugh around a fire, listening to tales of folly and
adventure?

This chapter covers the wider world—the grand and sweeping scope outside the
dungeon. The always marching movement of the GM’s fronts will shape the world
and, in turn, the world reflects the actions the players take to stop or
redirect them.
*** Steadings
We call all the assorted communities, holds, and so on where there’s a place to
stay and some modicum of civilization *steadings*, as in “homestead.” Steadings
are places with at least a handful of inhabitants, usually humans, and some
stable structures. They can be as big as a capital city or as small as few
ramshackle buildings.
** Creating the world
Remember how you started the first session? With action either underway or
impending? At some point the characters are going to need to retreat from that
action, either to heal their wounds or to celebrate and resupply.

When the players leave the site of their first adventure for the safety of
civilization it’s time to start drawing the campaign map. Take a large sheet of
paper (plain white if you like or hex-gridded if you want to get fancy), place
it where everyone can see, and make a mark for the site of the adventure. Use
pencil: this map will change. It can be to-scale and detailed or broad and
abstract, depending on your preference, just make it obvious. Keep the mark
small and somewhere around the center of the paper so you have space to grow.

Now add the nearest steading, a place the characters can go to rest and gather
supplies. Draw a mark for that place on the map and fill in the space between
with some terrain features. Try to keep it within a day or two of the site of
their first adventure—a short trip through a rocky pass or some heavy woods is
suitable, or a wider distance by road or across open ground.

When you have time (after the first session or during a snack break, for
example) use the rules to create the first steading. Consider adding marks for
other places that have been mentioned so far, either details from character
creation or the steading rules themselves.
** While You’re In Town…
When the players visit a steading there are some special moves they’ll be able
to make. These still follow the fictional flow of the game. When the players
arrive, ask them “What do you do?” The players’ actions will, more often than
not, trigger a move from this list. They cover respite, reinvigoration, and
resupply—opportunities for the players to gather their wits and spend their
treasure. Remember that a steading isn’t a break from reality. You’re still
making hard moves when necessary and thinking about how the players’ actions (or
inaction) advances your fronts. The impending doom is always there, whether the
players are fighting it in the dungeon or ignoring it while getting drunk in the
local tavern.

Don’t let a visit to a steading become a permanent respite. Remember, Dungeon
World is a scary, dangerous place. If the players choose to ignore that, they’re
giving you a golden opportunity to make a hard move. Fill the characters’ lives
with adventure whether they’re out seeking it or not. These moves exist so you
can make a visit to town an interesting event without spending a whole session
haggling over the cost of a new baldric.
** Elements of a Steading
A steading is any bit of civilization that offers some amount of safety to its
inhabitants. Villages, towns, keeps, and cities are the most common steadings.
Steadings are described by their tags. All steadings have tags indicating
prosperity, population, and defenses. Many will have tags to illustrate their
more unusual properties.

Steadings are differentiated based on size. The size indicates roughly how many
people the steading can support. The population tag tells you if the current
population is more than or less than this amount.

Villages are the smallest steadings. They’re usually out of the way, off the
main roads. If they’re lucky they can muster some defense but it’s often just
rabble with pitchforks and torches. A village stands near some easily
exploitable resource: rich soil, plentiful fish, an old forest, or a mine. There
might be a store of some sort but more likely its people trade among themselves.
Coin is scarce.

Towns have a hundred or so inhabitants. They’re the kind of place that springs
up around a mill, trading post, or inn and usually have fields, farms, and
livestock of some kind. They might have a standing militia of farmers strong
enough to wield a blade or shoot a bow. Towns have the basics for sale but
certainly no special goods. Usually they’ll focus on a local product or two and
do some trade with travelers.

A keep is a steading built specifically for defense—sometimes of a particularly
important location like a river delta or a rich gold mine. Keeps are found at
the frontier edges of civilization. Inhabitants are inured to the day-to-day
dangers of the road. They’re tough folks that number between a hundred and a
thousand, depending on the size of the keep and the place it defends. Keeps
won’t often have much beyond their own supplies, traded to them from nearby
villages, but will almost always have arms and armor and sometimes a rare
magical item found in the local wilds.

From bustling trade center to sprawling metropolis, the city represents the
largest sort of steading in Dungeon World. These are places where folk of many
races and kinds can be found. They often exist at the confluence of a handful of
trade routes or are built in a place of spiritual significance. They don’t often
generate their own raw materials for trade, relying on supplies from villages
nearby for food and resources, but will always have crafted goods and some
stranger things for sale to those willing to seek them.

Prosperity indicates what kinds of items are usually available. Population
indicates the number of inhabitants relative to the current size of the
steading. Defenses indicate the general scope of arms the steading has. Tags in
these categories can be adjusted. -Category means to change the steading to the
next lower tag for that category (so Moderate would become Poor with
-Prosperity). +Category means to change the steading to the next higher tag (so
Shrinking becomes Steady with +Population). Tags in those categories can also be
compared like numbers. Treat the lowest tag in that category as 1 and each
successive tag as the next number (so Dirt is 1, Poor is 2, etc.).

Tags will change over the course of play. Creating a steading provides a
snapshot of what that place looks like /right now/. As the players spend time in
it and your fronts progress the world will change and your steadings with it.
*** Adding Steadings
You add your first steading when you create the campaign map—it’s the place the
players go to rest and recover. When you first draw it on the map all you need
is a name and a location.

When you have the time you’ll use the rules below to create the steading. The
first steading is usually a village, but you can use a town if the first
adventure was closely tied to humans (for example, if the players fought a human
cult). Create it using the rules below.

Once you’ve created the first steading you can add other places referenced in
its tags (the oath, trade, and enmity tags in particular) or anywhere else
that’s been referred to in play. Don’t add too much in the first session, leave
blanks and places to explore.

As play progresses the characters will discover new locales and places of
interest either directly, by stumbling upon them in the wild, or indirectly, by
hearing about them in rumors or tales. Add new steadings, dungeons, and other
locations to the map as they’re discovered or heard about. Villages are often
near a useful resource. Towns are often found at the point where several
villages meet to trade. Keeps watch over important locations. Cities rely on the
trade and support of smaller steads. Dungeons can be found anywhere and in many
forms.

Whenever you add a new steading use the rules to decide its tags. Consider
adding a distinctive feature somewhere nearby. Maybe a forest, some old standing
stones, an abandoned castle, or whatever else catches your fancy or makes sense.
A map of only steadings and ruins with nothing in between is dull; don’t neglect
the other features of the world.
*** Steading Tags
**** Prosperity

/Dirt/: Nothing for sale, nobody has more than they need (and they’re lucky if
they have that). Unskilled labor is cheap.

/Poor/: Only the bare necessities for sale. Weapons are scarce unless the
steading is heavily defended or militant. Unskilled labor is readily available.

/Moderate/: Most mundane items are available. Some types of skilled laborers.

/Wealthy/: Any mundane item can be found for sale. Most kinds of skilled
laborers are available, but demand is high for their time.

/Rich/: Mundane items and more, if you know where to find them. Specialist labor
available, but at high prices.
**** Population

/Exodus/: The steading has lost its population and is on the verge of collapse.

/Shrinking/: The population is less than it once was. Buildings stand empty.

/Steady/: The population is in line with the current size of the steading. Some
slow growth.

/Growing/: More people than there are buildings.

/Booming/: Resources are stretched thin trying to keep up with the number of
people.
**** Defenses

/None/: Clubs, torches, farming tools.

/Militia/: There are able-bodied men and women with worn weapons ready to be
called, but no standing force.

/Watch/: There are a few watchers posted who look out for trouble and settle
small problems, but their main role is to summon the militia.

/Guard/: There are armed defenders at all times with a total pool of less than
100 (or equivalent). There is always at least one armed patrol about the
steading.

/Garrison/: There are armed defenders at all times with a total pool of 100–300
(or equivalent). There are multiple armed patrols at all times.

/Battalion/: As many as 1,000 armed defenders (or equivalent). The steading has
manned maintained defenses as well.

/Legion/: The steading is defended by thousands of armed soldiers (or
equivalent). The steading’s defenses are intimidating.
**** Other Tags

/Safe/: Outside trouble doesn’t come here until the players bring it. Idyllic
and often hidden, if the steading would lose or degrade another beneficial tag
get rid of safe instead.

/Religion/: The listed deity is revered here.

/Exotic/: There are goods and services available here that aren’t available
anywhere else nearby. List them.

/Resource/: The steading has easy access to the listed resource (e.g., a spice,
a type of ore, fish, grapes). That resource is significantly cheaper.

/Need/: The steading has an acute or ongoing need for the listed resource. That
resource sells for considerably more.

/Oath/: The steading has sworn oaths to the listed steadings. These oaths are
generally of fealty or support, but may be more specific.

/Trade/: The steading regularly trades with the listed steadings.

/Market/: Everyone comes here to trade. On any given day the available items may
be far beyond their prosperity. +1 to supply.

/Enmity/: The steading holds a grudge against the listed steadings.

/History/: Something important once happened here, choose one and detail or make
up your own: battle, miracle, myth, romance, tragedy.

/Arcane/: Someone in town can cast arcane spells for a price. This tends to draw
more arcane casters, +1 to recruit when you put out word you’re looking for an
adept.

/Divine/: There is a major religious presence, maybe a cathedral or monastery.
They can heal and maybe even raise the dead for a donation or resolution of a
quest. Take +1 to recruit priests here.

/Guild/: The listed type of guild has a major presence (and usually a fair
amount of influence). If the guild is closely associated with a type of
hireling, +1 to recruit that type of hireling.

/Personage/: There’s a notable person who makes their home here. Give them a
name and a short note on why they’re notable.

/Dwarven/: The steading is significantly or entirely dwarves. Dwarven goods are
more common and less expensive than they typically are.

/Elven/: The steading is significantly or entirely elves. Elven goods are more
common and less expensive than they typically are.

/Craft/: The steading is known for excellence in the listed craft. Items of
their chosen craft are more readily available here or of higher quality than
found elsewhere.

/Lawless/: Crime is rampant; authority is weak.

/Blight/: The steading has a recurring problem, usually a type of monster.

/Power/: The steading holds sway of some type. Typically political, divine, or
arcane.
*** Steading Names
Graybark, Nook’s Crossing, Tanner’s Ford, Goldenfield, Barrowbridge, Rum River,
Brindenburg, Shambles, Covaner, Enfield, Crystal Falls, Castle Daunting, Nulty’s
Harbor, Castonshire, Cornwood, Irongate, Mayhill, Pigton, Crosses, Battlemoore,
Torsea, Curland, Snowcalm, Seawall, Varlosh, Terminum, Avonia, Bucksburg,
Settledown, Goblinjaw, Hammerford, Pit, The Gray Fast, Ennet Bend, Harrison’s
Hold, Fortress Andwynne, Blackstone
** Making a Village
By default a village is Poor, Steady, Militia, Resource (your choice) and has an
Oath to another steading of your choice. If the village is part of a kingdom or
empire choose one:
    - The village is somewhere naturally defended: Safe, -Defenses
    - The village has abundant resources that sustain it: +Prosperity, Resource
      (your choice), Enmity (your choice)
    - The village is under the protection of another steading: Oath (that
      steading), +Defenses
    - The village is on a major road: Trade (your choice), +Prosperity
    - The village is built around a wizard’s tower: Personage (the wizard),
      Blight (arcane creatures)
    - The village was built on the site of religious significance: Divine,
      History (your choice)
Choose one problem:
    - The village is in arid or uncultivable land: Need (Food)
    - The village is dedicated to a deity: Religious (that deity), Enmity (a
      settlement of another deity)
    - The village has recently fought a battle: -Population, -Prosperity if they
      fought to the end, -Defenses if they lost.
    - The village has a monster problem: Blight (that monster), Need
      (adventurers)
    - The village has absorbed another village: +Population, Lawless
    - The village is remote or unwelcoming: -Prosperity, Dwarven or Elven
** Making a Town
By default a town is Moderate, Steady, Watch, and Trade (two of your choice). If
the town is listed as Trade by another steading choose one:
    - The town is booming: Booming, Lawless
    - The town stands on a crossroads: Market, +Prosperity
    - The town is defended by another steading: Oath (that steading), +Defenses
    - The town is built around a church: Power (Divine)
    - The town is built around a craft: Craft (your choice), Resource (something
      required for that craft)
    - The town is built around a military post: +Defenses
Choose one problem:
    - The town has grown too big for an important supply (like grain, wood, or
      stone): Need (that resource), Trade (a village or town with that resource)
    - The town offers defense to others: Oath (your choice), -Defenses
    - The town is notorious for an outlaw who is rumored to live there:
      Personage (the outlaw), Enmity (where the crimes were committed)
    - The town has cornered the market on a good or service: Exotic (that good
      or service), Enmity (a settlement with ambition)
    - The town has a disease: -Population
    - The town is a popular meeting place: +Population, Lawless
** Making a Keep
By default a keep is Poor, Shrinking, Guard, Need (Supplies), Trade (someplace
with supplies), Oath (your choice). If the keep is owed fealty by at least one
settlement choose one:
    - The keep belongs to a noble family: +Prosperity, Power (Political)
    - The keep is run by a skilled commander: Personage (the commander),
      +Defenses
    - The keep stands watch over a trade road: +Prosperity, Guild (trade)
    - The keep is used to train special troops: Arcane, -Population
    - The keep is surrounded by fertile land: remove Need (Supplies)
    - The keep stands on a border: +Defenses, Enmity (steading on the other side
      of the border)
Choose one problem
    - The keep is built on a naturally defensible position: Safe, -Population
    - The keep was a conquest from another power: Enmity (steadings of that
      power)
    - The keep is a safe haven for brigands: Lawless
    - The keep was built to defend from a specific threat: Blight (that threat)
    - The keep has seen horrible bloody war: History (Battle), Blight (Restless
      Spirits)
    - The keep is given the worst of the worst: Need (Skilled Recruits)
** Making a City
By default a city is Moderate, Steady, Guard, Market, and Guild (one of your
choice). It also has Oaths with at least two other steadings, usually a town and
a keep. If the city has trade with at least one steading and fealty from at
least one steading choose one:
    - The city has permanent defenses, like walls: +Defenses, Oath (your choice)
    - The city is ruled by a single individual: Personage (the ruler), Power
      (Political)
    - The city is diverse: Dwarven or Elven or both
    - The city is a trade hub: Trade (every steading nearby), +Prosperity
    - The city is ancient, built on top of its own ruins: History (your choice),
      Divine
    - The city is a center of learning: Arcane, Craft (your choice), Power
      (Arcane)
Choose one problem:
    - The city has outgrown its resources: +Population, Need (food)
    - The city has designs on nearby territory: Enmity (nearby steadings),
      +Defenses
    - The city is ruled by a theocracy: -Defenses, Power (Divine)
    - The city is ruled by the people: -Defenses, +Population
    - The city has supernatural defenses: +Defenses, Blight (related
      supernatural creatures)
    - The city lies on a place of power: Arcane, Personage (whoever watches the
      place of power), Blight (arcane creatures)
** Fronts on the Campaign Map
Your steadings are not the only thing on the campaign map. In addition to
steadings and the areas around them your fronts will appear on the map, albeit
indirectly.

Fronts are organizational tools, not something the characters think of, so don’t
put them on the map directly. The orcs of Olg’gothal may be a front but don’t
just draw them on the map. Instead for each front add some feature to the map
that indicates the front’s presence. You can label it if you like, but use the
name that the characters would use, not the name you gave the front.

For example, the orcs of Olg’gothal could be marked on the map with a burning
village they left behind, fires in the distance at night, or a stream of
refugees. Lord Xothal, a lich, might be marked by the tower where dead plants
take root and grow.

As your fronts change, change the map. If the players cleanse Xothal’s tower
redraw it. If the orcs are driven off erase the crowds of refugees.
** Updating the Campaign Map
The campaign map is updated between sessions or whenever the players spend
significant downtime in a safe place. Updates are both prescriptive and
descriptive: if an event transpires that, say, gathers a larger fighting force
to a village, update the tags to reflect that. Likewise if a change in tags mean
that a village has a bigger fighting force you’ll likely see more armored men in
the street.

Between each session check each of the conditions below. Go down the list and
check each condition for all steadings before moving to the next. If a condition
applies, apply its effects.
**** Growth
When *a village or town is booming and its prosperity is above moderate* you may
reduce prosperity and defenses to move to the next largest type. New towns
immediately gain market and new cities immediately gain guild (your choice).
**** Collapse
When *a steading’s population is in exodus and its prosperity is poor or less*
it shrinks. A city becomes a town with a steady population and +prosperity. A
keep becomes a town with +defenses and a steady population. A town becomes a
village with steady population and +prosperity. A village becomes a ghost town.
**** Want
When *a steading has a need that is not fulfilled* (through trade, capture, or
otherwise) that steading is in want. It gets either -prosperity, -population, or
loses a tag based on that resource like craft or trade, your choice.
**** Trade
When *trade is blocked* because the source of that trade is gone, the route is
endangered, or political reasons, the steading has a choice: gain need (a traded
good) or take -prosperity.
**** Capture
When *control of a resource changes* remove that resource from the tags of the
previous owner and add it to the tags of the new owner (if applicable). If the
previous owner has a craft or trade based on that resource they now have need
(that resource). If the new owner had a need for that resource, remove it.
**** Profit
When *a steading has more trade than its current prosperity* it gets
+prosperity.
**** Surplus
When *a steading has a resource that another steading needs* unless enmity or
other diplomatic reasons prevent it they set up trade. The steading with the
resource gets +prosperity and their choice of oaths, +population, or +defenses;
the steading with the need erases that need and adds trade.
**** Aid
When *a steading has oaths to a steading under attack* that steading may take
-defenses to give the steading under attack +defenses.
**** Embattled
When *a steading is surrounded by enemy forces* it suffers losses. If it fights
back with force it gets -defenses. If its new defenses are watch or less it also
gets -prosperity. If it instead tries to wait out the attack it gets
-population. If its new population is shrinking or less it loses a tag of your
choice. If the steading’s defenses outclass the attacker’s (your call if it’s
not clear, or make it part of an adventure front) the steading is no longer
surrounded.
**** Opportunity
When *a steading has enmity against a weaker steading* they may attack. Subtract
the distance (in rations) between the steadings from the steading with enmity’s
defenses. If the result is greater than the other steading’s defenses +defense
for each step of size difference (village to town, town to keep, keep to city)
they definitely attack. Otherwise it’s your call: has anything happened recently
to stoke their anger? The forces of the attacker embattle the defender, while
they maintain the attack they’re -defenses.
**** Clash
When *two steadings both attack each other* their forces meet somewhere between
them and fight. If they’re evenly matched they both get -defenses and their
troops return home. If one has the advantage they take -defenses while the other
takes -2 defenses.
*** Other Updates
The conditions above detail the most basic of interactions between steadings, of
course the presence of your fronts and the players mean things can get far more
complex. Since tags are descriptive, add them as needed to reflect the players’
actions and your fronts’ effects on the world.