
* The Thief
You’ve heard them, sitting around the campfire. Bragging about this battle or
that. About how their gods are smiling on your merry band. You count your coins
and smile to yourself—this is the thrill above all. You alone know the secret of
Dungeon World—filthy filthy lucre.

Sure, they give you lip for all the times you’ve snuck off alone but without
you, who among them wouldn’t have been dissected by a flying guillotine or
poisoned straight to death by some ancient needle trap? So, let them complain.
When you’re done with all this delving you’ll toast their hero’s graves.

From your castle. Full of gold. You rogue.
** Names
/Halfling/: Felix, Rook, Mouse, Sketch, Trixie, Robin, Omar, Brynn, Bug
/Human/: Sparrow, Shank, Jack, Marlow, Dodge, Rat, Pox, Humble, Farley
** Look
Choose one for each:
Shifty Eyes or Criminal Eyes
Hooded Head, Messy Hair, or Cropped Hair
Dark Clothes, Fancy Clothes, or Common Clothes
Lithe Body, Knobby Body, or Flabby Body
** Stats
Your maximum HP is 6+Constitution.
Your base damage is d8.
** Starting Moves
Choose a race and gain the corresponding move:
*** Halfling
When you attack with a ranged weapon, deal +2 damage.
*** Human
You are a professional. When you spout lore or discern realities about criminal
activities, take +1.
You start with these moves:
*** Trap Expert
When you *spend a moment to survey a dangerous area*, roll+DEX. ✴On a 10+, hold
3. ✴On a 7–9, hold 1. Spend your hold as you walk through the area to ask these
questions:
    - Is there a trap here and if so, what activates it?
    - What does the trap do when activated?
    - What else is hidden here?
*** Tricks of the Trade
When you *pick locks or pockets or disable traps*, roll+DEX. ✴On a 10+, you do
it, no problem. ✴On a 7–9, you still do it, but the GM will offer you two
options between suspicion, danger, or cost.
*** Backstab
When you *attack a surprised or defenseless enemy with a melee weapon*, you can
choose to deal your damage or roll+DEX. ✴On a 10+ choose two. ✴On a 7–9 choose
one.
    - You don’t get into melee with them
    - You deal your damage+1d6
    - You create an advantage, +1 forward to you or an ally acting on it
    - Reduce their armor by 1 until they repair it
*** Flexible Morals
When someone tries to detect your alignment you can tell them any alignment you
like.
*** Poisoner
You’ve mastered the care and use of a poison. Choose a poison from the list
below; that poison is no longer dangerous for you to use. You also start with
three uses of the poison you choose. Whenever you have time to gather materials
and a safe place to brew you can make three uses of the poison you choose for
free. Note that some poisons are applied, meaning you have to carefully apply it
to the target or something they eat or drink. Touch poisons just need to touch
the target, they can even be used on the blade of a weapon.
    - Oil of Tagit (applied): The target falls into a light sleep
    - Bloodweed (touch): The target deals -1d4 damage ongoing until cured
    - Goldenroot (applied): The target treats the next creature they see as a
      trusted ally, until proved otherwise
    - Serpent’s Tears (touch): Anyone dealing damage to the target rolls twice
      and takes the better result.
** Alignment
Choose an alignment:
*** Chaotic
Leap into danger without a plan.
*** Neutral
Avoid detection or infiltrate a location.
*** Evil
Shift danger or blame from yourself to someone else.
** Gear
Your load is 9+Str. You start with dungeon rations (5 uses, 1 weight), leather
armor (1 armor, 1 weight), 3 uses of your chosen poison, and 10 coins. Choose
your arms:
    - Dagger (hand, 1 weight) and short sword (close, 1 weight)
    - Rapier (close, precise, 1 weight)
Choose a ranged weapon:
    - 3 throwing daggers (thrown, near, 0 weight)
    - Ragged Bow (near, 2 weight) and bundle of arrows (3 ammo, 1 weight)
Choose one:
    - Adventuring gear (1 weight)
    - Healing potion (0 weight)
** Bonds
Fill in the name of one of your companions in at least one:

I stole something from _______________.

_______________ has my back when things go wrong.

_______________ knows incriminating details about me.

_______________ and I have a con running.
** Advanced Moves
When you gain a level from 2–5, choose from these moves.
*** Cheap Shot
When using a precise or hand weapon, your backstab deals an extra +1d6 damage.
*** Cautious
When you use trap expert you always get +1 hold, even on a 6-.
*** Wealth and Taste
When you *make a show of flashing around your most valuable possession*, choose
someone present. They will do anything they can to obtain your item or one like
it.
*** Shoot First
You’re never caught by surprise. When an enemy would get the drop on you, you
get to act first instead.
*** Poison Master
After you’ve used a poison once it’s no longer dangerous for you to use.
*** Envenom
You can apply even complex poisons with a pinprick. When you apply a poison
that’s not dangerous for you to use to your weapon it’s touch instead of
applied.
*** Brewer
When you have time to gather materials and a safe place to brew you can create
three doses of any one poison you’ve used before.
*** Underdog
When you’re outnumbered, you have +1 armor.
*** Connections
When you put out word to the criminal underbelly about something you want or
need, roll+CHA. ✴On a 10+, someone has it, just for you. ✴On a 7–9, you’ll have
to settle for something close or it comes with strings attached, your call.
When you gain a level from 6–10, choose from these moves or the level 2–5 moves.
*** Dirty Fighter
Replaces: Cheap Shot
When using a precise or hand weapon, your backstab deals an extra +1d8 damage
and all other attacks deal +1d4 damage.
*** Extremely Cautious
Replaces: Cautious
When you use trap expert you always get +1 hold, even on a 6-. On a 12+ you get
3 hold and the next time you come near a trap the GM will immediately tell you
what it does, what triggers it, who set it, and how you can use it to your
advantage.
*** Alchemist
Replaces: Brewer
When you have you have time to gather materials and a safe place to brew you can
create three doses of any poison you’ve used before. Alternately you can
describe the effects of a poison you’d like to create. The GM will tell you that
you can create it, but with one or more caveats:
    - It will only work under specific circumstances
    - The best you can manage is a weaker version
    - It’ll take a while to take effect
    - It’ll have obvious side effects
*** Serious Underdog
Replaces: Underdog
You have +1 armor. When you’re outnumbered, you have +2 armor instead.
*** Evasion
When you defy danger on a 12+, you transcend the danger. You not only do what
you set out to, but the GM will offer you a better outcome, true beauty, or a
moment of grace.
*** Strong Arm, True Aim
You can throw any melee weapon, using it to volley. A thrown melee weapon is
gone; you can never choose to reduce ammo on a 7–9.
*** Escape Route
When you’re in too deep and need a way out, name your escape route and roll+DEX.
✴On a 10+ you’re gone. ✴On a 7–9 you can stay or go, but if you go it costs you:
leave something behind or take something with you, the GM will tell you what.
*** Disguise
When you have time and materials you can create a disguise that will fool anyone
into thinking you’re another creature of about the same size and shape. Your
actions can give you away but your appearance won’t.
*** Heist
When you take time to make a plan to steal something, name the thing you want to
steal and ask the GM these questions. When acting on the answers you and your
allies take +1 forward.
    - Who will notice it’s missing?
    - What’s its most powerful defense?
    - Who will come after it?
    - Who else wants it?