
* The Wizard
Dungeon World has rules. Not the laws of men or the rule of some petty tyrant.
Bigger, better rules. You drop something—it falls. You can’t make something out
of nothing. The dead stay dead, right?

Oh, the things we tell ourselves to feel better about the long, dark nights.

You’ve spent so very long poring over those tomes of yours. The experiments that
nearly drove you mad and all the botched summonings that endangered your very
soul. For what? For power. What else is there? Not just the power of King or
Country but the power to boil a man’s blood in his veins. To call on the thunder
of the sky and the churn of the roiling earth. To shrug off the rules the world
holds so dear.

Let them cast their sidelong glances. Let them call you “warlock” or
“diabolist.” Who among them can hurl fireballs from their eyes?

Yeah. We didn’t think so.
** Names
/Elf/: Galadiir, Fenfaril, Lilliastre, Phirosalle, Enkirash, Halwyr 
/Human/: Avon, Morgan, Rath, Ysolde, Ovid, Vitus, Aldara, Xeno, Uri
** Look
Choose one for each:
Haunted Eyes, Sharp Eyes, or Crazy Eyes
Styled Hair, Wild Hair, or Pointed Hat
Worn Robes, Stylish Robes, or Strange Robes
Pudgy Body, Creepy Body, or Thin Body
** Stats
Your maximum HP is 4+Constitution.
Your base damage is d4.
** Starting Moves
Choose a race and gain the corresponding move:
*** Elf
Magic is as natural as breath to you. Detect Magic is a cantrip for you.
*** Human
Choose one cleric spell. You can cast it as if it was a wizard spell.
You start with these moves:
*** Spellbook
You have mastered several spells and inscribed them in your spellbook. You start
out with three first level spells in your spellbook as well as the cantrips.
Whenever you gain a level, you add a new spell of your level or lower to your
spellbook. You spellbook is 1 weight.
*** Prepare Spells
When you *spend uninterrupted time (an hour or so) in quiet contemplation of
your spellbook*, you:
    - Lose any spells you already have prepared
    - Prepare new spells of your choice from your spellbook whose total levels
      don’t exceed your own level+1.
    - Prepare your cantrips which never count against your limit.
*** Cast a Spell (Int)
When you *release a spell you’ve prepared*, roll+Int. ✴On a 10+, the spell is
successfully cast and you do not forget the spell—you may cast it again later.
✴On a 7-9, the spell is cast, but choose one:
    - You draw unwelcome attention or put yourself in a spot. The GM will tell
      you how.
    - The spell disturbs the fabric of reality as it is cast—take -1 ongoing to
      cast a spell until the next time you Prepare Spells.
    - After it is cast, the spell is forgotten. You cannot cast the spell again
      until you prepare spells.
Note that maintaining spells with ongoing effects will sometimes cause a penalty
to your roll to cast a spell.
*** Spell Defense
You may end any ongoing spell immediately and use the energy of its dissipation
to deflect an oncoming attack. The spell ends and you subtract its level from
the damage done to you.
*** Ritual
When you *draw on a place of power to create a magical effect*, tell the GM what
you’re trying to achieve. Ritual effects are always possible, but the GM will
give you one to four of the following conditions:
    - It’s going to take days/weeks/months
    - First you must ____
    - You’ll need help from ____
    - It will require a lot of money
    - The best you can do is a lesser version, unreliable and limited
    - You and your allies will risk danger from ____
    - You’ll have to disenchant ____ to do it
** Alignment
Choose an alignment:
*** Good
Use magic to directly aid another.
*** Neutral
Discover something about a magical mystery.
*** Evil
Use magic to cause terror and fear.
** Gear
Your load is 7+Str. You start with your spellbook (1 weight) and dungeon rations
(5 uses, 1 weight). Choose your defenses:
    - Leather armor (1 armor, 1 weight)
    - Bag of books (5 uses, 2 weight) and 3 healing potions
Choose your weapon:
    - Dagger (hand, 1 weight)
    - Staff (close, two-handed, 1 weight)
Choose one:
    - Healing potion (0 weight)
    - 3 antitoxins (0 weight)
** Bonds
Fill in the name of one of your companions in at least one:

_______________ will play an important role in the events to come. I have
foreseen it!

_______________ is keeping an important secret from me.

_______________ is woefully misinformed about the world; I will teach them all
that I can.
** Advanced Moves
When you gain a level from 2-5, choose from these moves. You also add a new
spell to your spellbook at each level.
*** Prodigy
Choose a spell. You prepare that spell as if it were one level lower.
*** Empowered Magic
When you cast a spell, on a 10+ you have the option of choosing from the 7-9
list. If you do, you may choose one of these as well:
    - The spell’s effects are maximized
    - The spell’s targets are doubled
*** Fount of Knowledge
When you *spout lore about something no one else has any clue about*, take +1.
*** Know-It-All
When *another player’s character comes to you for advice and you tell them what
you think is best*, they get +1 forward when following your advice and you mark
experience if they do.
*** Expanded Spellbook
Add a new spell from the spell list of any class to your spellbook.
*** Enchanter
When you have time and safety with a magic item you may ask the GM what it does,
the GM will answer you truthfully.
*** Logical
When you *use strict deduction to analyze your surroundings*, you can discern
realities with INT instead of WIS.
*** Arcane Ward
As long as you have at least one prepared spell of first level or higher, you
have +2 armor.
*** Counterspell
When you *attempt to counter an arcane spell that will otherwise affect you*,
stake one of your prepared spells on the defense and roll+Int. ✴On a 10+, the
spell is countered and has no effect on you. ✴On a 7-9, the spell is countered
and you forget the spell you staked. Your counterspell protects only you; if the
countered spell has other targets they get its effects.
*** Quick Study
When you *see the effects of an arcane spell*, ask the GM the name of the spell
and its effects. You take +1 when acting on the answers.
When you gain a level from 6-10, choose from these moves or the level 2-5 moves.
*** Master
Requires: Prodigy
Choose one spell in addition to the one you picked for prodigy. You prepare that
spell as if it were one level lower.
*** Greater Empowered Magic
Replaces: Empowered Magic
When you cast a spell, on a 10-11 you have the option of choosing from the 7-9
list. If you do, you may choose one of these effects as well. On a 12+ you get
to choose one of these effects for free:
    - The spell’s effects are doubled
    - The spell’s targets are doubled
*** Enchanter’s Soul
Requires: Enchanter
When you have time and safety with a magic item in a place of power you can
empower that item so that the next time you use it its effects are amplified,
the GM will tell you exactly how.
*** Highly Logical
Replaces: Logical
When you *use strict deduction to analyze your surroundings*, you can discern
realities with Int instead of Wis. On a 12+ you get to ask the GM any three
questions, not limited by the list.
*** Arcane Armor
Replaces: Arcane Ward
As long as you have at least one prepared spell of first level or higher, you
have +4 armor.
*** Protective Counter
Requires: Counterspell
When an ally within sight of you is affected by an arcane spell, you can counter
it as if it affected you. If the spell affects multiple allies you must counter
for each ally separately.
*** Ethereal Tether
When you have time with a willing or helpless subject you can craft an ethereal
tether with them. You perceive what they perceive and can discern realities
about someone tethered to you or their surroundings no matter the distance.
Someone willingly tethered to you can communicate with you over the tether as if
you were in the room with them.
*** Mystical Puppet Strings
When you *use magic to control a person’s actions* they have no memory of what
you had them do and bear you no ill will.
*** Spell Augmentation
When you *deal damage to a creature* you can shunt a spell’s energy into
them—end one of your ongoing spells and add the spell’s level to the damage
dealt.
*** Self-Powered
When you have time, arcane materials, and a safe space, you can create your own
place of power. Describe to the GM what kind of power it is and how you’re
binding it to this place, the GM will tell you one kind of creature that will
have an interest in your workings.