* Character Creation
Making Dungeon World characters is quick and easy. You should all create your
first characters together at the beginning of your first session. Character
creation is, just like play, a kind of conversation—everyone should be there for
it.

You may need to make another character during play, if yours gets killed for
example. If so, no worries, the character creation process helps you make a new
character that fits into the group in just a few minutes. All characters, even
replacement characters, start at first level.

Most everything you need to create a character you’ll find on the character
sheets. These steps will walk you through filling out a character sheet.
** 1. Choose a Class
Look over the character classes and choose one that interests you. To start with
everyone chooses a different class; there aren’t two wizards. If two people want
the same class, talk it over like adults and compromise.
I sit down with Paul and Shannon to play a game run by John. I’ve got some cool
ideas for a wizard, so I mention that would be my first choice. No one else was
thinking of playing one, so I take the wizard character sheet.
** 2. Choose a Race
Some classes have race options. Choose one. Your race gives you a special move.
I like the idea of being flexible—having more spells available is always good,
right? I choose Human, since it’ll allow me to pick a cleric spell and cast it
like it was a wizard one. That’ll leave Shannon’s cleric free to keep the
healing magic flowing.
** 3. Choose a Name
Choose your character’s name from the list.
Avon sounds good.
** 4. Choose Look
Your look is your physical appearance. Choose one item from each list.
Haunted eyes sound good since every wizard has seen some things no mortal was
meant to. No good wizard has time for hair styling so wild hair it is. My robes
are strange, and I mention to everyone that I think maybe they came from Beyond
as part of a summoning ritual. No time to eat with all that studying and
research: thin body.
** 5. Choose Stats
Assign these scores to your stats: 16, 15, 13, 12, 9, 8. Start by looking over
the basic moves and the starting moves for your class. Pick out the move that
interests you the most: something you’ll be doing a lot, or something that you
excel at. Put a 16 in the stat for that move. Look over the list again and pick
out the next most important move to your character, maybe something that
supports your first choice. Put your 15 in the stat for that move. Repeat this
process for your remaining scores: 13, 12, 9, 8.
It looks like I need Intelligence to cast spells, which are my thing, so my 16
goes there. The defy danger option for Dexterity looks like something I might be
doing to dive out of the way of a spell, so that gets my 15. A 13 Wisdom will
help me notice important details (and maybe keep my sanity, based on the defy
danger move). Charisma might be useful in dealing with summoned creatures so
I’ll put my 12 there. Living is always nice, so I put my 9 in Constitution for
some extra HP. Strength gets the 8.
** 6. Figure Out Modifiers
Next you need to figure out the modifiers for your stats. The modifiers are what
you use when a move says +DEX or +CHA. If you’re using the standard character
sheets the modifiers are already listed with each score.
ScoreModifier1–3-34–5-26–8-19–12013–15+116–17+218+3
** 7. Set Maximum HP
Your maximum HP is equal to your class’s base HP+Constitution score. You start
with your maximum HP.
Base 4 plus 9 con gives me a whopping 13 HP.
** 8. Choose Starting Moves
The front side of each character sheet lists the starting moves. Some classes,
like the fighter, have choices to make as part of one of their moves. Make these
choices now. The wizard will need to choose spells for their spellbook. Both the
cleric and the wizard will need to choose which spells they have prepared to
start with.
A /Summoning/ spell is an easy choice, so I take Contact Spirits. Magic Missile
will allow me to deal more damage than the pitiful d4 for the wizard class, so
that’s in too. I choose Alarm for my last spell, since I can think of some
interesting uses for it.
** 9. Choose Alignment
Your alignment is a few words that describe your character’s moral outlook. Each
class may only start with certain alignments. Choose your alignment—in play,
it’ll give your character certain actions that can earn you additional XP
The Neutral option for wizards says I earn extra XP when I discover a magical
mystery. Avon is all about discovering mystery—I’ll go with Neutral.
** 10. Choose Gear
Each class has choices to make for starting gear. Keep your load in mind—it
limits how much you can easily carry. Make sure to total up your armor and note
it on your character sheet.
I’m worried about my HP, so I take armor over books. A dagger sounds about right
for rituals; I choose that over a staff. It’s a toss-up between the healing
potion and the antitoxin, but healing wins out. I also end up with some rations.
** 11. Introduce Your Character
Now that you know who your character is, it’s time to introduce them to everyone
else. Wait until everyone’s finished choosing their name. Then go around the
table; when it’s your turn, share your look, class and anything else pertinent
about your character. You can share your alignment now or keep it a secret if
you prefer.

This is also the time for the GM to ask questions. The GM’s questions should
help establish the relationships between characters (“What do you think about
that?”) and draw the group into the adventure (“Does that mean you’ve met
Grundloch before?”). The GM should listen to everything in the description and
ask about anything that stands out. Establish where they’re from, who they are,
how they came together, or anything else that seems relevant or interesting.
“This is Avon, mighty wizard! He’s a human with haunted eyes, wild hair, strange
robes, and a thin body. Like I mentioned before his robes are strange because
they’re literally not of this world: they came to him as part of a summoning
ritual.”
** 12. Choose Bonds
Once everyone has described their characters you can choose your bonds. You must
fill in one bond but it’s in your best interest to fill in more. For each blank
fill in the name of one character. You can use the same character for more than
one statement.

Take some time to discuss the bonds and let the GM ask questions about them as
they come up. You’ll want to go back and forth and make sure everyone is happy
and comfortable with how the bonds have come out. Leave space to discover what
each one might mean in play, too: don’t pre-determine everything at the start.
Once everyone’s filled in their bonds read them out to the group. When a move
has you roll+Bond you’ll count the number of bonds you have with the character
in question and add that to the roll.
With everyone introduced I choose which character to list in each bond, I have
Paul’s fighter Gregor and Shannon’s cleric Brinton to choose from. The bond
about prophecy sounds fun, so I choose Gregor for it and end up with “Gregor
will play an important role in the events to come. I have foreseen it!” It seems
like the wizard who contacts Things From Beyond and the cleric might not see eye
to eye, so I add Shannon’s character and get “Brinton is woefully misinformed
about the world; I will teach them all that I can.” I leave my last bond blank;
I’ll deal with it later. Once everyone is done I read my bonds aloud and we all
discuss what this means about why we’re together and where we’re going.
** 13. Get Ready to Play
Take a little break: grab a drink, stretch your legs and let the GM brainstorm
for a little bit about what they’ve learned about your characters. Once you’re
all ready, grab your dice and your sheet and get ready to take on the dungeon.

Once you’re ready the GM will get things started as described in the First
Session chapter.