* The Cleric
The lands of Dungeon World are a gods-forsaken mess. They’re lousy with the
walking dead, beasts of all sorts, and the vast unnatural spaces between safe
and temple-blessed civilizations. It is a godless world out there. That’s why it
needs you.

Bringing the glory of your god to the heathens isn’t just in your nature—it’s
your calling. It falls to you to proselytize with sword and mace and spell. To
cleave deep into the witless heart of the wilds and plant the seed of divinity
there. Some say that it is best to keep god close to your heart. You know that’s
rubbish. God lives at the edge of a blade.

Show the world who is lord.
** Names
/Dwarf/: Durga, Aelfar, Gerda, Rurgosh, Bjorn, Drummond, Helga, Siggrun, Freya
/Human/: Wesley, Brinton, Jon, Sara, Hawthorn, Elise, Clarke, Lenore, Piotr,
Dahlia, Carmine
** Look
Choose one for each:
Kind Eyes, Sharp Eyes, or Sad Eyes
Tonsure, Strange Hair, or Bald
Flowing Robes, Habit, or Common Garb
Thin Body, Knobby Body, or Flabby Body
** Stats
Your maximum HP is 8+Constitution.
Your base damage is d6.
** Starting Moves
Choose a race and gain the corresponding move:
*** Dwarf
You are one with stone. When you commune you are also granted a special version
of Words of the Unspeaking as a rote which only works on stone.
*** Human
Your faith is diverse. Choose one wizard spell. You can cast and be granted that
spell as if it was a cleric spell.
You start with these moves:
*** Deity
You serve and worship some deity or power which grants you spells. Give your god
a name (maybe Helferth, Sucellus, Zorica or Krugon the Bleak) and choose your
deity’s domain:
    - Healing and Restoration
    - Bloody Conquest
    - Civilization
    - Knowledge and Hidden Things
    - The Downtrodden and Forgotten
    - What Lies Beneath
Choose one precept of your religion:
    - Your religion preaches the sanctity of suffering, add Petition: Suffering
    - Your religion is cultish and insular, add Petition: Gaining Secrets
    - Your religion has important sacrificial rites, add Petition: Offering
    - Your religion believes in trial by combat, add Petition: Personal Victory
*** Divine Guidance
When you *petition your deity according to the precept of your religion*, you
are granted some useful knowledge or boon related to your deity’s domain. The GM
will tell you what.
*** Turn Undead
When you *hold your holy symbol aloft and call on your deity for protection*,
roll+Wis. ✴On a 7+, so long as you continue to pray and brandish your holy
symbol, no undead may come within reach of you. ✴On a 10+, you also momentarily
daze intelligent undead and cause mindless undead to flee. Aggression breaks the
effects and they are able to act as normal. Intelligent undead may still find
ways to harry you from afar. They’re clever like that.
*** Commune
When you *spend uninterrupted time (an hour or so) in quiet communion with your
deity*, you:
    - Lose any spells already granted to you.
    - Are granted new spells of your choice whose total levels don’t exceed your
      own level+1, and none of which is a higher level than your own level.
    - Prepare all of your rotes, which never count against your limit.
*** Cast a Spell
When you *unleash a spell granted to you by your deity*, roll+Wis. ✴On a 10+,
the spell is successfully cast and your deity does not revoke the spell, so you
may cast it again. ✴On a 7–9, the spell is cast, but choose one:
    - You draw unwelcome attention or put yourself in a spot. The GM will tell
      you how.
    - Your casting distances you from your deity—take -1 ongoing to cast a spell
      until the next time you commune.
    - After you cast it, the spell is revoked by your deity. You cannot cast the
      spell again until you commune and have it granted to you.
Note that maintaining spells with ongoing effects will sometimes cause a penalty
to your roll to cast a spell.
** Alignment
Choose an alignment:
*** Good
Endanger yourself to heal another.
*** Lawful
Endanger yourself following the precepts of your church or god.
*** Evil
Harm another to prove the superiority of your church or god.
** Gear
Your load is 10+Str. You carry dungeon rations (5 uses, 1 weight) and some
symbol of the divine, describe it (0 weight). Choose your defenses:
    - Chainmail (1 armor, 1 weight)
    - Shield (+1 armor, 2 weight)
Choose your armament:
    - Warhammer (close, 1 weight)
    - Mace (close, 1 weight)
    - Staff (close, two-handed, 1 weight) and bandages (0 weight)
Choose one:
    - Adventuring gear (1 weight) and dungeon rations (5 uses, 1 weight)
    - Healing potion (0 weight)
** Bonds
Fill in the name of one of your companions in at least one:

_______________ has insulted my deity; I do not trust them.

_______________ is a good and faithful person; I trust them implicitly.

_______________ is in constant danger, I will keep them safe.

I am working on converting _______________ to my faith.
** Advanced Moves
When you gain a level from 2–5, choose from these moves.
*** Chosen One
Choose one spell. You are granted that spell as if it was one level lower.
*** Invigorate
When you *heal someone* they take +2 forward to their damage.
*** The Scales of Life and Death
When *someone takes their last breath in your presence*, they take +1 to the
roll.
*** Serenity
When you cast a spell you ignore the first -1 penalty from ongoing spells.
*** First Aid
Cure Light Wounds is a rote for you, and therefore doesn’t count against your
limit of granted spells.
*** Divine Intervention
When you commune you get 1 hold and lose any hold you already had. Spend that
hold when you or an ally takes damage to call on your deity, they intervene with
an appropriate manifestation (a sudden gust of wind, a lucky slip, a burst of
light) and negate the damage.
*** Penitent
When you *take damage and embrace the pain*, you may take +1d4 damage (ignoring
armor). If you do, take +1 forward to cast a spell.
*** Empower
When you cast a spell, on a 10+ you have the option of choosing from the 7–9
list. If you do, you may choose one of these effects as well:
    - The spell’s effects are doubled
    - The spell’s targets are doubled
*** Orison for Guidance
When you *sacrifice something of value to your deity and pray for guidance*,
your deity tells you what it would have you do. If you do it, mark experience.
*** Divine Protection
When you wear no armor or shield you get 2 armor.
*** Devoted Healer
When you heal someone else of damage, add your level to the amount of damage
healed.
When you gain a level from 6–10, choose from these moves or the level 2–5 moves.
*** Anointed
Requires: Chosen One
Choose one spell in addition to the one you picked for chosen one. You are
granted that spell as if it was one level lower.
*** Apotheosis
The first time you *spend time in prayer as appropriate to your god* after
taking this move, choose a feature associated with your deity (rending claws,
wings of sapphire feathers, an all-seeing third eye, etc.). When you emerge from
prayer, you permanently gain that physical feature.
*** Reaper
When you *take time after a conflict to dedicate your victory to your deity and
deal with the dead*, take +1 forward.
*** Providence
Replaces: Serenity
You ignore the -1 penalty from two spells you maintain.
*** Greater First Aid
Requires: First Aid
Cure Moderate Wounds is a rote for you, and therefore doesn’t count against your
limit of granted spells.
*** Divine Invincibility
Replaces: Divine Intervention
When you commune you gain 2 hold and lose any hold you already had. Spend that
hold when you or an ally takes damage to call on your deity, who intervenes with
an appropriate manifestation (a sudden gust of wind, a lucky slip, a burst of
light) and negates the damage.
*** Martyr
Replaces: Penitent
When you *take damage and embrace the pain*, you may take +1d4 damage (ignoring
armor). If you do, take +1 forward to cast a spell and add your level to any
damage done or healed by the spell.
*** Divine Armor
Replaces: Divine Protection
When you wear no armor or shield you get 3 armor.
*** Greater Empower
Replaces: Empower
When you cast a spell, on a 10–11 you have the option of choosing from the 7–9
list. If you do, you may choose one of these effects as well. On a 12+ you get
to choose one of these effects for free.
    - The spell’s effects are doubled
    - The spell’s targets are doubled
*** Multiclass Dabbler
Get one move from another class. Treat your level as one lower for choosing the
move.