* Lower Depths
** Aboleth Group, Huge, Intelligent
*Tentacle (d10+3 damage) 18 HP 0 Armor*
*Reach*
*Special Qualities:* Telepathy
Deep below the surface of the world, in freshwater seas untouched by the sun,
dwell the aboleth. Fish the size of whales, with strange growths of gelatinous
feelers used to probe the lightless shores. They’re served by slaves: blind
albino victims of any race unfortunate enough to stumble on them, drained of
thought and life by the powers of the aboleth’s alien mind. In the depths they
plot against each other, fishy cultists building and digging upward towards the
surface until someday, they’ll breach it. For now, they sleep and dream and
guide their pallid minions to do their bidding. /Instinct/: To command
    - Invade a mind
    - Turn minions on them
    - Put a plan in motion
** Apocalypse Dragon Solitary, Huge, Magical, Divine
*Bite (b[2d12]+9 damage, 4 piercing) 26 HP 5 Armor*
*Reach, Forceful, Messy*
*Special Qualities:* Inch-thick metal hide, Supernatural knowledge, Wings
The end of all things shall be a burning—of tree and earth and of the air
itself. It shall come upon the plains and mountains not from beyond this world
but from within it. Birthed from the womb of deepest earth shall come the Dragon
that Will End the World. In its passing all will become ash and bile and the
Dungeon World a dying thing will drift through planar space devoid of life. They
say to worship the Apocalypse Dragon is to invite madness. They say to love it
is to know oblivion. The awakening is coming. /Instinct/: To end the world
    - Set a disaster in motion
    - Breathe forth the elements
    - Act with perfect foresight
** Chaos Spawn Solitary, Amorphous
*Chaotic touch (d10 damage) 19 HP 1 Armor*
*Close, Reach*
*Special Qualities:* Chaos form
Driven from the city, a cultist finds sanctuary in towns and villages.
Discovered there, he flees to the hills and scratches his devotion on the cave
walls. Found out again, he is chased with knife and torch into the depths,
crawling deeper and deeper until, in the deepest places, he loses his way.
First, he forgets his name. Then he forgets his shape. His chaos gods, most
beloved, bless him with a new one. /Instinct/: To undermine the established
order
    - Rewrite reality
    - Unleash chaos from containment
** Chuul Group, Large, Cautious
*Claws (d8+1 damage, 3 piercing) 10 HP 4 Armor*
*Close, Reach, Messy*
*Special Qualities:* Amphibious
Your worst seafood nightmare come to life. A vicious sort of half-man
half-crawdad, cursed with primal intelligence and blessed with a pair of
razor-sharp claws. Strange things lurk in the stinking pools in caverns best
forgotten and the chuul is one of them. If you spot one, your best hope is a
heavy mace to crack its shell and maybe a little garlic butter. Mmmm.
/Instinct/: To split
    - Split something in two with mighty claws
    - Retreat into water
** Deep Elf Assassin Group, Intelligent, Organized
*Poisoned blade (d8 damage, 1 piercing) 6 HP 1 Armor*
*Close*
It was not so simple a thing as a war over religion or territory. No
disagreement of queens led to the great sundering of the elves. It was sadness.
It was the very diminishing of the world by the lesser races. The glory of all
the elves had built was cracking and turning to glass. Some, then, chose to
separate themselves from the world; wracked with tears they turned their backs
on men and dwarves. There were others, though, that were overcome with something
new. A feeling no elf had felt before. Spite. Hatred filled these elves and
twisted them and they turned on their weaker cousins. Some still remain after
the great exodus below. Some hide amongst us with spider-poisoned blades, meting
out that strangest of punishments: elven vengeance. /Instinct/: To spite the
surface races
    - Poison them
    - Unleash an ancient spell
    - Call reinforcements
** Deep Elf Swordmaster Group, Intelligent, Organized
*Barbed blade (b[2d8]+2 damage, 1 piercing) 6 HP 2 Armor*
*Close*
The deep elves lost the sweetness and gentle peace of their bright cousins ages
ago, but they did not abandon grace. They move with a swiftness and beauty that
would bring a tear to any warrior’s eye. In the dark, they’ve practiced. A
cruelty has infested their swordsmanship—a wickedness comes to the fore. Barbed
blades and whips replace the shining pennant-spears of elven battles on the
surface. The swordmasters of the deep elf clans do not merely seek to kill, but
to punish with every stroke of their blades. Wickedness and pain are their
currency. /Instinct/: To punish unbelievers
    - Inflict pain beyond measure
    - Use the dark to advantage
** Deep Elf Priest Solitary, Divine, Intelligent, Organized
*Smite (d10+2 damage) 14 HP 0 Armor*
*Close, Reach*
*Special Qualities:* Divine connection
The spirits of the trees and the lady sunlight are far, far from home in the
depths where the deep elves dwell. New gods were found there, waiting for their
children to come home. Gods of the spiders, the fungal forests, and things that
whisper in the forbidden caves. The deep elves, ever attuned to the world around
them, listened with hateful intent to their new gods and found a new source of
power. Hate calls to hate and grim alliances were made. Even among these
spiteful ranks, piety finds a way to express itself. /Instinct/: To pass on
divine vengeance
    - Weave spells of hatred and malice
    - Rally the deep elves
    - Pass on divine knowledge
** Dragon Solitary, Huge, Terrifying, Cautious, Hoarder
*Bite (b[2d12]+5 damage, 4 piercing) 16 HP 5 Armor*
*Reach, Messy*
*Special Qualities:* Elemental blood, Wings
They are the greatest and most terrible things this world will ever have to
offer. /Instinct/: To rule
    - Bend an element to its will
    - Demand tribute
    - Act with disdain
** Gray Render Solitary, Large
*Rending claws (d10+3 damage, 3 piercing) 16 HP 1 Armor*
*Close, Reach, Forceful*
On its own, the render is a force of utter destruction. Huge and leathery, with
a maw of unbreakable teeth and claws to match, the render seems to enjoy little
more than tearing things apart. Stone, flesh, or steel, it matters little.
However, the gray render is so rarely found alone. They bond with other
creatures. Some at birth, others as fully-grown creatures, and a gray render
will follow their bonded master wherever they go, bringing them offerings of
meat and protecting them while they sleep. Finding an un-bonded render means
certain riches, if you survive to sell it. /Instinct/: To serve
    - Tear something apart
** Magmin Horde, Intelligent, Organized, Hoarder
*Flaming hammer (d6+2 damage) 7 HP 4 Armor*
*Close, Reach*
*Special Qualities:* Fiery blood
Dwarf-shaped and industrious, the magmin are among the deepest-dwellers of
Dungeon World. Found in cities of brass and obsidian built nearest the molten
core of the planet, the magmin live a life devoted to craft—especially that of
fire and magical items related to it. Surly and strange, they do not often deign
to speak to petitioners who appear at their gates, even those who have somehow
found a way to survive the hellish heat. Even so, they respect little more than
a finely made item and to learn to forge from a magmin craftsman means unlocking
secrets unknown to surface blacksmiths. Like so much else, visiting the magmin
is a game of risk and reward. /Instinct/: To craft
    - Offer a trade or deal
    - Strike with fire or magic
    - Provide just the right item, at a price
** Minotaur Solitary, Large
*Axe (d10+1 damage) 16 HP 1 Armor*
*Close, Reach*
*Special Qualities:* Unerring sense of direction
“Head of a man, body of a bull. No, wait, I’ve got that backwards. It’s the
bull’s head and the man’s body. Hooves sometimes? Is that right? I remember the
old king said something about a maze? Blast! You know I can’t think under this
kind of pressure. What was that? Oh gods, I think it’s coming…” /Instinct/: To
contain
    - Confuse them
    - Make them lost
** Naga Solitary, Intelligent, Organized, Hoarder, Magical
*Bite (d10 damage) 12 HP 2 Armor*
*Close, Reach*
Ambitious and territorial above nearly all else, the naga are very rarely found
without a well-formed and insidious cult of followers. You’ll see it in many
mountain towns—a snake sigil scrawled on a tavern wall or a local church burned
to the ground. People going missing in the mines. Men and women wearing the mark
of the serpent. At the core of it all lies a naga: an old race now fallen into
obscurity, still preening with the head of a man over its coiled, serpent body.
Variations of these creatures exist depending on their bloodline and original
purpose, but they are all master manipulators and magical forces to be reckoned
with. /Instinct/: To lead
    - Send a follower to their death
    - Use old magic
    - Offer a deal or bargain
** Salamander Horde, Large, Intelligent, Organized, Planar
*Flaming spear (b[2d6]+3 damage) 7 HP 3 Armor*
*Close, Reach, Near*
*Special Qualities:* Burrowing
“The excavation uncovered what the reports called a basalt gate. Black stone
carved with molten runes. When they dug it up, the magi declared it inert but
further evidence indicates that was an incorrect claim. The entire team went
missing. When we arrived, the gate was glowing. Its light filled the whole
cavern. We could see from the entrance that the area had become full of these
creatures—like men with red and orange skin, tall as an ogre but with a snake’s
tail where their legs ought to be. They were clothed, too—some had black glass
armor. They spoke to each other in a tongue that sounded like grease in a fire.
I wanted to leave but the sergeant wouldn’t listen. You’ve already read what
happened next, sir. I know I’m the only one that got back, but what I said is
true. The gate is open, now. This is just the beginning!” /Instinct/: To consume
in flame
    - Summon elemental fire
    - Melt away deception
