* The Druid
Cast your eyes around the fire. What has brought you to these people, stinking
of the dust and sweat of the city? Perhaps it is a kindness—do you protect them
as the mother bear watches over her cubs? Are they your pack, now? Strange
brothers and sisters you have. Whatever your inspiration, they would certainly
fail without your sharp senses and sharper claws.

You are of the sacred spaces; you are born of soil and wear the marks of her
spirits on your skin. You may have had a life before, maybe you were a city
dweller like them, but not now. You’ve given up that static shape. Listen to
your allies pray to their carved stone gods and polish their silver shells. They
speak of the glory they’ll find back in that festering town you left behind.

Their gods are children, their steel is false protection. You walk the old ways,
you wear the pelts of the earth itself. You’ll take your share of the treasure,
but will you ever walk as one of them? Only time will tell.
** Names
/Elf/: Hycorax, Ethanwe, Sinathel, Demanor, Menoliir, Mithralan, Taeros, Aegor
/Halfling/: Tanner, Dunstan, Rose, Ivy, Robard, Mab, Thistle, Puck, Anne, Serah
/Human/: Elana, Obelis, Herran, Syla, Andanna, Siobhan, Aziz, Pelin, Sibel,
Nils, Wei
** Look
Choose one for each:
Wise Eyes, Wild Eyes, or Haunting Eyes
Furry Hood, Messy Hair, or Braided Hair
Ceremonial Garb, Practical Leathers, or Weathered Hides
** Stats
Your maximum HP is 6+Constitution.
Your base damage is d6.
** Starting Moves
Choose a race and gain the corresponding move:
*** Elf
The sap of the elder trees flows within you. In addition to any other
attunements, the Great Forest is always considered your land.
*** Human
As your people learned to bind animals to field and farm, so too are you bound
to them. You may always take the shape of any domesticated animal, in addition
to your normal options.
*** Halfling
You sing the healing songs of spring and brook. When you make camp, you and your
allies heal +1d6.
You start with these moves:
*** Born of the Soil
You learned your magic in a place whose spirits are strong and ancient and
they’ve marked you as one of their own. No matter where you go, they live within
you and allow you to take their shape. Choose one of the following. It is the
land to which you are attuned—when shapeshifting you may take the shape of any
animal who might live in your Land.
    - The Great Forests
    - The Whispering Plains
    - The Vast Desert
    - The Stinking Mire
    - The River Delta
    - The Depths of the Earth
    - The Sapphire Islands
    - The Open Sea
    - The Towering Mountains
    - The Frozen North
    - The Blasted Wasteland
Chose a tell—a physical attribute that marks you as born of the soil—that
reflects the spirit of your land. It may be an animal feature like antlers or
leopard’s spots or something more general: hair like leaves or eyes of
glittering crystal. Your tell remains no matter what shape you take.
*** By Nature Sustained
You don’t need to eat or drink. If a move tells you to mark off a ration just
ignore it.
*** Spirit Tongue
The grunts, barks, chirps, and calls of the creatures of the wild are as
language to you. You can understand any animal native to your land or akin to
one whose essence you have studied.
*** Shapeshifter
When you call upon the spirits to change your shape, roll+Wis. ✴On a 10+ hold 3.
✴On a 7–9 hold 2. ✴On a miss hold 1 in addition to whatever the GM says.

You may take on the physical form of any species whose essence you have studied
or who lives in your land: you and your possessions meld into a perfect copy of
the species’ form. You have any innate abilities and weaknesses of the form:
claws, wings, gills, breathing water instead of air. You still use your normal
stats but some moves may be harder to trigger—a housecat will find it hard to do
battle with an ogre. The GM will also tell you one or more moves associated with
your new form. Spend 1 hold to make that move. Once you’re out of hold, you
return to your natural form. At any time, you may spend all your hold and revert
to your natural form.
*** Studied Essence
When you *spend time in contemplation of an animal spirit*, you may add its
species to those you can assume using shapeshifting.
** Alignment
Choose an alignment:
*** Chaotic
Destroy a symbol of civilization.
*** Good
Help something or someone grow.
*** Neutral
Eliminate an unnatural menace.
** Gear
Your load is 6+Str. You carry some token of your land, describe it. Choose your
defenses:
    - Hide armor (1 armor, 1 weight)
    - Wooden shield (+1 armor, 1 weight)
Choose your armament:
    - Shillelagh (close, 2 weight)
    - Staff (close, two-handed, 1 weight)
    - Spear (close, thrown, near, 1 weight)
Choose one:
    - Adventuring gear (1 weight)
    - Poultices and herbs (2 uses, 1 weight)
    - Halfling pipeleaf (0 weight)
    - 3 antitoxin (0 weight)
** Bonds
Fill in the name of one of your companions in at least one:

____________________ smells more like prey than a hunter.

The spirits spoke to me of a great danger that follows ______________.

I have showed ________________ a secret rite of the Land.

___________ has tasted my blood and I theirs. We are bound by it.
** Advanced Moves
When you gain a level from 2–5, choose from these moves.
*** Hunter’s Brother
Choose one move from the ranger class list.
*** Red of Tooth and Claw
When you *are in an appropriate animal form* (something dangerous) increase your
damage to d8.
*** Communion of Whispers
When *you spend time in a place, making note of its resident spirits and calling
on the spirits of the land*, roll+Wis. You will be granted a vision of
significance to you, your allies, and the spirits around you. ✴On a 10+ the
vision will be clear and helpful to you. ✴On a 7–9 the vision is unclear, its
meaning murky. ✴On a miss, the vision is upsetting, frightening, or
traumatizing. The GM will describe it. Take -1 forward.
*** Barkskin
So long as your feet touch the ground you have +1 armor.
*** Eyes of the Tiger
When you mark an animal (with mud, dirt, or blood) you can see through that
animal’s eyes as if they were your own, no matter what distance separates you.
Only one animal at a time may be marked in this way.
*** Shed
When you *take damage while shapeshifted* you may choose to revert to your
natural form to negate the damage.
*** Thing-Talker
You see the spirits in the sand, the sea and the stone. You may now apply your
spirit tongue, shapeshifting and studied essence to inanimate natural objects
(plants and rocks) or creatures made thereof, as well as animals. Thing-talker
forms can be exact copies or can be mobile vaguely humanoid-shaped entities.
*** Formcrafter
When you shapeshift choose a stat: you take +1 ongoing to rolls using that stat
while shifted. The GM will choose a stat, too: you take -1 ongoing to rolls
using that stat while shifted.
*** Elemental Mastery
When you *call on the primal spirits of fire, water, earth or air to perform a
task for you* roll+Wis. ✴On a 10+ choose two. ✴On a 7–9 choose one. ✴On a miss,
some catastrophe occurs as a result of your calling.
    - The effect you desire comes to pass
    - You avoid paying nature’s price
    - You retain control
*** Balance
When you *deal damage*, take 1 balance. When you touch someone and channel the
spirits of life you may spend balance. For each balance spent, heal 1d4 HP.
When you gain a level from 6–10, choose from these moves or the level 2–5 moves.
*** Embracing No Form
When you shapeshift, roll 1d4 and add that total to your hold.
*** Doppelgänger’s Dance
You are able to study the essence of specific individuals to take their exact
form, including men, elves, or the like. Suppressing your tell is possible, but
if you do, take -1 ongoing until you return to your own form.
*** Blood and Thunder
Replaces: Red of Tooth and Claw
When you *are in an appropriate animal form* (something dangerous) increase your
damage to d10.
*** The Druid Sleep
When you take this move, the next opportunity that you have safety and time to
spend in an appropriate location, you may attune yourself to a new land. This
effect occurs only once and the GM will tell you how long it will take and what
cost you must pay. From then on, you are considered to be born of the soil in
both lands.
*** World-Talker
Requires: Thing-Talker
You see the patterns that make up the fabric of the world. You may now apply
your spirit tongue, shapeshifter and studied essence moves to pure
elements—fire, water, air and earth.
*** Stalker’s Sister
Requires: Hunter’s Brother
Choose one move from the ranger class list.
*** Formshaper
Requires: Formcrafter
You may increase your armor by 1 or deal an additional +1d4 damage while in an
animal form. Choose which when you shapeshift.
*** Chimera
When you shapeshift, you may create a merged form of up to three different
shapes. You may be a bear with the wings of an eagle and the head of a ram, for
example. Each feature will grant you a different move to make. Your chimera form
follows the same rules as shapeshifter otherwise.
*** Weather Weaver
When you are under open skies when the sun rises the GM will ask you what the
weather will be that day. Tell them whatever you like, it comes to pass.