* Equipment
The musty tombs and forgotten treasure troves of the world are filled with
useful items. The fighter can find a sharp new sword or the thief might stumble
across a deadly poison. Most items are mundane—not magical or intrinsically
unique in any way. Any item that is magical or one-of-a-kind is not mundane for
the purposes of moves. The fighter’s signature weapon is never mundane.

Each piece of equipment will have a number of tags. These will tell you
something about how the equipment affects the character using it (like +Armor)
or suggest something about the way it is used (like the Range tags). Like
everything else in Dungeon World, these guide the fiction you’re creating in
play. If a weapon is awkward, it might mean that you’re more likely to drop it
when you fail that hack and slash roll.

By no means is this an exhaustive list—feel free to create your own tags.
*** General Equipment Tags

These are general tags that can apply to just about any piece of gear. You’ll
see them on armor, weapons or general adventuring tools.

/Applied/: It’s only useful when carefully applied to a person or to something
they eat or drink.

/Awkward/: It’s unwieldy and tough to use.

/+Bonus/: It modifies your effectiveness in a specified situation. It might be
“+1 forward to spout lore” or “-1 ongoing to hack and slash.”

/n coins/: How much it costs to buy, normally. If the cost includes “-Charisma”
a little negotiation subtracts the haggler’s Charisma score (not modifier) from
the price.

/Dangerous/: It’s easy to get in trouble with it. If you interact with it
without proper precautions the GM may freely invoke the consequences of your
foolish actions.

/Ration/: It’s edible, more or less.

/Requires/: It’s only useful to certain people. If you don’t meet the
requirements it works poorly, if at all.

/Slow/: It takes minutes or more to use.

/Touch/: It’s used by touching it to the target’s skin.

/Two-handed/: It takes two hands to use it effectively.

/n weight/: Count the listed amount against your load. Something with no listed
weight isn’t designed to be carried. 100 coins in standard denominations is 1
weight. The same value in gems or fine art may be lighter or heavier.

/Worn/: To use it, you have to be wearing it.

/n Uses/: It can only be used /n/ times.
** Weapons
Weapons don’t kill monsters, people do. That’s why weapons in Dungeon World
don’t have a listed damage. A weapon is useful primarily for its tags which
describe what the weapon is useful for. A dagger is not useful because it does
more or less damage than some other blade. It’s useful because it’s small and
easy to strike with at close distance. A dagger in the hands of the wizard is
not nearly so dangerous as one in the hands of a skilled fighter.
*** Weapon Tags
Weapons may have tags that are primarily there to help you describe them (like
Rusty or Glowing) but these tags have a specific, mechanical effect.

/n Ammo/: It counts as ammunition for appropriate ranged weapons. The number
indicated does not represent individual arrows or sling stones, but represents
what you have left on hand.

/Forceful/: It can knock someone back a pace, maybe even off their feet.

/+n Damage/: It is particularly harmful to your enemies. When you deal damage,
you add /n/ to it.

/Ignores Armor/: Don’t subtract armor from the damage taken.

/Messy/: It does damage in a particularly destructive way, ripping people and
things apart.

/n Piercing/: It goes right through armor. When you deal damage with /n/
piercing, you subtract /n/ from the enemy’s armor for that attack.

/Precise/: It rewards careful strikes. You use DEX to hack and slash with this
weapon, not STR.

/Reload/: After you attack with it, it takes more than a moment to reset for
another attack.

/Stun/: When you attack with it, it does stun damage instead of normal damage.

/Thrown/: Throw it at someone to hurt them. If you volley with this weapon, you
can’t choose to mark off ammo on a 7–9; once you throw it, it’s gone until you
can recover it.

Weapons have tags to indicate the range at which they are useful. Dungeon World
doesn’t inflict penalties or grant bonuses for “optimal range” or the like, but
if your weapon says Hand and an enemy is ten yards away, a player would have a
hard time justifying using that weapon against him.

/Hand/: It’s useful for attacking something within your reach, no further.

/Close/: It’s useful for attacking something at arm’s reach plus a foot or two.

/Reach/: It’s useful for attacking something that’s several feet away—maybe as
far as ten.

/Near/: It’s useful for attacking if you can see the whites of their eyes.

/Far/: It’s useful for attacking something in shouting distance.
*** Weapon List

The stats below are for typical items. There are, of course, variations. A dull
long sword might be -1 damage instead while a masterwork dagger could be +1
damage. Consider the following to be stats for typical weapons of their type—a
specific weapon could have different tags to represent its features.
**** Ragged Bow near, 15 coins, 2 weight
**** Fine Bow near, far, 60 coins, 2 weight
**** Hunter’s Bow near, far, 100 coins, 1 weight
**** Crossbow near, +1 damage, reload, 35 coins, 3 weight
**** Bundle of Arrows 3 ammo, 1 coin, 1 weight
**** Elven Arrows 4 ammo, 20 coins, 1 weight
**** Club, Shillelagh close, 1 coin, 2 weight
**** Staff close, two-handed, 1 coin, 1 weight
**** Dagger, Shiv, Knife hand, 2 coins, 1 weight
**** Throwing Dagger thrown, near, 1 coin, 0 weight
**** Short Sword, Axe, Warhammer, Mace close, 8 coins, 1 weight
**** Spear reach, thrown, near, 5 coins, 1 weight
**** Long Sword, Battle Axe, Flail close, +1 damage, 15 coins, 2 weight
**** Halberd reach, +1 damage, two-handed, 9 coins, 2 weight
**** Rapier close, precise, 25 coins, 1 weight
**** Dueling Rapier close, 1 piercing, precise, 50 coins, 2 weight
** Armor
Armor is heavy, difficult to wear and is damned uncomfortable. Some classes are
better trained to ignore these drawbacks, but anyone can strap on a suit of
armor and enjoy the benefits it grants.
*** Armor Tags
Armor, like weapons, has tags. Some are purely descriptive but the ones below
have some mechanical effect on the player wearing them

/n Armor/: It protects you from harm and absorbs damage. When you take damage,
subtract your armor from the total. If you have more than one item with /n
Armor/, only the highest value counts.

/+n Armor/: It protects you and stacks with other armor. Add its value to your
total armor.

/Clumsy/: It’s tough to move around with. -1 ongoing while using it. This
penalty is cumulative.
*** Armor List
**** Leather, Chainmail 1 armor, worn, 10 coins, 1 weight
**** Scale Mail 2 armor, worn, clumsy, 50 coins, 3 weight
**** Plate 3 armor, worn, clumsy, 350 coins, 4 weight
**** Shield +1 armor, 15 coins, 2 weight
** Dungeon Gear
**** Adventuring Gear 5 uses, 20 coins, 1 weight
Adventuring gear is a collection of useful mundane items such as chalk, poles,
spikes, ropes, etc. When you rummage through your adventuring gear for some
useful mundane item, you find what you need and mark off a use.
**** Bandages 3 uses, slow, 5 coins, 0 weight
When you have a few minutes to bandage someone else’s wounds, heal them of 4
damage and expend a use.
**** Poultices and Herbs 2 uses, slow, 10 coins, 1 weight
When you carefully treat someone’s wounds with poultices and herbs, heal them of
7 damage and expend a use.
**** Healing Potion 50 coins, 0 weight
When you drink an entire healing potion, heal yourself of 10 damage or remove
one debility, your choice.
**** Keg of Dwarven Stout 10 coins, 4 weight
When you open a keg of dwarven stout and let everyone drink freely, take +1 to
your Carouse roll. If you drink a whole keg yourself, you are very, very drunk.
**** Bag of Books 5 uses, 10 coins, 2 weight
When your bag of books contains just the right book for the subject you’re
spouting lore on, consult the book, mark off a use, and take +1 to your roll.
**** Antitoxin 10 coins, 0 weight
When you drink antitoxin, you’re cured of one poison affecting you.
**** Dungeon Rations Ration, 5 uses, 3 coins, 1 weight
Not tasty, but not bad either.
**** Personal Feast Ration, 1 use, 10 coins, 1 weight
Ostentatious to say the least.
**** Dwarven Hardtack Requires Dwarf, ration, 7 uses, 3 coins, 1 weight
Dwarves say it tastes like home. Everyone else says it tastes like home, if home
is a hog farm, and on fire.
**** Elven Bread Ration, 7 uses, 10 coins, 1 weight
Only the greatest of elf-friends are treated to this rare delicacy.
**** Halfling Pipeleaf 6 uses, 5 coins, 0 weight
When you share halfling pipeleaf with someone, expend two uses and take +1
forward to parley with them.
** Poisons
**** Oil of Tagit Dangerous, applied, 15 coins, 0 weight
The target falls into a light sleep.
**** Bloodweed Dangerous, touch, 12 coins, 0 weight
Until cured, whenever the afflicted rolls damage, they roll an additional d4 and
subtract that result from their normal damage.
**** Goldenroot Dangerous, applied, 20 coins, 0 weight
The target treats the next creature they see as a trusted ally, until proved
otherwise.
**** Serpent’s Tears Dangerous, touch, 10 coins, 0 weight
Anyone dealing damage against the target rolls twice and takes the better
result.
** Services
**** A week’s stay at a peasant inn 14-Charisma coins
**** A week’s stay at a civilized inn 30-Charisma coins
**** A week’s stay at the fanciest inn in town 43-Charisma coins
**** A week’s unskilled mundane labor 10 coins
**** A month’s pay for enlistment in an army 30 coins
**** A custom item from a blacksmith Base Item + 50 coins
**** A night’s “companionship” 20-Charisma coins
**** An evening of song and dance 18-Charisma coins
**** Escort for a day along a bandit-infested road 20 coins
**** Escort for a day along a monster-infested road 54 coins
**** A run-of-the-mill killing 5 coins
**** An assassination 120 coins
**** Healing from a chirurgeon 5 coins
**** A month’s prayers for the departed 1 coin
**** Repairs to a mundane item 25% of the item’s cost
** Meals
**** A hearty meal for one 1 coin
**** A poor meal for a family 1 coin
**** A feast 15 coins per person
** Transport
**** Cart and Donkey, sworn to carry your burdens 50 coins, load 20
**** Horse 75 coins, load 10
**** Warhorse 400 coins, load 12
**** Wagon 150 coins, load 40
**** Barge 50 coins, load 15
**** River boat 150 coins, load 20
**** Merchant ship 5,000 coins, load 200
**** War ship 20,000 coins, load 100
**** Passage on a safe route 1 coin
**** Passage on a tough route 10 coins
**** Passage on a dangerous route 100 coins
** Land and Buildings
**** A hovel 20 coins
**** A cottage 500 coins
**** A house 2,500 coins
**** A mansion 50,000 coins
**** A keep 75,000 coins
**** A castle 250,000 coins
**** A grand castle 1,000,000 coins
**** A month’s upkeep 1% of the cost
** Bribes
**** A peasant dowry 20-Charisma coins
**** “Protection” for a small business 100-Charisma coins
**** A government bribe 50-Charisma coins
**** A compelling bribe 80-Charisma coins
**** An offer you can’t refuse 500-Charisma coins
** Gifts and Finery
**** A peasant gift 1 coin
**** A fine gift 55 coins
**** A noble gift 200 coins
**** A ring or cameo 75 coins
**** Finery 105 coins
**** A fine tapestry 350+ coins
**** A crown fit for a king 5,000 coins
** Hoards
**** A goblin’s stash 2 coins
**** A lizardman’s trinkets 5 coins
**** A “priceless” sword 80 coins
**** An orc warchief’s tribute 250 coins
**** A dragon’s mound of coins and gems 130,000 coins
* Magic Items
There are stranger things in the world than swords and leather. Magic items are
the non-mundane items that have intrinsic power.

Magic items are for you to make for your game. Players can make magic items
through the wizard’s ritual and similar moves. The GM can introduce magic items
in the spoils of battle or the rewards for jobs and quests. This list provides
some ideas, but magic items are ultimately for you to decide.

When making your own magic items keep in mind that these items are /magical/.
Simple modifiers, like+1 damage, are the realm of the mundane—magic items should
provide more interesting bonuses.
** Argo-Thaan, Holy Avenger Close, 2 weight
There are many swords in this world, but there is only one Argo-thaan. It is a
blade of gold, silver and light, revered as a holy relic by all orders and
religions for whom Good rings true. Its touch is a blessing and to many, the
sight of it brings tears of joy.

In the hands of a paladin, it strikes true and strong. A paladin wielding it
increases their damage die to d12 and has access to every paladin move. As well,
Argo-thaan can harm any creature of Evil, regardless of any defenses it may
have. No Evil creature may touch it without suffering agony. In the hands of any
non-paladin, it is merely a sword, heavier and more cumbersome than most—it
gains the awkward tag.

Argo-thaan, while not intelligent, will forever be drawn to a cause of true
Good, like iron to a magnet.
** Arrows of Acheron 1 ammo, 1 weight
Crafted in darkness by a blind fletcher, these arrows can find their target in
even the deepest darkness. An archer may fire them blind, in the dark, with his
eyes bound by heavy cloth and still be assured of a clean shot. If the light of
the sun ever touches the arrows, however, they come apart like shadows and dust.
** Axe of the Conqueror-King Close, 1 weight
It is crafted of shining steel, glowing with a golden light and imbued with
mythical powers of authority. When you bear the axe, you become a beacon of
inspiration to all you lead. Any hirelings in your employ have +1 Loyalty, no
matter the quality of your leadership.
** Barb of the Black Gate 0 weight
A nail or spike, twisted and forever cold, said to have been pried from the
Gates of Death. When hammered into a corpse, it disappears and ensures that
corpse will never be risen again—no magic short of that of Death himself can
reignite the flame of life (natural or otherwise) in the body.
** Bag of Holding 0 weight
A bag of holding is larger on the inside than the outside, it can contain an
infinite number of items, and its weight never increases. When you try to
retrieve an item from a bag of holding, roll+WIS. ✴On a 10+, it’s right there.
✴On a 7-9, choose one:
    - You get the exact item, but it takes a while
    - You get a similar item of the GM’s choice, but it only takes a moment
No matter how many items it contains, a bag of holding is always 0 weight.
** The Burning Wheel 2 weight
An ancient wooden wheel, as might appear on a war-wagon, banded with steel. On a
glance, it appears to be nothing special—many spokes are shattered and the thing
seems mundane. Under the scrutiny of magic or the eyes of an expert, its true
nature is revealed: the Burning Wheel is a gift from the God of Fire and burns
with his authority.

When you hold The Burning Wheel and speak a god’s name, roll+CON. ✴On a 7+, the
god you name takes notice and grants you an audience. An audience with a god is
not without a price: on a 10+, you choose one of your stats and reduce it to the
next lowest modifier (for example, a 14 is +1, so it would be reduced to 12, a
+0). ✴On a 7–9, the GM chooses which stat to reduce.

Once used, the Burning Wheel ignites and burns with brilliant light. It does not
confer any protection from those flames, nor does it provide any bonus to
swimming.
** Captain Bligh’s Cornucopia 1 weight
A brass naval horn, curled and ornate, carved with symbols of the gods of
Plenty. When blown, in addition to sound, the horn spills forth food. Enough to
feed a meal to everyone who hears its sound.
** The Carcosan Spire Reach, Thrown, 3 weight
None know from whence this spear of twisted white coral comes. Those who bear it
too long find their minds full of alien dreams and begin to hear the strange
thoughts of the Others. None are impervious. Used against any “natural” target
(men, goblins, owlbears and the like) the Spire acts as a mere mortal spear. Its
true purpose is to do harm to those things whose strange natures protect them
against mundane weapons. Used thus, the Spire can wound foes otherwise
invulnerable to harm. The wielder will recognize these twisted foes on sight—the
Spire knows its own.
** Cloak of Silent Stars 1 weight
A cape of rich black velvet outside and sparkling with tiny points of light
within, this cloak bends fate, time and reality around it to protect the wearer,
who may defy danger with whatever stat they like. To do this, the wearer invokes
the cloak’s magic and their player describes how the cloak helps “break the
rules.” They can deflect a fireball with CHA by convincing it they deserve to
live or elude a fall by applying the mighty logic of their INT to prove the fall
won’t hurt. The cloak makes it so. It can be used once for each stat before
losing its magic.
** Coin of Remembering 0 weight
What appears, at a glance, to be a simple copper coin is, in truth, an enchanted
coin. Its bearer can, at any time, redeem it to know immediately one fact that
has been forgotten. The coin vanishes thereafter. It does not have to be a thing
forgotten by the bearer, but it cannot be “known.” Interpretation of this
stipulation is left to the gods. If the coin is unsuccessful, it will still
paint an image in the mind’s eye of someone or something that does remember what
was sought.
** Common Scroll 1 use, 0 weight
A common scroll has a spell inscribed on it. The spell must be castable by you
or on your class’s spell list for you to be able to cast it. When you cast a
spell from a scroll, the spell takes effect, simple as that.
** Devilsbane Oil 1 use, 0 weight
A holy oil, created in limited supply by a mute sect of mountain monks whose
order protected humanity from the powers of the Demon Pits in ancient epochs.
Only a few jars remain. When applied to any weapon and used to strike a denizen
of any outer plane, the oil undoes the magic that binds that creature. In some
cases, this will return it to its home. In others, it merely undoes any magic
controlling it. The oil stays on the weapon for a few hours before it dries and
flakes away.

If applied to the edges of a doorway or drawn in a circle, the oil will repel
creatures whose home is any of the outer planes. They cannot pass across it. The
oil lasts for one full day before it soaks in or evaporates.
** Earworm Wax 1 use, 0 weight
A yellowish candle. Seems never to burn out and the light it casts is strange
and weak. Its wax is always cool, too. Drip the wax into the ear of a target and
gain 3 hold. Spend that hold and ask your target a question. They find
themselves telling you the whole truth, despite themselves. The consequences,
after the fact? Those are up to you to deal with.
** The Echo 0 weight
A seemingly empty bottle. Once unstoppered, the whispers of another plane
resound once and fall silent. In the silence, the bearer learns in his soul the
coming of one great danger and how he can avoid it. At any point after you use
the Echo, you can ignore the results of any single die roll—yours or another
player’s—and roll again. Once opened, the Echo is released and gone forever.
** The Epoch Lens 1 weight
An archmage, old and too frail to leave his tower, crafted this intricate and
fragile device of glass and gold to examine the histories and relics he so
loved. Looking at an object through the lens reveals visions of who made it and
where it came from.
** Farsight Stone 1 weight
Swirling clouds fill this smoky orb and those in its presence often hear strange
whispers. In ancient times, it was part of a network of such stones, used to
communicate and surveil across great distances. When you gaze into the stone,
name a location and roll+WIS. ✴On a 10+, you see a clear vision of the location
and can maintain it as long as you concentrate on the orb. ✴On a 7–9, you still
see the vision, but you draw the attention of some other thing (an angel, a
demon, or the holder of another Farsight stone) that uses the stone to surveil
you, as well.
** The Fiasco Codex 0 weight
A thick tome, said to be penned in the blood of poor fools and robber-barons by
some demon prince possessed of dark humor, this tome details tales and stories
of those whose ambition overwhelmed their reason. Reading from this tome teaches
one the value of clear-headedness but leaves a sense of dread behind. When you
read from the Fiasco Codex, Roll+WIS. ✴On a 10+, ask two of the questions below.
✴On a 7–9, ask one.
    - What is my greatest opportunity, right now?
    - Who can I betray to gain an advantage?
    - Who is an ally I should not trust?
The codex gives up its answers only once to each reader and takes 2 to 3 hours
to read.
** Flask of Breath 0 weight
A simple thing, but useful when you need a breath of fresh air. The flask
appears empty but cannot be filled, anything added to it simply spills out. This
is because the flask is eternally full of air. If placed underwater, it will
bubble forever. If pressed to the mouth, one can breathe normally—smoke is no
concern, for example. I’m sure you’ll find all sorts of unusual uses for it.
** Folly Held Aloft, The Wax Wings, A Huge Mistake 1 weight
Who hasn’t always wanted to soar the pretty blue sky? In an attempt to grant the
wishes of land-bound folk, these great magical wings were created. Known by many
names and crafted by as many mages, they commonly take the shape of the wings of
whatever local birds hold affection. Worn by means of a harness or, in some dire
cases, a surgical procedure.

When you take to the air with these magical wings, roll+DEX. ✴On a 10+, your
flight is controlled and you may stay aloft as long as you like. ✴On a 7–9, you
make it aloft but your flight is short or erratic and unpredictable, your
choice. ✴On a 6-, you make it aloft, but the coming-down part and everything
between is up to the GM.
** Immovable Rod 0 weight
A funny metal rod with a button on it. Press the button and the rod just sticks.
It freezes in place—in midair, standing up or lying down. It can’t be moved.
Pull it, push it, try as hard as you like, the rod stays. Maybe it can be
destroyed, maybe it can’t. Push the button again and it’s free—take it along
with you. Might be useful to have such a stubborn thing along.
** Infinite Book 1 weight
This book contains an infinite number of pages in a finite space. With no limit
to the pages, everything that ever was, is, or will be is contained somewhere in
the book. Luckily the index is great.

When you spout lore while consulting the book you gain an extra clause: On a
12+, the GM will give a solution to a problem or situation you’re in.
** Inspectacles 0 weight
Rough-hewn glass in wooden frames. Dinged up and barely held together, they
somehow allow the wearer to see much more than their naked eyes might. When you
discern realities wearing these gifted lenses, you get to bend the rules a
little. On a roll of 10+, ask any three questions you like. They don’t have to
be on the list. As long as sight could give you answers, the GM will tell you
what you want to know.
** The Ku’meh Maneuver 1 weight
A great, leathery tome worn shiny by the hands of a hundred great generals, this
book is often passed from warrior to warrior, from father to son along the great
battle lines that have divided Dungeon World’s past. Anyone reading it may, upon
finishing for the first time, roll+INT. ✴On a 10+, hold 3. ✴On a 7-9, hold 1.
You may spend your hold to advise a companion on some matter of strategic or
tactical significance. This advice allows you to, at any time, regardless of
distance, roll to aid them on any one roll. On a miss, the GM can hold 1 and
spend it to apply -2 to any roll of yours or the poor sap who listened to your
advice.
** Lamented Memento 0 weight
Taking the form of a single lock of bright red hair, bound in a black ribbon and
immune to the ravages of time, the Lamented Memento bears a grim enchantment. In
it are the memories and emotions of a girl who dealt with Death at the Black
Gates so many times that, in the end, they fell in love and she left the world
to be with him for a time. Her memory protects the wielder. If he finds himself
at the Gates, the Memento can be traded for an automatic result of 10+ on the
Last Breath move.
** Lodestone Shield +1 armor, 1 weight
What mixed-up dummy made this? Shields are meant to repel metal, not draw it in!
Emblazoned with a lion rampant, the Lodestone Shield has the power to pull
blades and arrows to it. When you defend against enemies using metal weapons you
can spend one hold, per target, to disarm them. Also, sometimes you’ll find a
handful of loose change stuck to it.
** Map of the Last Patrol 0 weight
An ancient order of brave rangers once patrolled the land, protecting villages
and warning kings and queens of encroaching danger. They’re long gone, now, but
their legacy remains. This map, when marked with the blood of a group of people,
will always show their location—so long as they remain within the bounds of the
map.
** Ned’s Head 1 weight
An old skull, missing its jaw and very much worse-for-wear. The skull remembers
the folly of its former owner—a man with more honor than sense. Once per night,
the owner of the skull can ask “Who has it in for me?” and the skull will give
up one name in a sad, lonely voice. If the owner of the skull is ever killed, it
disappears surreptitiously. No one knows where it might turn up next.
** Nightsider’s Key 0 weight
This key unlocks any door for you, provided you don’t belong where you intend to
go. So long as you do nothing that would alert another to your presence
(remaining unheard, unseen and unnoticed) and takes nothing more than your
memories out with you, the key’s magic will prevent your intrusion from ever
being discovered. It’s like you were never there at all.
** Sacred Herbs 0 weight
The sacred herbs, collected and prepared by an order of lost wizard-monks, can
be found in bundles with two or three uses to them. Kept dry, they last
indefinitely. When smoked in a pipe or consumed in an incense burner and the
thick, blue smoke inhaled, these herbs will grant you strange visions of faraway
places and distant times. If you focus your will on a particular person, place
or thing, the herbs will respond: roll+WIS. ✴On a 10+, the vision is clear and
useful—yielding some valid information. ✴On a 7–9, the vision is about the thing
desired, but is unclear, fraught with metaphor or somehow difficult to
understand. ✴On a miss, the GM will ask you, “What is it you fear most?” You
must answer honestly, of course.
** The Sartar Duck 0 weight
An odd, hand-carved wooden duck. Who would make such a funny thing? While you
bear it, you find yourself an exceptionally gifted storyteller—no matter the
language, you can make yourself and your story clear to any audience. They will
understand your meaning, if not your words.
** Tears of Annalise 0 weight
Cloudy red gemstones the size of a thumbnail, the Tears of Annalise are always
found in pairs. When swallowed by two different people, they bind the swallowers
together—when either feels strong emotions (particularly sadness, loss, fear or
desire) the other feels it, as well. The effects last until one spills the blood
of the other.
** Teleportation Room Slow
James Ninefingers, eccentric genius mage, created these room-sized magical
apparati. A stone chamber etched with runes and scribblings, glowing with a
faint blue light. When you enter and say aloud the name of a location, roll+INT.
✴On a 10+, you arrive exactly where you’d intended. ✴On a 7–9, the GM chooses a
safe location nearby. ✴On a miss, you end up someplace. Maybe it’s nearby? It’s
definitely not safe. Strange things sometimes happen to those who bend time and
space with these devices.
** Timunn’s Armor 1 armor, 1 weight
A stealthy suit of armor, it appears as many things to many people and blends in
with appropriate apparel. The wearer always seems the height of fashion to any
who gaze upon him.
** Titus’ Truthful Tallow 0 weight
A candle of ivory- and copper-colored tallow with a wick of spun silver. When
lit, none upon whom its light falls is able to tell a lie. They may keep silent
or dissemble but when asked a question directly, they can speak naught but
truth.
** Tricksy Rope 1 weight
A rope that listens. Does tricks, too, like a smart and more obedient snake
might. Tell it “Coil” or “Slack” or “Come here, rope” and it will.
** The Sterling Hand 0 weight
Crafted by dwarven whitesmiths, this mirrored-metal hand is deeply scored with
runes of power and rejuvenation. Meant to replace wounded or destroyed limbs
from mining accidents, the Sterling Hand bonds to the wound, old or new, and is
strong and stout. It can be used as a weapon (Near range) and is made of pure
enough silver to harm creatures affected by such.
** Vellius’s Gauntlets 1 weight
Crafted in the name of Vellius the Clumsy, Vellius the Butter-Fingered, Vellius
the Clod, these gloves of simple cloth prevent you from dropping any object you
don’t intend to. You cannot be disarmed and will not fall from any rope or
ladder, for example. This item can get very messy if you have something strong
pulling at your legs while you grip onto something solid.
** Violation Glaive Reach, 2 weight
A legendary blade, said to have been thrust backwards in time from some grim
future, the violation glaive is crafted of strange green iron. The blade strikes
at the mind of those it wounds, as well as the body. When you hack and slash on
a 10+ you have an additional option: you can deal your normal damage, let them
counterattack you, and instill the emotion of your choice (maybe fear,
reverence, or trust).
** Vorpal Sword Close, 3 piercing, 2 weight
Snicker-snack and all that. Sharp as anything, this simple-seeming sword means
to separate one thing from another—the limb from the body or folk from their
lives. When you deal damage with the Vorpal Sword, your enemy must choose
something (an item, an advantage, a limb) and lose it, permanently.
