* Folk of the Realm
** Acolyte
“Can’t all be the High Priest, they said. Can’t all wield the White Spire, they
said. Scrub the floor, they told me. The Cthonic Overgod don’t want a messy
floor, do he? They said it’d be enlightenment and magic. Feh. It’s bruised knees
and dishpan hands. If only I’d been a cleric, instead.” /Instinct/: To serve
dutifully
    - Follow dogma
    - Offer eternal reward for mortal deeds
** Adventurer Horde, Intelligent
*Sword (d6 damage) 3 HP 1 Armor*
*Close*
*Special Qualities:* Endless enthusiasm
“Scum of the earth, they are. A troupe of armored men and women come sauntering
into town, brandishing what, for all intents and purposes, is enough magical and
mundane power to level the whole place. Bringing with them bags and bags of
loot, still dripping blood from whatever poor sod they had to kill to get it. An
economical fiasco waiting to happen, if you ask me. The whole system becomes
completely uprooted. Dangerous, unpredictable murder-hobos. Oh, wait, you’re an
adventurer? I take it all back.” /Instinct/: To adventure or die trying
    - Go on a fool’s errand
    - Act impulsively
    - Share tales of past exploits
** Bandit Horde, Intelligent, Organized
*Dirk (d6 damage) 3 HP 1 Armor*
*Close*
Desperation is the watchword of banditry. When times are tough, what else is
there to do but scavenge a weapon and take up with a clan of nasty men and
women? Highway robbery, poaching, scams and cons and murder most foul but we’ve
all got to eat so who can blame them? Then again, there’s evil in the hearts of
some and who’s to say that desperation isn’t a need to sate one’s baser lusts?
Anyway—it’s this or starve, sometimes. /Instinct/: To rob
    - Steal something
    - Demand tribute
** Bandit King Solitary, Intelligent, Organized
*Trusty knife (b[2d10] damage) 12 HP 1 Armor*
*Close*
Better to rule in hell than serve in heaven. /Instinct/: To lead
    - Make a demand
    - Extort
    - Topple power
** Fool
There’s not but one person in all the King’s court allowed to speak the truth.
The real, straight-and-honest truth about anything. The fool couches it all in
bells and prancing and chalky face-paint, but who else gets to tell the King
what’s what? You can trust a fool, they say, especially when he’s made you
red-faced and you’d just as soon drown him in a cesspit. /Instinct/: To mock
    - Expose injustice
    - Play a trick
** Guardsman Group, Intelligent, Organized
*Spear (d8 damage) 6 HP 1 Armor*
*Close, Reach*
Noble protector or merely drunken lout, it often makes no difference to these
sorts. Falling shy of a noble knight, the proud town guard is an ancient
profession nonetheless. These folks of the constabulary often dress in the
colors of their lord (when you can see it under the mud) and, depending on the
richness of that lord, might even have a decent weapon and some armor that fits.
Those are the lucky ones. Even so, someone has to be there to keep an eye on the
gate when the Black Riders have been spotted in the woods. Too many of us owe
our lives to these souls—remember that the next time one is drunkenly insulting
your mother, hmm? /Instinct/: To do as ordered
    - Uphold the law
    - Make a profit
** Halfling Thief Solitary, Small, Intelligent, Stealthy, Devious
*Dagger (w[2d8] damage) 12 HP 1 Armor*
*Close*
It would be foolish, now, to draw conclusions about folks just because they
happen to be good at one thing or another. Then again, a spade’s a spade, isn’t
it. Or maybe just the goodly, soft-and-sweet type of Halfling have the mind to
stay in their grassy-hill homes and aren’t the type you find in the slums and
taverns of the mannish world. Perhaps they’re there to cut your purse for
calling them “halfling” in the first place. Not all take so kindly to the title.
Or they’re playing a game, pretending to be a child in need of alms—and your
arrogant eyes can’t even see the difference until too late. Well, it matters
little. They’re gone with your coin before you even realize you deserved it.
/Instinct/: To live a life of stolen luxury
    - Steal
    - Put on the appearance of friendship
** Hedge Wizard Magical
Not all those who wield the arcane arts are adventuring wizards. Nor
necromancers in mausoleums or sorcerers of ancient bloodline. Some are just old
men and women, smart enough to have discovered a trick or two. It might make
them a bit batty to come by that knowledge, but if you’ve a curse to break or a
love to prove, might be that a hedge wizard will help you, if you can find his
rotten hut in the swamp and pay the price he asks. /Instinct/: To learn
    - Cast almost the right spell (for a price)
    - Make deals beyond their ken
** High Priest
Respected by all who gaze upon them, the high priests and abbesses of Dungeon
World are treated with a sort of reverence. Whether they pay homage to
Ur-thuu-hak, God of Swords, or whisper quiet prayers to Namiah, precious
daughter of peace, they know a thing or two that you and I won’t ever know. The
gods speak to them as a hawker-of-wares might speak to us in the marketplace.
For this, for the bearing-of-secrets and the knowing-of-things, we give them a
wide berth as they pass in their shining robes. /Instinct/: To lead
    - Set down divine law
    - Reveal divine secrets
    - Commission divine undertakings
** Hunter Group, Intelligent
*Ragged bow (d6 damage) 6 HP 1 Armor*
*Near, Far*
The wilds are home to more than just beasts of horn and scale. There are men and
women out there, too—those who smell blood on the wind and stalk the plains in
the skins of their prey. Whether with a trusty longbow bought on a rare trip
into the city or with a knife of bone and sinew, these folk have more in common
with the things they track and eat than with their own kind. Solemn, somber and
quiet, they find a sort of peace in the wild. /Instinct/: To survive
    - Bring back news from the wilds
    - Slay a beast
** Knight Solitary, Intelligent, Organized, Cautious
*Sword (b[2d10] damage) 12 HP 4 Armor*
*Close*
What youngster doesn’t cling to the rail at the mighty joust, blinded by the sun
on their glittering armor, wishing they could be the one adorned in steel and
riding to please the King and Queen? What peasant youth with naught but a loaf
of bread and a lame sow doesn’t wish to trade it all in for the lance and the
bright pennant? A knight is many things—a holy warrior, a sworn sword, a villain
sometimes, too, but a knight cannot help but be a symbol to all who see her. A
knight means something. /Instinct/: To live by a code
    - Make a moral stand
    - Lead soldiers into battle
** Merchant
“Ten foot poles. Get your ten foot poles, here. Torches, bright and hot. Mules,
too—stubborn but immaculately bred. Need a linen sack, do you? Right over here!
Come and get your ten foot poles!” /Instinct/: To profit
    - Propose a business venture
    - Offer a “deal”
** Noble
Are they granted their place by the gods, perhaps? Is that why they’re able to
pass their riches and power down by birth? Some trick or enchantment of the
blood, maybe. The peasant bends his knee and scrapes and toils and the noble
wears the finery of his place and, they say, we all have our burdens to bear.
Seems to me that some of us have burdens of stone and some carry their weight in
gold. It’s a tough life. /Instinct/: To rule
    - Issue an order
    - Offer a reward
** Peasant
Covered in muck, downtrodden at the bottom of the great chain of being, we all
stand on the backs of those who grow our food on their farms. Some peasants do
better than others, but none will ever see a coin of gold in their day. They’ll
dream at night of how someday, somehow, they’ll fight a dragon and save a
princess. Don’t act like you weren’t one before you lost what little sense you
had, adventurer. /Instinct/: To get by
    - Plead for help
    - Offer a simple reward and gratitude
** Rebel Horde, Intelligent, Organized
*Axe (d6 damage) 3 HP 1 Armor*
*Close*
In the countryside they’d be called outlaw and driven off or killed. The city,
though, is full of places to hide. Damp basements to pore over maps and to plan
and plot against a corrupt system. Like rats, they gnaw away at order, either to
supplant it anew or just erode the whole thing. The line between change and
chaos is a fine one—some rebels walk that thin line and others just want to see
it all torched. Disguise, a knife in the dark or a thrown torch at the right
moment are all tools of the rebel. The burning brand of anarchy is a common fear
amongst the nobles of Dungeon World. These men and women are why. /Instinct/: To
upset order
    - Die for a cause
    - Inspire others
** Soldier Horde, Intelligent, Organized
*Spear (d6 damage) 3 HP 1 Armor*
*Close, Reach*
For a commoner with a strong arm, sometimes it’s this or be a bandit. It’s wear
the colors and don ill-fitting armor and march into the unknown with a thousand
other scared men and women conscripted to fight the wars of our time. They could
be hiding out in the woods instead, living off poached elk and dodging the
king’s guard. Better to risk one’s life in service to a cause. To bravely toss
one’s lot in with one’s fellows and hope to come out the other side still in one
piece. Besides, the nobles need strong men and women. What is it they say? A
handful of soldiers beats a mouthful of arguments. /Instinct/: To fight
    - March into battle
    - Fight as one
** Spy
Beloved of kings but never truly trusted. Mysterious, secretive and alluring,
the life of a spy is, if you ask a commoner, full of romance and intrigue.
They’re a knife in the dark and a pair of watchful eyes. A spy can be your best
friend, your lover or that old man you see in the market every day. One never
knows. Hells, maybe you’re a spy—they say there’s magic that can turn folks’
minds without them ever knowing it. How can we trust you? /Instinct/: To
infiltrate
    - Report the truth
    - Double cross
** Tinkerer
It’s said that if you see a tinker on the road and you don’t offer him a swig of
ale or some of your food that he’ll leave a curse of bad luck behind. A tinker
is a funny thing. These strange folk often travel the roads between towns with
their oddment carts and favorite mules. With a ratty dog and always a story to
tell. Sometimes the mail, too, if you’re lucky and live in a place where Queen’s
Post won’t go. If you’re kind, maybe they’ll sell you a rose that never wilts or
a clock that chimes with the sound of faerie laughter. Or maybe they’re just
antisocial peddlers. You never know, right? /Instinct/: To create
    - Offer an oddity at a price
    - Spin tales of great danger and reward in far-off lands
