
* Basic Moves
This chapter contains the moves that are available to all characters. These
moves fall into two categories: basic and special.

Basic moves are the bread and butter of the adventurer’s life. They cover
situations likely to come up in fights, tense negotiations, and dangerous areas.

Special moves come up a little more rarely. They cover things like gaining a
level, taking a long journey, or returning to town between adventures.

All player characters have all the basic and special moves. Each player
character will also have some moves from their class—we’ll get to those later.

Each move is presented here starting with its name, then the rules of the move.
Some are also accompanied by a quick discussion of how to use the move and some
examples of the move being used in play.
** Hack and Slash
When you attack an enemy in melee, roll+Str. ✴On a 10+, you deal your damage to
the enemy and avoid their attack. At your option, you may choose to do +1d6
damage but expose yourself to the enemy’s attack. ✴On a 7–9, you deal your
damage to the enemy and the enemy makes an attack against you.
Hack and slash is for attacking a prepared enemy plain and simple. If the enemy
isn’t prepared for your attack—if they don’t know you’re there or they’re
restrained and helpless—then that’s not hack and slash. You just deal your
damage or murder them outright, depending on the situation. Nasty stuff.

The enemy’s counterattack can be any GM move made directly with that creature. A
goblin might just attack you back, or they might jam a poisoned needle into your
veins. Life’s tough, isn’t it?

Note that an “attack” is some action that a player undertakes that has a chance
of causing physical harm to someone else. Attacking a dragon with inch-thick
metal scales full of magical energy using a typical sword is like swinging a
meat cleaver at a tank: it just isn’t going to cause any harm, so hack and slash
doesn’t apply. Note that circumstances can change that: if you’re in a position
to stab the dragon on its soft underbelly (good luck with getting there) it
could hurt, so it’s an attack.

If the action that triggers the move could reasonably hurt multiple targets roll
once and apply damage to each target (they each get their armor).

Some attacks may have additional effects depending on the triggering action, the
circumstances, or the weapons involved. An attack could also knock someone down,
restrain them, or leave a big bloody splatter.
GM: Jarl, you’re up to your not-inconsiderable belly in slavering goblins. They
have you surrounded, knives bared. What do you do?
Jarl: I’ve had enough of this! I wallop the closest goblin with my hammer.
GM: Okay, then. This is definitely combat, you’re using hack and slash.
Roll+Str.
Jarl: I got an 11. It says here that I have a choice. Fear is for the weak, let
those goblins come!
GM: You smash your hammer into the nearest goblin and are rewarded by the
satisfying sound of the crunching of his bones. That and a knife wound as the
goblin counterattacks. He deals 4 damage to you. What do you do?
GM: Cadeus, from the shadows, you’ve got the drop on those orc warriors.
Cadeus: I leap out and bring my sword down in a sweeping arc! Like this! Yeeeah!
GM: Well, they weren’t expecting that, they’re caught totally off guard and you
slice into one. Roll damage.
Cadeus: I deal 6 damage.
GM: The orc collapses in a bloody heap! The second orc freezes and then he’s
grinning at you with that horrible tusked mouth, raising his signal horn from
his belt! What do you do?
GM: Bartleby, you’ve got Finbar the Magnificent, mightiest duelist in the land,
completely disarmed and at sword point.
Bartleby: I won’t let you betray me again, Finbar! I run him through.
GM: Well, okay, that’s a hack and slash, roll+Str.
Bartleby: If you say so… I got a 7.
GM: Okay, you run him through because he can’t even defend himself and… umm,
wait. You know what, he’s not in melee with you at all. He’s helpless, forget
hack and slash, he’s toast. He slumps to the ground, coughing up blood but the
sound of the guard alarm rings out. What do you do?
** Volley
When you take aim and shoot at an enemy at range, roll+Dex. ✴On a 10+, you have
a clear shot—deal your damage. ✴On a 7–9, choose one (whichever you choose you
deal your damage):
    - You have to move to get the shot placing you in danger as described by the
      GM
    - You have to take what you can get: -1d6 damage
    - You have to take several shots, reducing your ammo by one
Volley covers the entire act of drawing, aiming, and firing a ranged weapon or
throwing a thrown weapon. The advantage to using a ranged weapon over melee is
that the attacker is less likely to be attacked back. Of course they do have to
worry about ammunition and getting a clear shot though.

On a 7–9, read “danger” broadly. It can be bad footing or ending in the path of
a sword or maybe just giving up your sweet sniper nest to your enemies. Whatever
it is, it’s impending and it’s always something that causes the GM to say “What
do you do?” Quite often, the danger will be something that will then require you
to dedicate yourself to avoiding it or force you to defy danger.

If you’re throwing something that doesn’t have ammo (maybe you’ve got a move
that makes your shield throwable) you can’t choose to mark off ammo. Choose from
the other two options instead.
Aranwe: So, I’m stuck down here on the floor of the ritualarium and that orc
eyegouger is chanting his ritual up on the pedestal? Since Thelian has the rest
of the rabble busy, I’ll aim my bow and take a shot at the chanting orc.
GM: An excellent choice—sounds like volley to me.
Aranwe: I got an 8, damn. Well, I’m low on arrows and even lower on HP. I better
take what I can get. I roll my damage, then subtract the results of a d6, right?
I got a 3. Is that enough to distract him, at least?
GM: Sure! The arrow digs into the eyegouger’s leg and he roars in pain,
interrupting the ritual temporarily. Unfortunately, it looks like interruption
might just be worse—a terrible rumbling echoes from the pit under the pedestal
and the masonry of the room begins to crumble. What do you do?
Halek: Kobolds and an ogre? Man, what’s going on here? Well, if they’re coming
to get me, I might as well let my arrows say hello. I take a shot at the mob. I
rolled an 8.
GM: Well, what’ll it be? Danger? Ammo?
Halek: I’ll take the danger.
GM: Well, the kobolds swarm you and you manage to hit one as they approach—he
falls down but as the rest approach, you realize you’ve lost track of the ogre.
He smashes you with his club and you take 12 damage!
Halek: 12 damage? That’s the danger?
GM: You’re right, that’s not just danger. Okay, so you’re not mush yet—the ogre
is looming behind you and that club is flying down at your head! What do you do?
** Defy Danger
When you *act despite an imminent threat* or *suffer a calamity*, say how you
deal with it and roll. If you do it…
    - …by powering through, +Str
    - …by getting out of the way or acting fast, +Dex
    - …by enduring, +Con
    - …with quick thinking, +Int
    - …through mental fortitude, +Wis
    - …using charm and social grace, +Cha
✴On a 10+, you do what you set out to, the threat doesn’t come to bear. ✴On a
7–9, you stumble, hesitate, or flinch: the GM will offer you a worse outcome,
hard bargain, or ugly choice.
You defy danger when you do something in the face of impending peril. This may
seem like a catch-all. It is! Defy danger is for those times when it seems like
you clearly should be rolling but no other move applies.

Defy danger also applies when you make another move despite danger not covered
by that move. For example, hack and slash assumes that’s you’re trading blows in
battle—you don’t need to defy danger because of the monster you’re fighting
unless there’s some specific danger that wouldn’t be part of your normal attack.
On the other hand, if you’re trying to hack and slash while spikes shoot from
hidden traps in the walls, those spikes are a whole different danger.

Danger, here, is anything that requires resilience, concentration, or poise.
This move will usually be called for by the GM. She’ll tell you what the danger
is as you make the move. Something like “You’ll have to defy danger first. The
danger is the steep and icy floor you’re running across. If you can keep your
footing, you can make it to the door before the necromancer’s magic gets you.”

Which stat applies depends on what action you take and your action has to
trigger the move. That means you can’t defy danger from a steep and icy floor
with a charming smile just so you can use Cha, since charmingly smiling at the
icy floor does nothing to it. On the other hand, making a huge leap over the ice
would be Str, placing your feet carefully would be Dex, and so on. Make the move
to get the results.
GM: Emory, as you climb up the side of the ravine you spy a cultist on a ledge
nearby who evokes a frost spell and covers the side of the cliff with ice! If
you want to keep climbing, you need to defy danger or you’ll fall.
Emory: No way, I am too tough. I grit my teeth and dig my nails into the wall,
climbing one hand at a time. I’m using Con, okay? I got an 8, though…
GM: Hmm, well, I think the only way you can gain any traction, tough guy, is if
you use your dagger to pull yourself up the last few feet. It’s going to be
lodged in there until you have some time to pull it loose and there’s an angry
spellcaster nearby.
Emory: I can always get a new dagger when I get home. Time to finish this climb
and that cultist.
GM: The athach is swinging his burly third arm down at you, knobby fingers
gripping a broken branch. What are you doing, Valeria?
Valeria: So he wants to fight, huh? Let’s do it. I hack and slash him, swinging
my sword at his legs.
GM: Now hold on there, champ. He’s already got you at a disadvantage. You can
jump into the fray but you’ll take that club head on unless you defy danger
first.
Valeria: Pfft, he’s no match for Valeria the Red! I leap aside like a leaf in
the wind, then I start hacking and slashing.
GM: Defy danger with your Dex, please and thank you.
Octavia: I’ve had enough of this ogre, I’m going to drop my shield and swing my
hammer in both hands. Hack and slash, right?
GM: You drop your shield? That’s a bad idea–now you have to defy danger because
the ogre is going to bash you.
Octavia: Are you sure? Isn’t that what hack and slash is? Trading blows and
stuff?
GM: Yes, duh, of course. I need another cup of coffee–hack and slash it is, make
your move!
** Defend
When you *stand in defense of a person, item, or location* under attack,
roll+Con. ✴On a 10+, hold 3. ✴On a 7–9, hold 1. As long as you stand in defense,
when you or the thing you defend is attacked you may spend hold, 1 for 1, to
choose an option:
    - Redirect an attack from the thing you defend to yourself
    - Halve the attack’s effect or damage
    - Open up the attacker to an ally giving that ally +1 forward against the
      attacker
    - Deal damage to the attacker equal to your level
Defending something means standing nearby and focusing on preventing attacks
against that thing or stopping anyone from getting near it. When you’re no
longer nearby or you stop devoting your attention to incoming attacks then you
lose any hold you might have had.

You can only spend hold when someone makes an attack on you or the thing you’re
defending. The choices you can make depend on the attacker and the type of
attack. In particular, you can’t deal damage to an attacker who you can’t reach
with your weapon.

An attack is any action you can interfere with that has harmful effects. Swords
and arrows are attacks, of course, but so are spells, grabs, and charges.

If the attack doesn’t deal damage then halving it means the attacker gets some
of what they want but not all of it. It’s up to you and the GM to work out what
that means depending on the circumstances. If you’re defending the Gem Eye of
Oro-Uht and an orc tries to grab it from its pedestal then half effect might
mean that the gem gets knocked to the floor but the orc doesn’t get his hands on
it, yet. Or maybe the orc gets a hold of it but so do you—now you’re both
fighting over it, tooth and nail. If you and the GM can’t agree on a halved
effect you can’t choose that option.

Defending yourself is certainly an option. It amounts to giving up on making
attacks and just trying to keep yourself safe.
GM: Avon, you begin weaving the spell to push the necromancer’s ghost back
through the gates but the zombies are bearing down on you.
Lux: Don’t worry, squishy Avon, I will save you. While Avon casts his spell, I
swear to protect him—I slam my hammer on my shield and yell “If you want to stop
him, you’ll have to come through me.” I’d like to defend Avon.
GM: And with such gusto, too. Roll+Con.
Lux: I get an 11, three hold, right?
Avon: Better get ready to use it, Lux. I got an 8 on my spellcasting roll—I
choose to put myself in danger.
GM: Of course you do. The zombies are drawn by the magical disturbance, lurching
toward you on the attack. Suddenly, you’re swarmed by them, they’re everywhere!
What do you do?
Avon: Squeak helplessly?
Lux: I’m on it. I spend a point of my hold to redirect the attack to me—I shove
Avon aside and let the full fury of my goodness spill out in waves, angering the
undead. To be safe, I’m going to whip my hammer in an arc and deal my damage. I
might as well use it all up and reduce the damage by half. My god protects us!
GM: So, Hadrian, you’ve been defending Durga while she heals Willem, but now
Willem is better. What do you do?
Durga: I leap forward to drive back the troglodytes!
Hadrian: I want to tangle with this crocodilian.
GM: Okay, Durga, the trogs come at you with their clubs.
Hadrian: No way, I still have hold left over, I want to spend it to redirect
that attack to myself.
GM: You two are spread out, now. How are you going to do that if you’re 20 yards
away? You lost your hold when you attacked the croc, my friend.
Hadrian: Yeah, I guess I’m not “standing in defense” anymore. Forget it, you’re
on your own, Durga!
** Spout Lore
When you *consult your accumulated knowledge about something*, roll+Int. ✴On a
10+, the GM will tell you something interesting and useful about the subject
relevant to your situation. ✴On a 7–9, the GM will only tell you something
interesting—it’s on you to make it useful. The GM might ask you “How do you know
this?” Tell them the truth, now.
You spout lore any time you want to search your memory for knowledge or facts
about something. You take a moment to ponder the things you know about the
Orcish Tribes or the Tower of Ul’dammar and then reveal that knowledge.

The knowledge you get is like consulting a bestiary, travel guide, or library.
You get facts about the subject matter. On a 10+ the GM will show you how those
facts can be immediately useful, on a 7–9 they’re just facts.

On a miss the GM’s move will often involve the time you take thinking. Maybe you
miss that goblin moving around behind you, or the tripwire across the hallway.
It’s also a great chance to reveal an unwelcome truth.

Just in case it isn’t clear: the answers are always true, even if the GM had to
make them up on the spot. Always say what honesty demands.
Fenfaril: The floor was illusory? Damn those gnomes. Damn them straight to
wherever gnomes go when they’re dead.
GM: Heh, yep. You’re in a murky pit, and there’s a shadowy humanoid shape,
mottled and eyeless, moving towards you, mumbling.
Fenfaril: Mumbling shape, huh? What is that thing? Is it going to attack me? I’m
sure I’ve read about them somewhere before, maybe at school?
GM: Could be. Spout lore!
Fenfaril: Bestow your knowledge upon me, brain. I rolled an 8.
GM: Well, of course you know of these things—the name escapes you but you
definitely remember a drawing of a creature like this. It was in a hallway,
standing guard over something. You know there’s a trick to get it to let you
pass but you can’t quite remember. Why not?
Fenfaril: Obviously I was hungover that day. I was a terrible student. A trick,
you say? Hmm…
Vitus: I got a 10 on my spout lore about this gilded skull.
GM: You’re pretty sure you recognize the metalwork of Dis, the living city.
Vitus: …and? I did get a 10!
GM: Right, of course. Well, you recognize a few glyphs specifically. They’re
efreeti, marks of a fire spell, but they’re different, a kind of transmutation
magic. I bet if you cast a spell into the skull, it’ll turn it into a fire
spell.
Vitus: Magic missiles of fire—hurrah!
** Discern Realities
When you closely study a situation or person, roll+Wis. ✴On a 10+, ask the GM 3
questions from the list below. ✴On a 7–9, ask 1.

Either way, take +1 forward when acting on the answers.
    - What happened here recently?
    - What is about to happen?
    - What should I be on the lookout for?
    - What here is useful or valuable to me?
    - Who’s really in control here?
    - What here is not what it appears to be?
To discern realities you must closely observe your target. That usually means
interacting with it or watching someone else do the same. You can’t just stick
your head in the doorway and discern realities about a room. You’re not merely
scanning for clues—you have to look under and around things, tap the walls, and
check for weird dust patterns on the bookshelves. That sort of thing.

Discerning realities isn’t just about noticing a detail, it’s about figuring out
the bigger picture. The GM always describes what the player characters
experience honestly, so during a fight the GM will say that the kobold mage
stays at the other end of the hall. Discerning realities could reveal the reason
behind that: the kobold’s motions reveal that he’s actually pulling energy from
the room behind him, he can’t come any closer.

Just like spout lore, the answers you get are always honest ones. Even if the GM
has to figure it out on the spot. Once they answer, it’s set in stone. You’ll
want to discern realities to find the truth behind illusions—magical or
otherwise.

Unless a move says otherwise players can only ask questions from the list. If a
player asks a question not on the list the GM can tell them to try again or
answer a question from the list that seems equivalent.

Of course, some questions might have a negative answer, that’s fine. If there
really, honestly is nothing useful or valuable here, the GM will answer that
question with “Nothing, sorry.”
Omar: I don’t trust this room—I’m going to poke around a little. I take out my
tools and start messing with stuff. I pull candlesticks and tap the walls with
my hammer. My usual tricks.
GM: Discern realities?
Omar: Oh yes. I discern all the realities. I got a 12. I want to know “What here
is not as it appears to be?”
GM: Well, it’s obvious to you that the wall on the north side of the room has a
hollow spot. The stones are newer and the mortar is fresher, probably a hidden
alcove or passageway.
Omar: I want to ask another one. “Who sealed the room.”
GM: That’s not on the list, so I’m going pretend you asked “What happened here
recently.” Looking at the stonework, you notice the wall actually bends out in
places. The work is shoddy and awful—looks to you like the work of goblins. The
only way it’d get bent out that way, though, is if there was something pushing
it from within.
Omar: So either the goblins blocked it from the other side, or there’s something
in there that tried to get out.
GM: Bingo.
** Parley
When you have leverage on a GM Character and manipulate them, roll+Cha. Leverage
is something they need or want. ✴On a 10+, they do what you ask if you first
promise what they ask of you. ✴On a 7–9, they will do what you ask, but need
some concrete assurance of your promise, right now.
Parley covers a lot of ground including old standbys like intimidation and
diplomacy. You know you’re using parley when you’re trying to get someone to do
something for you by holding a promise or threat over them. Your leverage can be
nasty or nice, the tone doesn’t matter.

Merely asking someone politely isn’t parleying. That’s just talking. You say,
“Can I have that magic sword?” and Sir Telric says, “Hell no, this is my blade,
my father forged it and my mother enchanted it” and that’s that. To parley, you
have to have leverage. Leverage is anything that could lure the target of your
parley to do something for you. Maybe it’s something they want or something they
don’t want you to do. Like a sack of gold. Or punching them in the face. What
counts as leverage depends on the people involved and the request being made.
Threaten a lone goblin with death and you have leverage. Threaten a goblin
backed up by his gang with death and he might think he’s better off in a fight.

On a 7+ they ask you for something related to whatever leverage you have. If
your leverage is that you’re standing before them sharpening your knife and
insinuating about how much you’d like to shank them with it they might ask you
to let them go. If your leverage is your position in court above them they might
ask for a favor.

Whatever they ask for, on a 10+, you just have to promise it clearly and
unambiguously. On a 7–9, that’s not enough: you also have to give them some
assurance, right now, before they do what you want. If you promise that you’ll
ensure their safety from the wolves if they do what you want and you roll a 7–9
they won’t do their part until you bring a fresh wolf pelt to prove you can do
it, for example. It’s worth noting that you don’t actually have to keep your
promise. Whether you’ll follow up or not, well, that’s up to you. Of course
breaking promises leads to problems. People don’t take kindly to oath-breakers
and aren’t likely to deal with them in the future.

In some cases when you state what you want you may include a possible promise
for the creature to make, as in “flee and I’ll let you live.” It’s up to the
target of the parley if that’s the promise they want or if they have something
else in mind. They can say “yes, let me live and I’ll go” (with assurances, if
you rolled a 7–9) or “promise me you won’t follow me.”
Leena: “Lord Hywn, I need you to vouch for me or the Queen will never grant me
an audience.”
GM: He’s not really convinced—it could be a big hit to his reputation if you
embarrass him. “Why should I help you, Leena?”
Leena: Oh, while I talk to him, I absentmindedly play with the signet ring from
that assassin we killed. The one he hired to off the prince. I make sure he sees
it.
GM: Oh boy, okay. Roll parley.
Leena: An 8.
GM: “Enough being coy!” he looks at you cold and angry. “You and I both know you
murdered my hired man. Give me the ring, swear to silence, and I’ll do as you
ask.”
Leena: I toss it to him. We can always dig up more dirt on this scumbag later.
Pendrell: This is the place where One Eye plays cards, right? Okay, I walk up to
the guard. “Hey there fellows, care to, you know, open the door and let me in?”
and I’m being all suave and cool so they’ll do it. Parley is roll+Cha right?
GM: Not so fast, slick. All you’ve done is say what you want. The big smelly one
on the right steps in front of you and says, “Sorry sir, private game,” all
bored-sounding. It’s like he hates his job and wishes he were someplace else. If
you want to parley, you’re going to need some leverage. Maybe a bribe?
** Aid or Interfere
When you *help or hinder someone *, roll+bond with them. ✴On a 10+, they take +1
or -2 to their roll, your choice. ✴On a 7–9, they still get a modifier, but you
also expose yourself to danger, retribution, or cost.
Any time you feel like two players should be rolling against each other, the
defender should be interfering with the attacker. This doesn’t always mean
sabotaging them. It can mean anything from arguing against a parley to just
being a shifty person who’s hard to discern. It’s about getting in the way of
another players’ success.

Always ask the person aiding or interfering how they are doing it. As long as
they can answer that, they trigger the move. Sometimes, as the GM, you’ll have
to ask if interference is happening. Your players might not always notice
they’re interfering with each other.

Aid is a little more obvious. If a player can explain how they’re helping with a
move and it makes sense, let them roll to aid.

No matter how many people aid or interfere with a given roll, the target only
gets the +1 or -2 once. Even if a whole party of adventurers aid in attacking an
ogre, the one who makes the final attack only gets +1.
GM: Ozruk, you stand alone and bloodied before a pack of angry hellhounds.
Behind you cowers the Prince of Lescia, weeping in terror.
Ozruk: I stand firm and lift my shield. Despite certain doom, I will do my duty
and defend the princeling.
Aronwe: I emerge from the shadows and draw my sword! “Doom is not so certain,
dwarf!” I stand beside him. I want to help him defend. “Though I do not know you
well, I have seen you in battle, Ozruk. If we are to die today, we die as
brothers!” I don’t have any bonds with him but I want to try anyway.
GM: Touching, really. Okay, roll+0 and if you succeed, Ozruk, take +1 to your
defend attempt. Here we go!
* Special Moves
Special moves are moves that come up less often or in more specific situations.
They’re still the basis of what characters do in Dungeon World—particularly what
they do between dungeon crawls and high-flying adventures.
** Last Breath
When you’re dying you catch a glimpse of what lies beyond the Black Gates of
Death’s Kingdom (the GM will describe it). Then roll (just roll, +nothing—yeah,
Death doesn’t care how tough or cool you are). ✴On a 10+, you’ve cheated
Death—you’re in a bad spot but you’re still alive. ✴On a 7–9, Death himself will
offer you a bargain. Take it and stabilize or refuse and pass beyond the Black
Gates into whatever fate awaits you. ✴On 6-, your fate is sealed. You’re marked
as Death’s own and you’ll cross the threshold soon. The GM will tell you when.
The Last Breath is that moment standing between life and death. Time stands
still as Death appears to claim the living for his own. Even those who do not
pass beyond the Black Gates catch a glimpse of the other side and what might
await them—friends and enemies past, rewards or punishment for acts in life or
other, stranger vistas. All are changed in some way by this moment—even those
who escape.

There are three outcomes to this move. On a 10+, the Character has cheated Death
in some meaningful way. He’s escaped with something that, by rights, isn’t his
anymore. Death is powerless to stop this, but he remembers this slight. On a
7–9, the GM should offer a real choice with significant consequence. Think about
the behaviors of the character and the things you’ve learned about him in play.
Death knows and sees all and tailors his bargains accordingly. This is a trade,
remember. Offer something that will be a challenge to play out but will lead the
game in fun new direction. On a miss, death is inevitable. The most obvious
approach is to say “Death takes you across the threshold, into his bleak
kingdom.” and move on. However, sometimes Death comes slowly. You might say “you
have a week to live” or “you can feel the cold hand of Death on you…” and leave
it at that, for now. The player may want to give in and accept death at this
point—that’s okay. Let them create a new character as normal. The key thing to
remember is that a brush with death, succeed or fail, is a significant moment
that should always lead to change.
GM: Sparrow, as the knife blade disappears into your guts, the world fades away
and you stand before the Black Gates of Death. Among the throngs of suffering
souls, you spot Lord Hwyn, that sickly cur. It looks like all his ill deals
caught up with him at last. He spots you across the bleak gulf and you feel the
chill of his hunger in your very soul. Take your Last Breath.
Sparrow: Heavy. I got a 9.
GM: Death appears to you, wisps of black cloth dancing around his shadowy form.
A pale hand touches your face. You hear his voice in your mind. “Come to me so
soon, pretty Sparrow? You follow a river of souls, sent here by your blade. I do
so love you for them. I’ll return you to the world, but you must make me a
promise. In shadow you dwell, so shadow you shall become. Shun the light of day
forever or find a quick trip back to my company. What do you say, little thief?”
Sparrow: (gulp)
** Encumbrance
When you make a move while carrying weight you may be encumbered. If your weight
carried is:
    - Equal to or less than your load, you suffer no penalty
    - Less than or equal to your load+2, you take -1 ongoing until you lighten
      your burden
    - Greater than your load+2, you have a choice: drop at least 1 weight and
      roll at -1, or automatically fail
A PC’s load stat is determined by their class and Str. Being able to haul more
is a clear benefit when trying to carry treasure out of a dungeon or just making
sure you can bring along what you need.

This move only applies to things a person could walk around with and still act.
Carrying a boulder on your back is not encumbrance—you can’t really act or move
much with it. It affects what moves you can make appropriately in the fiction.
** Make Camp
When you *settle in to rest* consume a ration. If you’re somewhere dangerous
decide the watch order as well. If you have enough XP you may level up. When you
wake from at least a few uninterrupted hours of sleep heal damage equal to half
your max HP.
You usually make camp so that you can do other things, like prepare spells or
commune with your god. Or, you know, sleep soundly at night. Whenever you stop
to catch your breath for more than an hour or so, you’ve probably made camp.

Staying a night in an inn or house is making camp, too. Regain your hit points
as usual, but only mark off a ration if you’re eating from the food you carry,
not paying for a meal or receiving hospitality.
** Take Watch
When you’re on watch and something approaches the camp roll+Wis. ✴On a 10+,
you’re able to wake the camp and prepare a response, everyone in the camp takes
+1 forward. ✴On a 7–9, you react just a moment too late; your companions in camp
are awake but haven’t had time to prepare. They have weapons and armor but
little else. ✴On a miss, whatever lurks outside the campfire’s light has the
drop on you.
** Undertake a Perilous Journey
When you *travel through hostile territory*, choose one member of the party to
act as /trailblazer/, one to /scout/ ahead, and one to be /quartermaster/. Each
character with a job to do rolls+Wis. ✴On a 10+:
    - the quartermaster reduces the number of rations required by one
    - the trailblazer reduces the amount of time it takes to reach your
      destination (the GM will say by how much)
    - the scout will spot any trouble quick enough to let you get the drop on it
✴On a 7–9, each role performs their job as expected: the normal number of
rations are consumed, the journey takes about as long as expected, no one gets
the drop on you but you don’t get the drop on them either.
You can’t assign more than one job to a character. If you don’t have enough
party members, or choose not to assign a job, treat that job as if it had been
assigned and the responsible player had rolled a 6.

Distances in Dungeon World are measured in rations. A ration is the amount of
supplies used up in a day. Journeys take more rations when they are long or when
travel is slow.

A perilous journey is the whole way between two locations. You don’t roll for
one day’s journey and then make camp only to roll for the next day’s journey,
too. Make one roll for the entire trip.

This move only applies when you know where you’re going. Setting off to explore
is not a perilous journey. It’s wandering around looking for cool things to
discover. Use up rations as you camp and the GM will give you details about the
world as you discover them.
** End of Session
When you *reach the end of a session*, choose one of your bonds that you feel is
resolved (completely explored, no longer relevant, or otherwise). Ask the player
of the character you have the bond with if they agree. If they do, mark XP and
write a new bond with whomever you wish.

Once bonds have been updated look at your alignment. If you fulfilled that
alignment at least once this session, mark XP. Then answer these three questions
as a group:
    - Did we learn something new and important about the world?
    - Did we overcome a notable monster or enemy?
    - Did we loot a memorable treasure?
For each “yes” answer everyone marks XP.
** Level Up
When you *have downtime (hours or days) and XP equal to (or greater than) your
current level+7*, you can reflect on your experiences and hone your skills.
    - Subtract your current level+7 from your XP.
    - Increase your level by 1.
    - Choose a new advanced move from your class.
    - If you are the wizard, you also get to add a new spell to your spellbook.
    - Choose one of your stats and increase it by 1 (this may change your
      modifier). Changing your Constitution increases your maximum and current
      HP. Ability scores can’t go higher than 18.
** Carouse
When you return triumphant and throw a big party, spend 100 coins and roll +1
for every extra 100 coins spent. ✴On a 10+, choose 3. ✴On a 7–9, choose 1. ✴On a
miss, you still choose one, but things get really out of hand (the GM will say
how).
    - You befriend a useful NPC.
    - You hear rumors of an opportunity.
    - You gain useful information.
    - You are not entangled, ensorcelled, or tricked.
You can only carouse when you return triumphant. That’s what draws the crowd of
revelers to surround adventurers as they celebrate their latest haul. If you
don’t proclaim your success or your failure, then who would want to party with
you anyway?
** Supply
When you go to buy something with gold on hand, if it’s something readily
available in the settlement you’re in, you can buy it at market price. If it’s
something special, beyond what’s usually available here, or non-mundane,
roll+Cha. ✴On a 10+, you find what you’re looking for at a fair price. ✴On a
7–9, you’ll have to pay more or settle for something that’s not exactly what you
wanted, but close. The GM will tell you what your options are.
** Recover
When you *do nothing but rest in comfort and safety* after a day of rest you
recover all your HP. After three days of rest you remove one debility of your
choice. If you’re under the care of a healer (magical or otherwise) you heal a
debility for every two days of rest instead.
** Recruit
When you put out word that you’re looking to hire help, roll:
    - +1 if you make it known that your pay is generous
    - +1 if you make it known what you’re setting out to do
    - +1 if you make it known that they’ll get a share of whatever you find
    - +1 if you have a useful reputation around these parts
✴On a 10+, you’ve got your pick of a number of skilled applicants, your choice
who you hire, no penalty for not taking them along. ✴On a 7–9, you’ll have to
settle for someone close to what you want or turn them away. ✴On a miss someone
influential and ill-suited declares they’d like to come along (a foolhardy
youth, a loose-cannon, or a veiled enemy, for example), bring them and take the
consequences or turn them away. If you turn away applicants you take -1 forward
to recruit.
** Outstanding Warrants
When you *return to a civilized place in which you’ve caused trouble before*,
roll+Cha. ✴On a 10+, word has spread of your deeds and everyone recognizes you.
✴On a 7–9, as above, and the GM chooses a complication:
    - The local constabulary has a warrant out for your arrest.
    - Someone has put a price on your head.
    - Someone important to you has been put in a bad spot as a result of your
      actions.
This move is only for places where you’ve caused trouble, not every patch of
civilization you enter. Being publicly caught up in someone else’s trouble still
triggers this move.

Civilization generally means the villages, towns and cities of humans, elves,
dwarves, and halflings but it can also apply to any relatively lawful
establishment of monstrous species, such as orcs or goblins. If the PCs have
stayed in a place as part of the community, it counts as civilization.
** Bolster
When you *spend your leisure time in study, meditation, or hard practice,* you
gain preparation. If you prepare for a week or more, take 1 preparation. If you
prepare for a month or longer, take 3 instead. When your preparation pays off
spend 1 preparation for +1 to any roll. You can only spend one preparation per
roll.