
* The Paladin
Hell awaits. An eternity of torment in fire or ice or whatever best suits the
sins of the damned throngs of Dungeon World. All that stands between the pits of
that grim torture and salvation is you. Holy man, armored war machine, templar
of the Good and the Light, right? The cleric may say his prayers at night to the
gods, dwelling in their heavens. The fighter may wield his sharp sword in the
name of “good” but you know. Only you.

Eyes, hands, and sweet killing blow of the gods, you are. Yours is the gift of
righteousness and virtue. Of justice. Vision, too. A purity of intent that your
companions do not have.

So guide these fools, paladin. Take up your holy cause and bring salvation to
the wastrel world. 

Vae victis, right?
** Names
Thaddeus, Augustine, Lux, Cassius, Hadrian, Lucia, Octavia, Regulus, Valeria,
Sanguinus, Titanius
** Look
Choose one for each:
Kind Eyes, Fiery Eyes, or Glowing Eyes
Helmet, Styled Hair, or Bald
Worn Holy Symbol or Fancy Holy Symbol
Fit Body, Bulky Body, or Thin Body
** Stats
Your maximum HP is 10+Constitution.
Your base damage is d10.
** Starting Moves
You are human, so you get this move.
*** Human
When you *pray for guidance, even for a moment, and ask, “What here is evil?”*
the GM will tell you, honestly.
You start with these moves:
*** Lay on Hands (Cha)
When you *touch someone, skin to skin, and pray for their well-being *,
roll+CHA. ✴On a 10+ you heal 1d8 damage or remove one disease. ✴On a 7–9, they
are healed, but the damage or disease is transferred to you.
*** Armored
You ignore the clumsy tag on armor you wear.
*** I Am the Law
When you *give an NPC an order based on your divine authority*, roll+Cha. ✴On a
7+, they choose one:
    - Do what you say
    - Back away cautiously, then flee
    - Attack you
✴On a 10+, you also take +1 forward against them. ✴On a miss, they do as they
please and you take -1 forward against them.
*** Quest
When you *dedicate yourself to a mission through prayer and ritual cleansing*,
state what you set out to do:
    - Slay _______, a great blight on the land
    - Defend _______ from the iniquities that beset them
    - Discover the truth of _______
Then choose up to two boons:
    - An unwavering sense of direction to _______.
    - Invulnerability to _______ (e.g., edged weapons, fire, enchantment, etc.)
    - A mark of divine authority
    - Senses that pierce lies
    - A voice that transcends language
    - A freedom from hunger, thirst, and sleep
The GM will then tell you what vow or vows is required of you to maintain your
blessing:
    - Honor (forbidden: cowardly tactics and tricks)
    - Temperance (forbidden: gluttony in food, drink, and pleasure of the flesh)
    - Piety (required: observance of daily holy services)
    - Valor (forbidden: suffering an evil creature to live)
    - Truth (forbidden: lies)
    - Hospitality (required: comfort to those in need, no matter who they are)
** Alignment
Choose an alignment:
*** Lawful
Deny mercy to a criminal or unbeliever.
*** Good
Endanger yourself to protect someone weaker than you.
** Gear
Your load is 12+Str. You start with dungeon rations (5 uses, 1 weight), scale
armor (2 armor, 3 weight), and some mark of faith, describe it (0 weight).
Choose your weapon:
    - Halberd (reach, +1 damage, two-handed, 2 weight)
    - Long sword (close, +1 damage, 1 weight) and shield (+1 armor, 2 weight)
Choose one:
    - Adventuring gear (1 weight)
    - Dungeon rations (1 weight) and healing potion (0 weight)
** Bonds
Fill in the name of one of your companions in at least one:

_______________’s misguided behavior endangers their very soul!

_______________ has stood by me in battle and can be trusted completely.

I respect the beliefs of _______________ but hope they will someday see the true
way.

_______________ is a brave soul, I have much to learn from them.
** Advanced Moves
When you gain a level from 2–5, choose from these moves.
*** Divine Favor
Dedicate yourself to a deity (name a new one or choose one that’s already been
established). You gain the commune and cast a spell cleric moves. When you
select this move, treat yourself as a cleric of level 1 for using spells. Every
time you gain a level thereafter, increase your effective cleric level by 1.
*** Bloody Aegis
When you take damage you can grit your teeth and accept the blow. If you do you
take no damage but instead suffer a debility of your choice. If you already have
all six debilities you can’t use this move.
*** Smite
While on a quest you deal +1d4 damage.
*** Exterminatus
When you *speak aloud your promise to defeat an enemy*, you deal +2d4 damage
against that enemy and -4 damage against anyone else. This effect lasts until
the enemy is defeated. If you fail to defeat the enemy or give up the fight, you
can admit your failure, but the effect continues until you find a way to redeem
yourself.
*** Charge!
When you *lead the charge into combat*, those you lead take +1 forward.
*** Staunch Defender
When you defend you always get +1 hold, even on a 6-.
*** Setup Strike
When you hack and slash, choose an ally. Their next attack against your target
does +1d4 damage.
*** Holy Protection
You get +1 armor while on a quest.
*** Voice of Authority
Take +1 to order hirelings.
*** Hospitaller
When you heal an ally, you heal +1d8 damage.
When you gain a level from 6–10, choose from these moves or the level 2–5 moves.
*** Evidence of Faith
Requires: Divine Favor
When you *see divine magic as it happens*, you can ask the GM which deity
granted the spell and its effects. Take +1 when acting on the answers.
*** Holy Smite
Replaces: Smite
While on a quest you deal +1d8 damage.
*** Ever Onward
Replaces: Charge!
When you lead the charge into combat, those you lead take +1 forward and +2
armor forward.
*** Impervious Defender
Replaces: Staunch Defender
When you defend you always get +1 hold, even on a 6-. When you get a 12+ to
defend instead of getting hold the nearest attacking creature is stymied giving
you a clear advantage, the GM will describe it.
*** Tandem Strike
Replaces: Setup Strike
When you hack and slash, choose an ally. Their next attack against your target
does +1d4 damage and they take +1 forward against them.
*** Divine Protection
Replaces: Holy Protection
You get +2 armor while on a quest.
*** Divine Authority
Replaces: Voice of Authority
Take +1 to order hirelings. When you roll a 12+ the hireling transcends their
moment of fear and doubt and carries out your order with particular
effectiveness or efficiency.
*** Perfect Hospitaller
Replaces: Hospitaller
When you heal an ally, you heal +2d8 damage.
*** Indomitable
When you suffer a debility (even through Bloody Aegis) take +1 forward against
whatever caused it.
*** Perfect Knight
When you quest you choose three boons instead of two.