* Planar Powers
** Angel Solitary, Terrifying, Divine, Intelligent, Organized
*Sword of Flames (b[2d10]+4 damage, ignores armor) 18 HP 4 Armor*
*Close, Forceful*
*Special Qualities:* Wings
“So was it written that the heavens opened up to Avra’hal and did an angel from
the clouds emerge to speak unto her and so did it appear to her as her firstborn
daughter—beautiful, of ebon skin and golden eyes—and did Avra’hal weep to see
it. ‘Be not afraid,’ it commanded her. ‘Go to the villages I have shown you in
your dreams and unto them show the word I have written on your soul.’ Avra’hal
wept and wept and did agree to do this and did take up her sword and tome and
did into the villages go, a great thirst for blood on her lips for the word the
angel wrote upon the soul of Avra’hal was ‘kill’.” /Instinct/: To share divine
will
    - Deliver visions and prophecy
    - Stir mortals to action
    - Expose sin and injustice
** Barbed Devil Solitary, Large, Planar, Terrifying
*Spines (d10+3 damage, 3 piercing) 16 HP 3 Armor*
*Close, Reach, Messy*
*Special Qualities:* Spines
There are a thousand forms of devil, maybe more. Some common and some unique.
Each time the Inquisitors discover a new one they write it into the Tormentors
Codex and the knowledge is shared among the abbeys in the hope that atrocities
of that particular sort won’t find their way into the world again. The barbed
devil has long been known to the brothers and sisters of the Inquisition. It
appears only at a site of great violence or when called by a wayward summoner.
Covered in sharp quills, this particular demon revels in the spilling of blood,
preferably by impaling victims piecemeal or in whole upon its thorns and letting
them die there. Cruel but not particularly effective beyond slaughter. A low
inquisitorial priority. /Instinct/: To rend flesh and spill blood
    - Impale someone
    - Kill indiscriminately
** Chain Devil Solitary, Planar
*Crush (d10 damage, ignores armor) 12 HP 3 Armor*
*Close, Reach*
Do you think the phrase “drag him to hell” means nothing? It is unfortunately
literal, in the case of the chain devil. Appearing differently to each victim,
this summoned creature has but a single purpose: to wrap its victim up in
binding coils and take it away to a place of torment. Sometimes it will come as
a man-shaped mass of rusting iron, hooks and coils of mismatched links. Other
times, a roiling tangle of rope or kelp or twisted bloody bedsheets. The results
are always the same. /Instinct/: To capture
    - Take a captive
    - Return to whence it came
    - Torture with glee
** Concept Elemental Solitary, Devious, Planar, Amorphous
*Special Qualities:* Ideal form
The planes are not as literal as our world. Clothed in the elemental chaos are
places of stranger stuff than air and water. Here, rivers of time crash upon
shores of crystal fear. Bleak storms of nightmare roil and churn in a
laughter-bright sky. Sometimes, the spirits of these places can be lured into
our world, though they are infinitely more unpredictable and strange than mere
fire or earth might be. Easier to make mistakes, too—one might try calling up a
wealth elemental and be surprised to find a murder elemental instead.
/Instinct/: To perfect its concept
    - Demonstrate its concept in its purest form
** Corrupter Solitary, Devious, Planar, Hoarder
*Secret dagger (w[2d8] damage) 12 HP 0 Armor*
*Close*
“Surely, my good man, you must know why I am here. Must know who I am. You said
the words. You spilled the blood and followed the instructions almost to the
letter. Your pronunciation was a bit off but that’s to be expected. I’ve come to
give you what you’ve always wanted, friend. Glory, love, money? Paltry things
when you’ve the vaults of hell to plumb. Don’t look so shocked, you knew what
this was. You have but one thing we desire. Promise it to us, and the world
shall be yours for the taking. Trust me.” /Instinct/: To bargain
    - Offer a deal with horrible consequences
    - Plumb the vaults of hell for a bargaining chip
    - Make a show of power
** Djinn Group, Large, Magical
*Flame (d8+1 damage, ignores armor) 14 HP 4 Armor*
*Close, Reach*
*Special Qualities:* Made of flame
“Stop rubbing that lamp, you idiot. I do not care what you have read, it will
not grant you wishes. I brought you here to show you something real, something
true. See this mural? It shows the ancient city. The true city that came before.
They called it Majilis and it was made of brass by the spirits. They had golem
servants and human lovers and, in that day, it was said you could trade them a
year of your life for a favor. We are not here to gather treasure this night,
fool, we are here to learn. The djinn still sometimes come to these places, and
you must understand their history if you are to know how to behave. They are
powerful and wicked and proud and you must know them if you hope to survive a
summoning. Now, bring the lamp here and we will light it, it grows dark and
these ruins are dangerous at night.” /Instinct/: To burn eternally
    - Grant power for a price
    - Summon the forces of the City of Brass
** Hell Hound Group, Planar, Organized
*Fiery Bite (d8 damage) 10 HP 1 Armor*
*Close*
*Special Qualities:* Hide of shadow
When one reneges on a deal, does not the debtor come for payment? Does the owed
party not send someone to collect what is due? So too with the Powers Below.
They only want what is theirs. A howling pack of shadows, flame and jagged bone,
driven by the hunting horn. They will not cease, they cannot be evaded.
/Instinct/: To pursue
    - Follow despite all obstacles
    - Spew fire
    - Summon the forces of hell on their target
** Imp Horde, Planar, Intelligent, Organized
*Flame gout (d6 damage, ignores armor) 7 HP 1 Armor*
*Close, Near, Far*
These tiny observer-demons often act as a first-time binding subject by neophyte
warlocks. They can be found infesting arcane cabals, drinking potions when no
one watches, and chasing pets and servants with tiny pitchforks. A caricature of
true demonhood, these little creatures are, thankfully, not too difficult to
bind or extinguish. /Instinct/: To harass
    - Send information back to hell
    - Cause mischief
** Inevitable Group, Large, Magical, Cautious, Amorphous, Planar
*Hammer (d10+1 damage) 21 HP 5 Armor*
*Close, Reach*
*Special Qualities:* Made of Order
All things come to an end. Reality bleeds from the cut of entropy’s knife. At
the edge of time itself stand the inevitable. Massive, powerful and seemingly
carved from star-stuff themselves, the inevitable intervene only where magic or
calamity have undone the skein of fate. Where the arrogant and powerful boil the
substance of destiny away and seek to undermine the very laws of reality, the
inevitable arrive to guide things back to the proper order. Unshakable,
seemingly immune to mortal harm and utterly enigmatic, it is said that the
Inevitable are all that will remain when time’s long thread has run out.
/Instinct/: To preserve order
    - End a spell or effect
    - Enforce a law of nature or man
    - Give a glimpse of destiny
** Larvae Horde, Devious, Planar, Intelligent
*Slime (w[2d4] damage) 10 HP 0 Armor*
*Close*
Those who have seen visions of the Planes Below, and survived with their sanity
intact, speak of masses of these writhing wretches. Maggots with the faces of
men and women, crying out for salvation in a nest of flames. Sometimes, they can
be goaded out through a rip in the planar caul and emerge, wriggling and in
torment, into our world. Once here, they spread misery and sickness during their
mayfly lives before expiring into a slurry of gore. All in all, an enticement to
do good deeds in life. /Instinct/: To suffer
    - Fill them with despair
    - Beg for mercy
    - Draw evil attention
** Nightmare Horde, Large, Magical, Terrifying, Planar
*Trample (d6+1 damage) 7 HP 4 Armor*
*Close, Reach*
*Special Qualities:* Flame and shadow
The herd came from a pact made in the days when folk still inhabited the Blasted
Steppes. Horselords, they were, who travelled those lands. Born in the saddle,
it was said. One of theirs, in a bid to dominate his peers, made a black pact
with some fell power and traded away his finest horses. He had some power,
sure—but what’s a thousand year dynasty when a life is so short? Now the fiends
of the pit ride on the finest horses ever seen. Coats of shining oil and manes
of tormented flame: these are steeds of hell’s cavalry. /Instinct/: To ride
rampant
    - Sheath a rider in hellish flame
    - Drive them away
** Quasit Horde, Planar
*Hellish weaponry (d6 damage) 7 HP 2 Armor*
*Close*
*Special Qualities:* Adaptable form
An imp with some ambition. A quasit is a kind of foot soldier in the demon
realm. A commoner, armed with fangs or claws or wings or some other thing to
give it just a little edge over its hellish peers. Commonly bound by warlocks to
carry heavy loads or build bridges or guard their twisted towers, a quasit can
take on many forms, none of them pleasant. /Instinct/: To serve
    - Attack with abandon
    - Inflict pain
** The Tarrasque Solitary, Huge, Planar
*Special Qualities:* Impervious
The Tarrasque. Legendary unstoppable juggernaut—eater of cities and swallower of
ships, horses, and knights. A creature unseen in an age but about whom all kinds
of stories are told. One thread of truth weaves through these stories. It cannot
be killed. No blade can pierce its stony shell nor spell penetrate the shield it
somehow bears. Stories say, though, that the will of one pure soul can send it
to slumber, though what that means and, by the gods, where such a thing might be
found, pray we do not ever need to learn. It slumbers. Somewhere in the
periphery of the planar edge, it sleeps for now. /Instinct/: To consume
    - Swallow a person, group, or place whole
    - Release a remnant of a long-eaten place from its gullet
** Word Demon Solitary, Planar, Magical
All of mortal magic is just words. Spells are prayers, rote formula, runes cast,
or songs sung. Letters, words, sentences, and syntax strung together in a
language that the whole world itself might understand. By way of words we can
make our fellows cry or exult, can paint pictures and whisper desire to the
gods. No little wonder, then, that in all that power is intent. That every word
we utter, if repeated and meaning or emotion given to it, can spark a kind of
unintentional summoning. Word daemons are called by accident, appear at random
and are often short-lived, but come to attend a particular word. Capricious,
unpredictable and dangerous, yes—but possibly useful, depending on the word.
/Instinct/: To further their word
    - Cast a spell related to their word
    - Bring their word into abundance
